vxl/vxl

vxl_common.cmake

Update the git_url in the sample dashboard scripts

Update git-url to point to the new github location.

---

contrib/brl/bbas/bwm/video/exe/CMakeLists.txt
contrib/brl/bbas/volm/pro/CMakeLists.txt
contrib/brl/bbas/volm/pro/tests/CMakeLists.txt
contrib/brl/bseg/boxm2/ocl/algo/CMakeLists.txt
contrib/brl/bseg/boxm2/ocl/pro/CMakeLists.txt
contrib/brl/bseg/boxm2/ocl/tests/CMakeLists.txt
contrib/brl/bseg/boxm2/vecf/ocl/pro/CMakeLists.txt
contrib/brl/bseg/boxm2/vecf/view/tests/CMakeLists.txt
contrib/brl/bseg/boxm2/volm/pro/CMakeLists.txt
contrib/brl/bseg/boxm2_multi/pro/CMakeLists.txt
contrib/brl/bseg/bstm/ocl/pro/CMakeLists.txt
v3p/openjpeg2/CMakeLists.txt

Fix a variety of link errors on Linux and Mac that arise when building shared libraries.

Fix link errors

---

contrib/brl/bseg/bvxm/breg3d/breg3d_ekf_camera_optimizer.cxx
contrib/brl/bseg/bvxm/breg3d/breg3d_ekf_camera_optimizer.h
contrib/brl/bseg/bvxm/breg3d/tests/test_ekf_camera_optimizer.cxx
contrib/brl/bseg/bvxm/grid/bvxm_voxel_slab.h
contrib/brl/bseg/bvxm/grid/bvxm_voxel_slab.txx

Fix some tests failing due to SEGFAULT on MacOS

Breg3d ekf camera optimizer test fix

---

contrib/brl/bseg/boxm2/boxm2_block.cxx
contrib/brl/bseg/boxm2/boxm2_block.h
contrib/brl/bseg/boxm2/boxm2_block_metadata.h
contrib/brl/bseg/boxm2/boxm2_scene.cxx
contrib/brl/bseg/boxm2/boxm2_scene.h
contrib/brl/bseg/boxm2/ocl/pro/tests/test_filter_kernel.cxx
contrib/brl/bseg/boxm2/ocl/tests/boxm2_ocl_test_utils.cxx
contrib/brl/bseg/boxm2/ocl/tests/test_kernel_filter.cxx
contrib/brl/bseg/boxm2/ocl/tests/test_kernel_vector_filter.cxx
contrib/brl/bseg/boxm2/ocl/tests/test_ocl_lm_phongs_model.cxx

This PR fixes one failing test (boxm2_ocl_pro/test_filter_kernel) and at least fixes a crash in two others.

Boxm2 fixes

---

core/vnl/algo/tests/test_functions.cxx
core/vnl/algo/vnl_brent_minimizer.cxx
core/vnl/algo/vnl_brent_minimizer.h
core/vnl/algo/vnl_lbfgsb.cxx
core/vnl/algo/vnl_lbfgsb.h
core/vnl/algo/vnl_sparse_lm.cxx
core/vnl/examples/calculate.cxx
core/vnl/vnl_bignum.cxx
core/vnl/vnl_bignum.h
core/vnl/vnl_matlab_print_scalar.cxx
core/vnl/vnl_na.cxx

/opt/llvm_trunk/bin/clang-tidy \
-fix \
-checks=-*,clang-analyzer-*,-clang-analyzer-security.insecureAPI.rand,-clang-analyzer-alpha.core.PointerArithm,-clang-analyzer-alpha.unix.Stream,-clang-analyzer-alpha.security.ReturnPtrRange \
-p ~/src/vxl-bld/ \
~/src/vxl/core/vnl/*.cxx

Run clang-tidy Static Analysis on vxl/core/vnl

---

config/cmake/Modules/VXLStandardOptions.cmake

@hjmjohnson @thewtex I tested this in my Linux box against  [this ITK example](http://www.itk.org/Wiki/ITK/Examples/Math/Trig/Atan2ImageFilter).

ENH: Use BUILD_SHARED_LIBS global flag to force

---

core/vgl/algo/vgl_fit_plane_3d.hxx
core/vgl/algo/vgl_h_matrix_3d.h
core/vgl/tests/test_closest_point.cxx
core/vgl/vgl_closest_point.h
core/vgl/vgl_closest_point.hxx
core/vgl/vgl_cubic_spline_3d.h
core/vgl/vgl_plane_3d.hxx
core/vgl/vgl_pointset_3d.h

some cubic spline-related enhancements and a couple of other minor updates

Vgl updates

---

contrib/brl/bbas/CMakeLists.txt
contrib/brl/bbas/bnabo/CMakeLists.txt
contrib/brl/bbas/bnabo/bnabo.cxx
contrib/brl/bbas/bnabo/bnabo.h
contrib/brl/bbas/bnabo/bnabo_brute_force.cxx
contrib/brl/bbas/bnabo/bnabo_index_heap.h
contrib/brl/bbas/bnabo/bnabo_kdd_tree.cxx
contrib/brl/bbas/bnabo/bnabo_private.h

This PR adds an adapted version of libnabo (https://github.com/ethz-asl/libnabo) at contrib/brl/bbas/bnabo

Add adapted version of nabo K-d tree and K nearest neighbors library

---

config/cmake/Modules/FindClipper.cmake
contrib/CMakeLists.txt
contrib/brl/CMakeLists.txt
contrib/brl/bmods/FindSHAPELIB.cmake
contrib/brl/bseg/boxm2/ocl/CMakeLists.txt
contrib/brl/bseg/sbin/CMakeLists.txt
contrib/mul/CMakeLists.txt
contrib/mul/mbl/CMakeLists.txt
core/vgui/CMakeLists.txt
core/vidl/CMakeLists.txt
core/vil/CMakeLists.txt

These fixes to enable integration with 3rd party projects that include
VXL as a subdirectory.  resolves #250

remove more references to CMAKE_SOURCE_DIR

---

contrib/brl/bbas/bvgl/bvgl_k_nearest_neighbors_3d.h
contrib/brl/bbas/bvgl/tests/test_k_nearest_neighbors.cxx

Add ability to retrieve K nearest indices in bvgl_k_nearest_neighbors_3d + unit test.

Add knn indices retrieval

---

contrib/brl/bseg/boxm2/vecf/boxm2_vecf_estimate_camera_from_canthus.cxx
contrib/brl/bseg/boxm2/vecf/exe/estimate_camera_via_orbit.cxx

Small update for filename cout during error checking. Old code fails during Windows build.

Fixed filename cout

---

contrib/brl/bbas/bocl/bocl_device_info.cxx
contrib/brl/bbas/bocl/bocl_device_info.h
contrib/brl/bbas/bocl/bocl_utils.cxx

Added additional OpenCL reporting to aid in multi-GPU debugging:
--PCI bus & slot numbers for NVIDIA devices
--Error number when OpenCL error is "unknown"

Additional OpenCL reporting

---

contrib/brl/bbas/bocl/bocl_utils.cxx

Remove C++11 dependance for error message.

BUG: C++11 feature used in error message

---

vcl/vcl_deprecated.cxx
vcl/vcl_deprecated.h

Isolate functions so that only the version that
can be used are compiled.

STYLE: Minimize scope of functions

---

core/vidl/vidl_ffmpeg_istream.cxx
core/vidl/vidl_ffmpeg_istream_v0.9.hxx
core/vidl/vidl_ffmpeg_istream_v1.hxx
core/vidl/vidl_ffmpeg_istream_v2.hxx
core/vidl/vidl_ffmpeg_istream_v3.hxx
core/vidl/vidl_ffmpeg_ostream_v0.11.hxx
core/vidl/vidl_ffmpeg_ostream_v0.9.hxx
core/vidl/vidl_ffmpeg_ostream_v1.hxx
core/vidl/vidl_ffmpeg_ostream_v2.hxx
core/vidl/vidl_ffmpeg_ostream_v3.hxx
core/vidl/vidl_ffmpeg_ostream_v4.hxx
core/vidl/vidl_ffmpeg_ostream_v56.hxx

These changes fix the build on Ubuntu 14.04 using the libav system packages

Fix older vidl ffmpeg build

---

contrib/brl/bbas/volm/pro/processes/volm_map_osm_process.cxx
contrib/brl/bpro/core/sdet_pro/processes/sdet_texture_classifier_process2.cxx
contrib/brl/bpro/core/sdet_pro/processes/sdet_texture_classifier_roc_process.cxx
contrib/brl/bpro/core/sdet_pro/sdet_processes.h
contrib/brl/bpro/core/sdet_pro/sdet_register.cxx
contrib/brl/bseg/bvxm/pyscripts/bvxm_sdet_adaptor.py
contrib/brl/bseg/bvxm/pyscripts/bvxm_volm_adaptor.py
contrib/brl/bseg/bvxm/pyscripts/bvxm_vpgl_adaptor.py
contrib/brl/bseg/sdet/sdet_texture_classifier.cxx
contrib/brl/bseg/sdet/sdet_texture_classifier.h

A new method that returns the probability of certain classified category is added into texture classification under brl/bbas/sdet
In addition, some bugs in python processes were fixed.

Add new method into brl/bbas/sdet texture classification

---

contrib/brl/bbas/bnabo/bnabo.h
contrib/brl/bbas/bvgl/bvgl_k_nearest_neighbors_3d.h
contrib/brl/bbas/bvgl/bvgl_knn_index_3d.h

some minor updates to the K nearest neighbors functionality in contrib/brl/bbas/bvgl

bvgl knn updates

---

contrib/brl/bbas/brad/brad_image_metadata.cxx

add support to parse satellite images that have product type "Stereo"

add support to parse Stereo type satellite images

---

core/vidl/vidl_ffmpeg_istream_v56.hxx

Essentially, codec must be checked for validity before calling avcodec_flush_buffers() function. Or empty internal pointer will lead to hard crash.

fixed the crash in seek_frame().

---

core/vil/vil_copy.cxx
core/vil/vil_copy.h
core/vil/vil_math.h

Also creates a vil_math_sum_squares for a masked image.

Create in-memory deep copy function in vil_copy

---

core/vnl/io/vnl_io_diag_matrix.hxx
core/vnl/io/vnl_io_matrix.hxx
core/vnl/io/vnl_io_sparse_matrix.hxx
core/vnl/io/vnl_io_sym_matrix.hxx
core/vnl/io/vnl_io_vector.hxx
core/vnl/vnl_identity_3x3.h
core/vnl/vnl_transpose.h
core/vnl/xio/vnl_xio_matrix.hxx
core/vnl/xio/vnl_xio_quaternion.hxx
core/vnl/xio/vnl_xio_vector.hxx

This branch started with Bill Hoffman's pull request and added a few more instances of TEMPLATE_EXPORT.

Vs2015 link errors

---

vcl/vcl_compiler.h

CC: @dstoup @hjmjohnson @billhoffman @bradking

COMP: Add VCL support for GCC 7

---

core/vgl/CMakeLists.txt
core/vgl/Templates/vgl_affine_coordinates+double-.cxx
core/vgl/Templates/vgl_affine_coordinates+float-.cxx
core/vgl/tests/CMakeLists.txt
core/vgl/tests/test_affine_coordinates.cxx
core/vgl/tests/test_driver.cxx
core/vgl/vgl_affine_coordinates.h
core/vgl/vgl_affine_coordinates.hxx

Added affine coordinate functions to vgl

add new affine coordinate functions

---

contrib/brl/bseg/sdet/sdet_CFTG.h
contrib/brl/bseg/sdet/sdet_EHT.h
contrib/brl/bseg/sdet/sdet_EMD.h
contrib/brl/bseg/sdet/sdet_appearance.h
contrib/brl/bseg/sdet/sdet_curve_fragment_graph.h
contrib/brl/bseg/sdet/sdet_curve_model.h
contrib/brl/bseg/sdet/sdet_curvelet.h
contrib/brl/bseg/sdet/sdet_curvelet_map.h
contrib/brl/bseg/sdet/sdet_detector.h
contrib/brl/bseg/sdet/sdet_edgel.h
contrib/brl/bseg/sdet/sdet_edgel_link_graph.h
contrib/brl/bseg/sdet/sdet_edgemap.cxx
contrib/brl/bseg/sdet/sdet_edgemap.h
contrib/brl/bseg/sdet/sdet_edgemap_sptr.h
contrib/brl/bseg/sdet/sdet_hyp_tree_graph.h
contrib/brl/bseg/sdet/sdet_mrf_site_bp.h
contrib/brl/bseg/sdet/sdet_region.h
contrib/brl/bseg/sdet/sdet_region_edge.h
contrib/brl/bseg/sdet/sdet_sel.h
contrib/brl/bseg/sdet/sdet_sel_base.h
contrib/brl/bseg/sdet/sdet_sel_sptr.h

minor fixes to include paths and remove empty file.

Sdet minor

---

core/vnl/algo/vnl_adaptsimpson_integral.h
core/vnl/algo/vnl_amoeba.h
core/vnl/algo/vnl_bracket_minimum.h
core/vnl/algo/vnl_brent.h
core/vnl/algo/vnl_brent_minimizer.h
core/vnl/algo/vnl_cholesky.h
core/vnl/algo/vnl_conjugate_gradient.h
core/vnl/algo/vnl_convolve.h
core/vnl/algo/vnl_cpoly_roots.h
core/vnl/algo/vnl_determinant.h
core/vnl/algo/vnl_discrete_diff.h
core/vnl/algo/vnl_gaussian_kernel_1d.h
core/vnl/algo/vnl_generalized_eigensystem.h
core/vnl/algo/vnl_lbfgs.h
core/vnl/algo/vnl_lbfgsb.h
core/vnl/algo/vnl_ldl_cholesky.h
core/vnl/algo/vnl_powell.h
core/vnl/algo/vnl_rnpoly_solve.h
core/vnl/algo/vnl_rpoly_roots.h
core/vnl/algo/vnl_simpson_integral.h
core/vnl/algo/vnl_solve_qp.h
core/vnl/algo/vnl_sparse_lu.h
core/vnl/algo/vnl_sparse_symmetric_eigensystem.h

Export more vnl_algo symbols. What is in this branch fixes most of the failing dashboards, but there is still one link error that I can't figure out yet.

Add exported symbols to vnl_algo

---

core/vnl/algo/vnl_complex_generalized_schur.h
core/vnl/algo/vnl_generalized_schur.h

Add missing set of exports needed when compilng
with shared libraries for vnl_algo.

COMP: Adding exports for vnl_algo

---

CMakeLists.txt

minor: repeated policy settings
resolves #355

COMP: Remove duplicate cmake policy

---

config/cmake/Modules/VXLGenerateExportHeader.cmake

Review and update bug fixes from the cmake 3.10.2 upstream version
of the file cmake/Modules/GenerateExportHeader.cmake.

COMP: Synchronize bug fixes from cmake/Modules/GenerateExportHeader.cmake

---

contrib/brl/bseg/bstm_multi/basic/CMakeLists.txt
contrib/brl/bseg/bstm_multi/io/CMakeLists.txt

Fixes the recent configure errors with targets that don't contain cxx files

Set linker language

---

core/vgl/io/tests/test_point_2d_io.cxx
core/vgl/vgl_point_2d.hxx

I verified the test breaks with the commit prior to my fix and that this test resolves the issue.

Provide a test for the bug reading vgl_point_2d

---

vcl/vcl_compiler.h

It just adds a if/else branch to the existing logic.
Triggered here: https://discourse.itk.org/t/building-and-compiling-with-gcc-8-1/934/4

COMP: Add gcc8 support to vcl_compiler.

---

core/vil/CMakeLists.txt
core/vil/file_formats/vil_sgi.cxx
core/vil/file_formats/vil_sgi.h
core/vil/file_formats/vil_sgi_file_header.cxx
core/vil/file_formats/vil_sgi_file_header.h
core/vil/vil_config.h.in
core/vil/vil_file_format.cxx
core/vil/vil_save.cxx

File format specifications here: ftp://ftp.sgi.com/graphics/grafica/sgiimage.html
For now, this only includes uncompressed files.

Add sgi file format

---

core/vgl/vgl_plane_3d.h
core/vgl/vgl_plane_3d.hxx

Normalization option for vgl_plane_3d coefficients.  Authored by @mundyj.

vgl_plane_3d normalization

---

core/vnl/vnl_diag_matrix_fixed.h

@hjmjohnson @dstoup Please review / merge.

COMP: Avoid unused parameter warning in vnl_diag_matrix_fixed

---

core/vpgl/algo/tests/test_camera_convert.cxx
core/vpgl/algo/vpgl_camera_convert.cxx
core/vpgl/algo/vpgl_camera_convert.h

add conversion from ```vpgl_local_rational_camera``` to ```vpgl_affine camera```, plus test.

local_rational to affine camera conversion

---

config/cmake/Modules/VXLStandardOptions.cmake
core/doc/book/appendix_build.texi
core/vil/CMakeLists.txt
core/vil/vil_stream_url.cxx
core/vil1/CMakeLists.txt
core/vil1/vil1_stream_url.cxx
core/vul/CMakeLists.txt
core/vul/vul_url.cxx

This continues the process started earlier.

Remove solaris and alpha support

---

contrib/brl/bbas/bpgl/algo/CMakeLists.txt
contrib/brl/bbas/bpgl/algo/bpgl_gridding.h
contrib/brl/bbas/bpgl/algo/tests/CMakeLists.txt
contrib/brl/bbas/bpgl/algo/tests/test_driver.cxx
contrib/brl/bbas/bpgl/algo/tests/test_gridding.cxx
contrib/brl/bbas/bvgl/CMakeLists.txt
contrib/brl/bbas/bvgl/bvgl_k_nearest_neighbors_2d.h
contrib/brl/bbas/bvgl/tests/test_k_nearest_neighbors.cxx

Add a "gridding" algorithm to bpgl for transforming irregular data to a regular grid format.

Add bpgl gridding

---

CMakeLists.txt

This version provides a completly green dashboard build
as a baseline for future development.

ENH: Update to version 2.0.2.0

---

contrib/brl/bbas/baio/baio_unix.cxx
contrib/brl/bbas/baio/baio_windows.cxx

@hjmjohnson This fixes some header/implementation mismatches in what appears to be some files left behind by the recent code cleanup.

match baio header/impl declaration mismatches

---

core/vil/algo/CMakeLists.txt
core/vil/algo/Templates/vil_2nd_deriv_3x3+byte.double-.cxx
core/vil/algo/Templates/vil_2nd_deriv_3x3+byte.float-.cxx
core/vil/algo/Templates/vil_2nd_deriv_3x3+double.double-.cxx
core/vil/algo/Templates/vil_2nd_deriv_3x3+float.double-.cxx
core/vil/algo/Templates/vil_2nd_deriv_3x3+float.float-.cxx
core/vil/algo/Templates/vil_2nd_deriv_3x3+uint_16.double-.cxx
core/vil/algo/Templates/vil_2nd_deriv_3x3+uint_16.float-.cxx
core/vil/algo/tests/CMakeLists.txt
core/vil/algo/tests/test_algo_2nd_deriv_3x3.cxx
core/vil/algo/tests/test_driver.cxx
core/vil/algo/vil_2nd_deriv_3x3.h
core/vil/algo/vil_2nd_deriv_3x3.hxx

2nd derivative operator for vil.  From @mundyj

Add 2nd derivative operator to vil

---

contrib/gel/gevd/gevd_bufferxy.cxx
contrib/gel/gevd/tests/test_gevd_bufferxy.cxx

support non-contiguous images in gevd_bufferxy

gevd_bufferxy non-contiguous images

---

core/vgl/algo/Templates/vgl_hough_index_2d+double-.cxx
core/vgl/algo/Templates/vgl_hough_index_2d+float-.cxx
core/vgl/algo/tests/CMakeLists.txt
core/vgl/algo/tests/test_driver.cxx
core/vgl/algo/tests/test_hough_index_2d.cxx
core/vgl/algo/vgl_hough_index_2d.h
core/vgl/algo/vgl_hough_index_2d.hxx
core/vgl/vgl_line_segment_2d.h
core/vgl/vgl_line_segment_2d.hxx

Addition to vgl/algo from @mundyj - Hough transform for fast queries on line sets.  Also includes new mid_point function for vgl_line_segment_2d.h

Hough transform for vgl/algo

---

config/cmake/Modules/NewCMake/FindWin32SDK.cmake

FindWin32SDK for VS2017

---

core/vgl/algo/tests/test_intersection.cxx
core/vgl/algo/vgl_intersection.h
core/vgl/algo/vgl_intersection.hxx
core/vgl/vgl_bounding_box.h
core/vgl/vgl_bounding_box.hxx
core/vgl/vgl_cubic_spline_2d.h
core/vgl/vgl_cubic_spline_3d.h
core/vgl/vgl_intersection.h
core/vgl/vgl_intersection.hxx
core/vgl/vgl_point_2d.h
core/vgl/vgl_point_3d.h
core/vgl/vgl_pointset_3d.h
core/vgl/vgl_polygon.h
core/vgl/vgl_polygon.hxx
core/vgl/vgl_vector_2d.h
core/vgl/vgl_vector_3d.h

New VGL functionality, including:
- casting constructors (e.g., cast vgl_point_2d of type float into type double)
- vgl_intersection (both in vgl and vgl/algo)
- 2D bounding box for vgl_polygon
- small initialization fix for cubic splines
- comment update for clarity

new vgl functionality

---

core/vpgl/algo/vpgl_camera_convert.cxx
core/vpgl/vpgl_affine_camera.h
core/vpgl/vpgl_affine_camera.hxx

New VPGL functionality:
- vpgl_affine_camera - affine camera operators (canonical, pre/post multiply)
- vpgl_camera_convert - static_cast input to unsigned

vpgl: affine, convert

---

core/vpgl/algo/tests/test_fit_rational_cubic.cxx
core/vpgl/algo/vpgl_fit_rational_cubic.cxx
core/vpgl/algo/vpgl_fit_rational_cubic.h

vpgl_fit_rational_cubic update
- additional comments & code cleanup (including test)
- cleanup #include statements

vpgl_fit_rational_cubic update

---

vcl/CMakeLists.txt

Problem identified and contributed by @dzenanz from ITK upstream.

BUG: an absolute path is specified for VCL_COMPILER_DETECTION_HEADER

---

vcl/CMakeLists.txt

Follow up to #601. Closes InsightSoftwareConsortium/ITK#545.

BUG: fixing absolute path which slips into install location

---

core/vpgl/CMakeLists.txt
core/vpgl/Templates/vpgl_radial_tangential_distortion+double-.cxx
core/vpgl/Templates/vpgl_radial_tangential_distortion+float-.cxx
core/vpgl/algo/tests/test_lens_warp_mapper.cxx
core/vpgl/algo/vpgl_lens_warp_mapper.h
core/vpgl/tests/CMakeLists.txt
core/vpgl/tests/test_driver.cxx
core/vpgl/tests/test_rad_tan_distortion.cxx
core/vpgl/vpgl_lens_distortion.h
core/vpgl/vpgl_lens_distortion.hxx
core/vpgl/vpgl_radial_tangential_distortion.h
core/vpgl/vpgl_radial_tangential_distortion.hxx

vpgl_lens_distortion and related functions
-- Added radial and tangential lens distortion and warping
-- Added distort_pixel, undistort_pixel
-- make vpgl_lens_distortion::undistort purely virtual (previously unimplemented)

vpgl_lens_distortion and related functions

---

contrib/brl/bpro/core/bbas_pro/processes/bpgl_heightmap_from_disparity_process.cxx
contrib/brl/bpro/core/bvgl_pro/processes/bvgl_geo_index_region_resource_process.cxx
contrib/brl/bpro/core/pyscripts/bsgm_adaptor.py
contrib/brl/bpro/core/pyscripts/bvgl_adaptor.py
contrib/brl/bpro/core/pyscripts/vpgl_adaptor.py
contrib/brl/bpro/core/vpgl_pro/processes/vpgl_correct_rational_camera_process.cxx
contrib/brl/bseg/bsgm/pro/processes/bsgm_matching_stereo_process.cxx
core/vil/file_formats/vil_geotiff_header.cxx
core/vpgl/file_formats/vpgl_geo_camera.cxx

CORE:
- remove print statements from vil_geotiff_header & vpgl_geo_camera (user may print information elsewhere if needed for debugging)
CONTRIB BRL adaptors:
- user-defined verbosity for various adaptor processes
- catch error in bpgl_heightmap_from_disparity_process
- return region list directly in bvgl_geo_index_region_resource_process

verbosity & contrib adaptors

---

core/vil/file_formats/vil_sgi.cxx
core/vil/file_formats/vil_tiff.cxx
core/vpgl/vpgl_generic_camera.hxx
core/vpgl/vpgl_tri_focal_tensor.hxx
core/vul/vul_debug.cxx

cleanly rebased version of #619 from @clucock1 - I managed to mess up the conflict resolution of the previous one in the github interface.

Cyndie vxl fix warnings

---

contrib/brl/bbas/bpgl/algo/bpgl_3d_from_disparity.hxx
contrib/brl/bbas/bpgl/algo/bpgl_heightmap_from_disparity.hxx
contrib/brl/bbas/brad/app/brad_ms_app.cxx
contrib/brl/bbas/brad/app/brad_ms_app_rgb.cxx
contrib/brl/bbas/brad/brad_image_atmospherics_est.cxx
contrib/brl/bbas/brad/brad_multispectral_functions.cxx
contrib/brl/bbas/brad/brad_sam_template_match.cxx
contrib/brl/bbas/brad/brad_spectral_angle_mapper.cxx
contrib/brl/bbas/bwm/exe/bwm_3d_fixed_transform.cxx
contrib/brl/bbas/bwm/exe/bwm_compute_orientation_variance.cxx
contrib/brl/bpro/core/bbas_pro/processes/bpgl_heightmap_from_disparity_process.cxx
contrib/brl/bseg/baml/baml_detect_change.h
contrib/brl/bseg/baml/baml_utilities.cxx
contrib/brl/bseg/betr/betr_pixelwise_change_detection.cxx
contrib/brl/bseg/boxm2/cpp/algo/boxm2_refine_block_function_with_labels.cxx
contrib/brl/bseg/boxm2/cpp/pro/processes/boxm2_cpp_get_index_from_3d_point.cxx
contrib/brl/bseg/boxm2/pro/processes/boxm2_load_scene_process.cxx
contrib/brl/bseg/boxm2/vecf/boxm2_vecf_lid_base.cxx
contrib/brl/bseg/boxm2/vecf/boxm2_vecf_orbit_scene.cxx
contrib/brl/bseg/boxm2/vecf/boxm2_vecf_plot_orbit.cxx
contrib/brl/bseg/boxm2/volm/exe/boxm2_volumetric_post_process_p1_integration.cxx
contrib/brl/bseg/brip/app/brip_find_blob_app.cxx
contrib/brl/bseg/brip/brip_ms_blob_detection.cxx
contrib/brl/bseg/bstm/cpp/algo/bstm_refine_blk_in_time_function.hxx
contrib/brl/bseg/bstm/cpp/pro/processes/bstm_cpp_extract_point_cloud_process.cxx
contrib/brl/bseg/bstm_multi/bstm_multi_block.cxx
contrib/brl/bseg/bstm_multi/bstm_multi_tree_util.cxx
contrib/brl/bseg/bstm_multi/tests/test_bstm_multi_tree_util.cxx
contrib/brl/bseg/bvxm/pro/processes/bvxm_dem_to_xyz_process.cxx

Corrected most warnings in contrib brl.
Changed tabs to spaces in contrib brl.

Contrib brl fix warnings

---

contrib/brl/bbas/bpgl/algo/bpgl_heightmap_from_disparity.hxx
contrib/brl/bbas/bpgl/icam/icam_cylinder_map.cxx
contrib/brl/bbas/bpgl/icam/icam_spherical_map.cxx
contrib/brl/bpro/core/vil_pro/processes/vil_binarize_otsu_process.cxx
contrib/brl/bpro/core/vil_pro/processes/vil_image_mean_and_variance_process.cxx
contrib/brl/bpro/core/vpgl_pro/processes/vpgl_find_connected_component_process.cxx
contrib/brl/bpro/core/vpgl_pro/processes/vpgl_isfm_rational_camera_process.cxx
contrib/brl/bpro/core/vpgl_pro/processes/vpgl_isfm_rational_camera_with_initial_process.cxx
contrib/brl/bpro/core/vpgl_pro/processes/vpgl_rectify_images_process.cxx
contrib/brl/bseg/bstm_multi/tests/test_bstm_multi_tree_util.cxx
contrib/brl/bseg/vcon/pro/processes/vcon_calculate_trafficability_process.cxx

Fixed remaining C4018 and C4101 warnings in contrib/brl:
bpgl_algo
bstm_multi\tests
icam
vcon_pro
vil_pro
bpgl_pro

fixed warnings: icam, vcon_pro, vil_pro, vpgl_pro

---

contrib/brl/bbas/bpgl/CMakeLists.txt
contrib/brl/bbas/bpgl/acal/CMakeLists.txt
contrib/brl/bbas/bpgl/acal/acal_f_utils.cxx
contrib/brl/bbas/bpgl/acal/acal_f_utils.h
contrib/brl/bbas/bpgl/acal/acal_match_graph.cxx
contrib/brl/bbas/bpgl/acal/acal_match_graph.h
contrib/brl/bbas/bpgl/acal/acal_match_tree.cxx
contrib/brl/bbas/bpgl/acal/acal_match_tree.h
contrib/brl/bbas/bpgl/acal/acal_match_tree_solver.cxx
contrib/brl/bbas/bpgl/acal/acal_match_tree_solver.h
contrib/brl/bbas/bpgl/acal/acal_match_utils.cxx
contrib/brl/bbas/bpgl/acal/acal_match_utils.h
contrib/brl/bbas/bpgl/acal/acal_metadata.h
contrib/brl/bbas/bpgl/acal/acal_planar_feature_matcher.cxx
contrib/brl/bbas/bpgl/acal/acal_planar_feature_matcher.h
contrib/brl/bbas/bpgl/acal/acal_tile_data_manager.cxx
contrib/brl/bbas/bpgl/acal/acal_tile_data_manager.h
contrib/brl/bbas/bpgl/acal/tests/CMakeLists.txt
contrib/brl/bbas/bpgl/acal/tests/test_driver.cxx
contrib/brl/bbas/bpgl/acal/tests/test_f_utils.cxx
contrib/brl/bbas/bpgl/acal/tests/test_match_tree.cxx
contrib/brl/bbas/bpgl/acal/tests/test_match_utils.cxx
contrib/brl/bbas/bpgl/acal/tests/test_metadata.cxx

New BRL submodule to perform calibration of multiple affine cameras (typically derived from rational cameras), developed by @mundyj.

CONTRIB BRL: affine camera calibration

---

core/vgl/vgl_pointset_3d.h

vgl_pointset_3d.clear() must also clear scalars

vgl_pointset_3d.clear()

---

CMakeLists.txt

First attempt at fixing #624 
With this, the libraries now look like this:
```
$ ls
libclipper.so
libclipper.so.2.0
libclipper.so.2.0.2
libnetlib.so
libnetlib.so.2.0
libnetlib.so.2.0.2
libopenjpeg2.so
libopenjpeg2.so.2.0
libopenjpeg2.so.2.0.0
librply.so
librply.so.2.0
librply.so.2.0.2
libs.txt
libtestlib.so
libtestlib.so.2.0
libtestlib.so.2.0.2
libv3p_netlib.so
libv3p_netlib.so.2.0
libv3p_netlib.so.2.0.2
libvbl_io.so
libvbl_io.so.2.0
libvbl_io.so.2.0.2
libvbl.so
libvbl.so.2.0
libvbl.so.2.0.2
libvcl.so
libvcl.so.2.0
libvcl.so.2.0.2
libvcsl.so
libvcsl.so.2.0
libvcsl.so.2.0.2
libvgl_algo.so
libvgl_algo.so.2.0
libvgl_algo.so.2.0.2
libvgl_io.so
libvgl_io.so.2.0
libvgl_io.so.2.0.2
libvgl.so
libvgl.so.2.0
libvgl.so.2.0.2
libvgl_xio.so
libvgl_xio.so.2.0
libvgl_xio.so.2.0.2
libvil1.so …
```

Version shared objects

---

contrib/brl/bpro/core/pyscripts/bsgm_adaptor.py
contrib/brl/bseg/bsgm/CMakeLists.txt
contrib/brl/bseg/bsgm/app/bsgm_app.cxx
contrib/brl/bseg/bsgm/bsgm_disparity_estimator.cxx
contrib/brl/bseg/bsgm/bsgm_disparity_estimator.h
contrib/brl/bseg/bsgm/bsgm_error_checking.cxx
contrib/brl/bseg/bsgm/bsgm_error_checking.h
contrib/brl/bseg/bsgm/bsgm_multiscale_disparity_estimator.cxx
contrib/brl/bseg/bsgm/bsgm_multiscale_disparity_estimator.h
contrib/brl/bseg/bsgm/bsgm_pairwise_dsm.cxx
contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.cxx
contrib/brl/bseg/bsgm/pro/processes/bsgm_matching_stereo_process.cxx

CONTRIB BRL update for bsgm (semi-global matching)
- move error checking to separate file
- new left-right consistency check
- optional directional bias
- additional debugging options & code cleanup

CONTRIB BRL : bsgm update

---

contrib/brl/bbas/bpgl/acal/CMakeLists.txt
contrib/brl/bbas/bpgl/acal/acal_match_graph.cxx
contrib/brl/bbas/bpgl/acal/acal_match_graph.h
contrib/brl/bbas/bpgl/acal/acal_match_tree_solver.cxx
contrib/brl/bbas/bpgl/acal/acal_match_tree_solver.h
contrib/brl/bbas/bpgl/acal/acal_solution_error.h

CONTRIB BRL minor update for acal
-- added all match tree accessor to match_graph
-- made solution error its own class
-- minor code cleanup

CONTRIB BRL: minor acal update

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/coding_style_inconsistency_report.md
.github/ISSUE_TEMPLATE/compiler_support_report.md
.github/ISSUE_TEMPLATE/coverage_impact_report.md
.github/ISSUE_TEMPLATE/data_addition_request.md
.github/ISSUE_TEMPLATE/design_impact_report.md
.github/ISSUE_TEMPLATE/documentation_impact_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/infrastructure_impact_report.md
.github/ISSUE_TEMPLATE/performance_impact_report.md
.github/ISSUE_TEMPLATE/regression_bug_report.md
.github/pull_request_template.md

Provide templates for consistently capturing important information
in issues and PR requests.

ENH: Add templates for github issues & PR requests

---

core/vgui/impl/mfc/vgui_mfc_utils.cxx
core/vgui/impl/win32/vgui_win32_dialog_impl.cxx
core/vgui/impl/win32/vgui_win32_statusbar.cxx
core/vpgl/algo/tests/test_camera_homographies.cxx
core/vpgl/algo/tests/test_equi_rectification.cxx
core/vpgl/vpgl_rational_camera.hxx
core/vpl/os_win32/vpl.cxx

Corrected warnings in vgui, vpgl, and vpl

fixed missed warnings in core

---

contrib/brl/bbas/bwm/bwm_observer_cam.cxx
contrib/brl/bbas/bwm/io/tests/test_site_obj_reader.cxx
contrib/brl/bbas/bwm/process/bwm_process.cxx
contrib/brl/bbas/bwm/video/tests/test_cam_iostream.cxx
contrib/brl/bseg/betr/tests/CMakeLists.txt

* COMP: compiler error or warning fix in bwm and betr

brl: fixed warnings in bwm and betr

---

contrib/brl/bseg/bsgm/bsgm_error_checking.cxx

COMP: Changed isnan to std::isnan.

Fix rounding and test for nan

---

contrib/brl/bseg/boxm2/ocl/algo/boxm2_ocl_update_max_vis.cxx
contrib/brl/bseg/boxm2/ocl/pro/processes/boxm2_ocl_aux_update_view_direction_process.cxx
contrib/brl/bseg/boxm2/ocl/pro/processes/boxm2_ocl_render_expected_depth_process.cxx
contrib/brl/bseg/boxm2/vecf/ocl/boxm2_vecf_ocl_orbit_scene.cxx
contrib/brl/bseg/bstm/ocl/algo/bstm_ocl_change_detection.cxx
contrib/brl/bseg/bstm/ocl/pro/processes/bstm_ocl_render_expected_change_process.cxx

COMP: fixed new warnings C4101: unreferenced local variable in contrib/brl/bseg

brl fixed new unreferenced local variable warnings

---

contrib/brl/bseg/boxm2/ocl/algo/boxm2_ocl_expected_image_renderer.cxx
contrib/brl/bseg/boxm2/ocl/algo/boxm2_ocl_num_obs_renderer.cxx
contrib/brl/bseg/boxm2/ocl/algo/boxm2_ocl_refine_scene_around_geometry.cxx
contrib/brl/bseg/boxm2/ocl/algo/boxm2_ocl_update_heightmap_factor.cxx
contrib/brl/bseg/boxm2/reg/ocl/boxm2_ocl_hierarchical_points_to_volume_reg.cxx
contrib/brl/bseg/boxm2/reg/ocl/boxm2_ocl_hierarchical_reg.cxx
contrib/brl/bseg/boxm2/volm/pro/processes/boxm2_geo_cover_with_osm_to_xyz_process.cxx
contrib/brl/bseg/boxm2_multi/algo/boxm2_multi_pre_vis_inf.cxx
contrib/brl/bseg/boxm2_multi/algo/boxm2_multi_store_aux.cxx
contrib/brl/bseg/boxm2_multi/pro/processes/boxm2_create_multi_cache_process.cxx
contrib/brl/bseg/bstm/ocl/algo/bstm_ocl_annealed_particle_filter.cxx
contrib/brl/bseg/bstm/ocl/algo/bstm_ocl_particle_filter.cxx
contrib/brl/bseg/bvxm_bridge/bvxm_to_boxm2.cxx

COMP: fixed warnings C4018: '<': signed/unsigned mismatch in brl

fixed warnings signed/unsigned mismatch in brl

---

contrib/brl/bbas/bvgl/algo/Templates/bvgl_ptset_3d_ops+double-.cxx
contrib/brl/bbas/bvgl/algo/Templates/bvgl_ptset_3d_ops+float-.cxx
contrib/brl/bbas/bvgl/algo/Templates/bvgl_register_ptsets_3d_rigid+double-.cxx
contrib/brl/bbas/bvgl/algo/bvgl_ptset_3d_ops.h
contrib/brl/bbas/bvgl/algo/bvgl_ptset_3d_ops.hxx
contrib/brl/bbas/bvgl/algo/bvgl_register_ptsets_3d_rigid.h
contrib/brl/bbas/bvgl/algo/bvgl_register_ptsets_3d_rigid.hxx

Adding bvgl class for vgl pointset operations.

ENH: Ptset Ops

---

core/vnl/tests/test_vector.cxx
core/vnl/vnl_vector.h
core/vnl/vnl_vector.hxx

Revert "PERF: Add C++11 move-constructor and move-assignment to vnl_vector"

---

contrib/brl/bseg/bsgm/CMakeLists.txt
contrib/brl/bseg/bsgm/bsgm_remove_spikes.cxx
contrib/brl/bseg/bsgm/bsgm_remove_spikes.h

Add a bsgm_remove_spikes class for removing Z value spikes from DSMs.

ENH: bsgm_remove_spikes

---

contrib/brl/bbas/bpgl/acal/CMakeLists.txt
contrib/brl/bbas/bpgl/acal/acal_intertile_graph_solver.cxx
contrib/brl/bbas/bpgl/acal/acal_intertile_graph_solver.h
contrib/brl/bbas/bpgl/acal/acal_match_graph.cxx
contrib/brl/bbas/bpgl/acal/acal_metadata.h
contrib/brl/bbas/bpgl/acal/tests/test_metadata.cxx

Adding another non-linear optimizer for solving for camera translations between tiles.

ENH: acal_intertile_graph_solver

---

contrib/brl/bbas/bpgl/acal/acal_metadata.h
contrib/brl/bseg/bsgm/bsgm_pair_selector.cxx

Updating pair selection metadata in acal_metadata.

ENH: Update acal_metadata

---

contrib/brl/bbas/bnabo/bnabo_index_heap.h
contrib/brl/bbas/bpgl/acal/acal_metadata.h
contrib/brl/bbas/bpgl/acal/tests/test_match_tree.cxx
contrib/brl/bbas/bvgl/algo/bvgl_register_ptsets_3d_rigid.h
contrib/brl/bseg/betr/betr_pixelwise_change_detection_params.h
contrib/brl/bseg/bvxm/breg3d/breg3d_ekf_camera_optimizer.cxx

fix various compiler errors in contrib (Apple clang version 11.0.0)

COMP: fix various compiler errors in contrib

---

core/vnl/vnl_drand48.cpp

@N-Dekker Update to modernize to c++ style.

Modernize type casting

---

core/vnl/vnl_bignum.h
core/vul/tests/test_debug.cxx
core/vul/vul_string.cxx
v3p/bzlib/bzlib.c

Cleanup several dashboard compiler warnings.

Clang tidy

---

contrib/brl/bbas/bpgl/bpgl_geotif_camera.h
contrib/brl/bbas/bpgl/bpgl_geotif_camera.hxx
contrib/brl/bbas/bpgl/bpgl_lon_lat_camera.h
contrib/brl/bbas/bpgl/bpgl_lon_lat_camera.hxx
contrib/brl/bbas/bpgl/tests/test_geotif_camera.cxx
contrib/brl/bbas/bpgl/tests/test_lon_lat_camera.cxx
contrib/brl/bbas/bvgl/algo/bvgl_register_ptsets_3d_rigid.h
contrib/brl/bbas/bvgl/algo/bvgl_register_ptsets_3d_rigid.hxx
contrib/brl/bseg/bsgm/bsgm_remove_spikes.cxx
contrib/brl/bseg/bsgm/bsgm_remove_spikes.h

-  :no_entry_sign:  Makes breaking changes to the vxl/core/\* API that requires semantic versioning increase
-  :no_entry_sign:  Makes design changes to existing vxl/core\* API that requires semantic versioning increase
-  [X]  Makes changes to the contributed directory API DOES NOT require semantic versioning increase
-  [X] Adds tests and baseline comparison (quantitative).
-   :no_entry_sign: Adds Documentation.

Update bpgl geotif cam

---

core/vpgl/algo/tests/test_equi_rectification.cxx
core/vpgl/algo/vpgl_equi_rectification.cxx
core/vpgl/algo/vpgl_equi_rectification.h

- no_entry_sign: Makes breaking changes to the vxl/core/\* API that requires semantic versioning increase
-  [X]  Adds tests and baseline comparison (quantitative).

improved perspective rectification

---

contrib/brl/bbas/vsph/CMakeLists.txt
contrib/brl/bbas/vsph/tests/CMakeLists.txt
contrib/brl/bbas/vsph/tests/test_driver.cxx
contrib/brl/bbas/vsph/tests/test_spherical_triangle.cxx
contrib/brl/bbas/vsph/vsph_spherical_coord.cxx
contrib/brl/bbas/vsph/vsph_spherical_coord.h
contrib/brl/bbas/vsph/vsph_spherical_triangle.cxx
contrib/brl/bbas/vsph/vsph_spherical_triangle.h
contrib/brl/bbas/vsph/vsph_unit_sphere.cxx
contrib/brl/bbas/vsph/vsph_unit_sphere.h

Vsph extensions

---

contrib/brl/bbas/bpgl/algo/bpgl_3d_from_disparity.h
contrib/brl/bbas/bpgl/algo/bpgl_3d_from_disparity.hxx
contrib/brl/bbas/bpgl/algo/bpgl_heightmap_from_disparity.h
contrib/brl/bbas/bpgl/algo/bpgl_heightmap_from_disparity.hxx
contrib/brl/bbas/bpgl/algo/bpgl_rectify_image_pair.hxx
contrib/brl/bbas/bvgl/algo/bvgl_ptset_3d_ops.hxx
contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.h
contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.hxx

-  [X] or  Makes changes to the contributed directory API DOES NOT require semantic versioning increase

Perspective ambiguity

---

contrib/brl/bbas/brad/brad_calibration.cxx

-  :no_entry_sign: Adds tests and baseline comparison (quantitative).
Stops spam

STYLE: Comment out cout

---

contrib/brl/bbas/brad/CMakeLists.txt
contrib/brl/bbas/brad/brad_calibration.cxx
contrib/brl/bbas/brad/brad_calibration.h
contrib/brl/bbas/brad/brad_image_atmospherics_est.cxx
contrib/brl/bbas/brad/brad_image_atmospherics_est.h
contrib/brl/bbas/brad/brad_multispectral_functions.cxx
contrib/brl/bbas/brad/brad_spectral_angle_mapper.cxx
contrib/brl/bbas/brad/brad_utils.cxx
contrib/brl/bbas/brad/brad_utils.h

contrib/brl refactoring of brad calibration system (`brad_calibration` and `brad_image_atmospherics_est`) to permit output of calibration parameters. 
Additional update reorganizing `CMakeLists.txt` and removing some unnecessary `#include` directives.
- ❌<Makes design changes to existing vxl/core\* API that requires semantic versioning increase
- ❌Adds Documentation.

ENH: contrib/brl brad calibration

---

CMakeLists.txt
contrib/brl/bbas/bpgl/acal/acal_f_utils.cxx
contrib/brl/bbas/bpgl/acal/acal_f_utils.h
contrib/brl/bbas/bpgl/acal/acal_match_tree_solver.cxx
contrib/brl/bbas/bpgl/acal/acal_match_tree_solver.h
core/vgl/algo/tests/test_intersection.cxx
core/vgl/algo/vgl_intersection.h
core/vgl/algo/vgl_intersection.hxx

-   :no_entry_sign: or  Makes changes to the contributed directory API DOES NOT require semantic versioning increase
-  [X] or  Adds tests and baseline comparison (quantitative).

added multiple ray intersection with covariance

---

core/vnl/vnl_diag_matrix.h
core/vnl/vnl_matrix_fixed.h
core/vnl/vnl_matrix_fixed_ref.h
core/vnl/vnl_transpose.h

Copy-n-paste error in diagnostic message.

BUG: Diagnostic message was wrong.

---

contrib/brl/bbas/bpgl/acal/CMakeLists.txt
contrib/brl/bbas/bpgl/acal/acal_f_utils.cxx
contrib/brl/bbas/bpgl/acal/acal_match_tree_solver.cxx
contrib/brl/bbas/bpgl/acal/acal_match_tree_solver.h
contrib/brl/bbas/bpgl/acal/acal_single_track_solver.cxx
contrib/brl/bbas/bpgl/acal/acal_single_track_solver.h
core/vgl/algo/tests/test_intersection.cxx
core/vgl/algo/vgl_intersection.hxx

Tree solve covar

---

contrib/brl/bbas/bpgl/algo/Templates/bpgl_3d_from_disparity+double.proj-.cxx
contrib/brl/bbas/bpgl/algo/Templates/bpgl_3d_from_disparity+float.proj-.cxx
contrib/brl/bbas/bpgl/algo/bpgl_3d_from_disparity.hxx

-  [X]  Makes changes to the contributed directory API DOES NOT require semantic versioning increase

add proj_camera as type for 3d reconstruction

---

contrib/brl/bseg/bsgm/bsgm_census.h
contrib/brl/bseg/bsgm/bsgm_disparity_estimator.cxx
contrib/brl/bseg/bsgm/bsgm_disparity_estimator.h

-  [X]  --> Makes changes to the contributed directory API DOES NOT require semantic versioning increase

moved error checking .h to dispairity estimator .h

---

contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.hxx

-  [X]  --> Makes changes to the contributed directory API DOES NOT require semantic versioning increase

fixed duplicate scale_0 in prob_pairwise

---

contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.hxx

bsgm_prob_pairwise_dsm bug fix - favor `std::is_same` over other methods for template type discovery.  Previous method attempting to compare `std::numeric_limits<PIX_T>::max()` to expected maximum value does not produce the expected result for `PIX_T==unsigned char`.
https://en.cppreference.com/w/cpp/types/is_same
@decrispell 
- ❌  Makes changes to the contributed directory API DOES NOT require semantic versioning increase
- ❌  Adds tests and baseline comparison (quantitative).
- ❌  Adds Documentation.

BUG: contrib/brl std::is_same

---

contrib/brl/bbas/bvgl/Templates/vbl_array_3d+vcl_vector+float--.cxx
contrib/brl/bbas/bvgl/Templates/vbl_array_3d+vcl_vector+vgl_point_3d+float---.cxx
contrib/brl/bbas/bvgl/Templates/vbl_array_3d+vcl_vector+vgl_vector_3d+float---.cxx
contrib/brl/bbas/bvgl/bvgl_grid_index_3d.h
core/vgl/vgl_pointset_3d.h

-  [X] --> Makes changes to the contributed directory API DOES NOT require semantic versioning increase

Extend grid index

---

core/vnl/vnl_vector.h
core/vnl/vnl_vector_fixed.h

DOC: Grammer change in comment

---

contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.h
contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.hxx

-  [X] --> Makes changes to the contributed directory API DOES NOT require semantic versioning increase

Construct xyzp

---

contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.hxx

-  [X]  --> Makes changes to the contributed directory API DOES NOT require semantic versioning increase

removed #if 0 block on code statements

---

CMakeLists.txt
contrib/gel/vsol/vsol_cylinder.h
core/vgl/CMakeLists.txt
core/vgl/Templates/vgl_cylinder+double-.cxx
core/vgl/Templates/vgl_cylinder+float-.cxx
core/vgl/Templates/vgl_cylinder_3d+double-.cxx
core/vgl/Templates/vgl_cylinder_3d+float-.cxx
core/vgl/algo/Templates/vgl_fit_cylinder_3d+double-.cxx
core/vgl/algo/Templates/vgl_fit_cylinder_3d+float-.cxx
core/vgl/algo/tests/CMakeLists.txt
core/vgl/algo/tests/test_driver.cxx
core/vgl/algo/tests/test_fit_cylinder_3d.cxx
core/vgl/algo/vgl_fit_cylinder_3d.h
core/vgl/algo/vgl_fit_cylinder_3d.hxx
core/vgl/io/Templates/vsl_vector_io+vcl_vector+vgl_cylinder+double---.cxx
core/vgl/io/vgl_io_cylinder.h
core/vgl/io/vgl_io_cylinder.hxx
core/vgl/tests/test_closest_point.cxx
core/vgl/tests/test_include.cxx
core/vgl/tests/test_template_include.cxx
core/vgl/vgl_closest_point.h
core/vgl/vgl_closest_point.hxx
core/vgl/vgl_cylinder_3d.h
core/vgl/vgl_cylinder_3d.hxx
core/vgl/vgl_distance.h
core/vgl/vgl_distance.hxx
core/vgl/vgl_fwd.h

-  [X] --> Makes breaking changes to the vxl/core/\* API that requires semantic versioning increase
-  [X]  --> Makes design changes to existing vxl/core\* API that requires semantic versioning increase
-  [X]  --> Adds tests and baseline comparison (quantitative).

Fit cylinder

---

core/vnl/algo/Templates/vnl_fft_base+double.allsizes-.cxx
core/vnl/algo/Templates/vnl_fft_base+float.allsizes-.cxx

COMP: Instantiate vnl_fft_base for 5D data

---

CMakeLists.txt
core/vgl/io/CMakeLists.txt
core/vgl/io/Templates/vgl_io_oriented_box_2d+double-.cxx
core/vgl/io/Templates/vgl_io_oriented_box_2d+float-.cxx
core/vgl/io/tests/CMakeLists.txt
core/vgl/io/tests/test_driver.cxx
core/vgl/io/tests/test_include.cxx
core/vgl/io/tests/test_oriented_box_2d_io.cxx
core/vgl/io/tests/test_template_include.cxx
core/vgl/io/vgl_io_oriented_box_2d.h
core/vgl/io/vgl_io_oriented_box_2d.hxx

Adds VSL support for vgl_oriented_box_2d.

ENH: VSL support for vgl_oriented_box_2d

---

contrib/brl/bbas/bpgl/algo/bpgl_rectify_image_pair.hxx

Prevent size_t subtraction underflow from happening in bpgl_rectify_image_pair::warp_image. This was happening with a window that had minimum bounds near 0, subtracting a non-zero margin.

BUG: bpgl_rectify_image_pair::warp_image

---

contrib/brl/bseg/bsgm/bsgm_disparity_estimator.h
contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.hxx

Remove printing of debug messages to screen by default.

PERF: Remove some bsgm std::cout messages

---

contrib/brl/bbas/bpgl/acal/acal_single_track_solver.cxx

-  [X]  --> Makes changes to the contributed directory API DOES NOT require semantic versioning increase

removed hard fail for large translations

---

CMakeLists.txt
core/vpgl/file_formats/vpgl_geo_camera.cxx

vpgl_geo_camera - bugfix to actually throw errors.  Adjust error messages, and print to stderr.
- ✔️  Makes design changes to existing vxl/core\* API that requires semantic versioning increase

BUG: vpgl_geo_camera throw errors

---

core/vnl/tests/test_math.cxx
core/vnl/tests/test_na.cxx
core/vnl/tests/test_quaternion.cxx
core/vnl/tests/test_rational.cxx
core/vnl/tests/test_rotation_matrix.cxx

Ref https://github.com/InsightSoftwareConsortium/ITK/issues/2651.

COMP: 5 tests had a missing #include <limits>

---

CMakeLists.txt
core/vgl/algo/CMakeLists.txt
core/vgl/algo/Templates/vgl_fit_xy_paraboloid_3d+double-.cxx
core/vgl/algo/Templates/vgl_fit_xy_paraboloid_3d+float-.cxx
core/vgl/algo/tests/CMakeLists.txt
core/vgl/algo/tests/test_fit_quadric_3d.cxx
core/vgl/algo/vgl_fit_xy_paraboloid_3d.h
core/vgl/algo/vgl_fit_xy_paraboloid_3d.hxx

-  [X] --> Makes design changes to existing vxl/core\* API that requires semantic versioning increase
-  [X] --> Adds tests and baseline comparison (quantitative).

implement a z(x,y) paraboloid fitting algorithm

---

contrib/brl/bbas/bvgl/algo/bvgl_register_ptsets_3d_rigid.h
contrib/brl/bbas/bvgl/algo/bvgl_register_ptsets_3d_rigid.hxx

Analytic reg error minimization

---

core/vpgl/file_formats/vpgl_geo_camera.cxx
core/vpgl/file_formats/vpgl_geo_camera.h

- :no_entry_sign: --> Makes changes to the contributed directory API DOES NOT require semantic versioning increase

Geocamera fix 

---

core/vnl/algo/tests/test_determinant.cxx

DOC: Fix typos in test messages

---

contrib/brl/bbas/bpgl/algo/bpgl_gridding.h
contrib/brl/bseg/bsgm/bsgm_error_checking.hxx

take max shadow prob instead of min in gridding

---

core/vpgl/file_formats/CMakeLists.txt
core/vpgl/io/CMakeLists.txt
core/vpgl/io/tests/CMakeLists.txt
core/vpgl/io/tests/test_lvcs_io.cxx
core/vpgl/io/vpgl_io_lvcs.cxx
core/vpgl/tests/CMakeLists.txt
core/vpgl/tests/test_local_rational_camera.cxx
core/vpgl/tests/test_rational_camera.cxx
core/vpgl/vpgl_lvcs.cxx
core/vpgl/vpgl_lvcs.h
core/vpgl/vpgl_rational_camera.hxx

BUG: fix segfault for binary io of `vpgl_lvcs_sptr`, including new tests.  Previous code attempted to `vsl_b_read` to a nullptr which caused a segfault.  New code reads to an new `vpgl_lvcs` on the heap (encapsulated in a `vpgl_lvcs_sptr`), returning either the new object or nullptr depending on the stream condition after read.
STYLE: vpgl cleanup 
- remove redundant includes, tests, and cmake linked libraries
- vpgl_lvcs move save function to cxx file
- vpgl_lvcs & vpgl_io_lvcs formatting and consistent naming
@decrispell 
- ❌  Makes design changes to existing vxl/core\* API that requires semantic versioning increase
- ❌ Makes changes to the contributed directory API DOES NOT require semantic …

BUG/STYLE: vpgl_lvcs_sptr io & vpgl style

---

contrib/brl/bbas/bvgl/bvgl_grid_index_3d.h
contrib/brl/bbas/bvgl/bvgl_k_nearest_neighbors_2d.h

Macro tile merge support

---

contrib/tbl/vipl/vipl_with_vnl_matrix/accessors/vipl_accessors_vnl_vector.h
core/vnl/algo/tests/test_levenberg_marquardt.cxx
core/vnl/vnl_T_n.h
core/vnl/vnl_bignum.cxx
vcl/tests/test_atomic_count.cxx
vcl/tests/test_cstdio.cxx
vcl/tests/test_memory.cxx
vcl/tests/test_sstream.cxx
vcl/tests/test_string.cxx

Make code formatting with macros easier to read, parse, and interpret.

Code macro cleanup

---

.gitignore
core/vnl/algo/vnl_lsqr.cxx
core/vnl/algo/vnl_lsqr.h
core/vnl/vnl_bignum.cxx
core/vnl/vnl_bignum.h
core/vnl/vnl_finite.h
core/vnl/vnl_polynomial.h
v3p/netlib/libf2c/s_cat.c
vcl/tests/test_memory.cxx

Ran scan-build on code subset that is included with ITK.

Scan build fixes

---

contrib/brl/bbas/bvgl/bvgl_grid_index_3d.h

missing vnl include

---

CMakeLists.txt
core/vpgl/algo/tests/test_affine_tensor_transfer.cxx
core/vpgl/vpgl_affine_tri_focal_tensor.h
core/vpgl/vpgl_affine_tri_focal_tensor.hxx
core/vpgl/vpgl_tri_focal_tensor.h

- 
:no_entry_sign: --> Makes changes to the contributed directory API DOES NOT require semantic versioning increase

Trifocal upgrade

---

v3p/netlib/opt/lbfgsb.c

Port the fixs from scipy fortran files
commit cb9ed45d1a25d77204c737a8e1489dfb9606241f
Author: William Hickman <william.hickman@nrg.com>
Date:   Thu Oct 17 23:49:37 2019
BUG: prevent bound violation in L-BFGS-B optimize method
commit 4eb242fabeef7d1871d21936bee275be4fda1844
Author: Pauli Virtanen <pav@iki.fi>
Date:   Sun Sep 1 09:43:43 2019
BUG: optimize/lbfgsb: fix nan propagation in projgr
commit 25ddd8c8e94ce2190fe2999e15efcdf740daf14b
Author: Melissa Weber Mendonça <melissawm@gmail.com>
Date:   Sat Jul 13 16:13:24 2019
DOC: Added comment clarifying the call for dcsrch.f in lbfgsb.f
Ran f2c, and then manually propagated changes into lbfgsb.c in this repo.

BUG: Fix bugs identified by scipy project

---

contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.h
contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.hxx

add limit to height-based disparity

---

CMakeLists.txt
core/vpgl/algo/CMakeLists.txt
core/vpgl/algo/tests/CMakeLists.txt
core/vpgl/algo/tests/test_affine_fm_compute.cxx
core/vpgl/algo/tests/test_camera_compute.cxx
core/vpgl/algo/tests/test_driver.cxx
core/vpgl/algo/vpgl_affine_camera_robust_est.cxx
core/vpgl/algo/vpgl_affine_camera_robust_est.h
core/vpgl/algo/vpgl_affine_fm_compute_5_point.cxx
core/vpgl/algo/vpgl_affine_fm_compute_5_point.h
core/vpgl/algo/vpgl_affine_fm_robust_est.cxx
core/vpgl/algo/vpgl_affine_fm_robust_est.h
core/vpgl/algo/vpgl_camera_compute.cxx
core/vpgl/algo/vpgl_camera_compute.h

Robust camera geometry

---

CMakeLists.txt
core/vgl/algo/vgl_intersection.h
core/vgl/algo/vgl_intersection.hxx

added special case two ray intersection

---

contrib/brl/bseg/bvxm/bvxm_edge_util.cxx

round edge pixel location

---

contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.h
contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.hxx

ENH: bsgm_prob_pairwise_dsm add getters for shadow_info
- ✅ Makes changes to the contributed directory API DOES NOT require semantic versioning increase

ENH: contrib bsgm shadow_info getters

---

contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.h

add access to disparity margin

---

core/vpgl/file_formats/vpgl_nitf_RSM_camera.cxx

-  :no_entry_sign: Makes breaking changes to the vxl/core/\* API that requires semantic versioning increase
-  :no_entry_sign: Makes design changes to existing vxl/core\* API that requires semantic versioning increase

COMP: Add missing #include <limits>

---

contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.hxx

pass xyz geo consistency to surface types

---

v3p/netlib/sparse/spSolve.c
v3p/netlib/sparse/spUtils.c

Fix old coding errors that introduce compiler warnings.  These have been around since 2006.

Fix sp solve code

---

README.md

Also remove an outdated sentence.

DOC: Improve README formatting

---

v3p/netlib/linalg/lsmrBase.cxx
v3p/netlib/linalg/lsmrBase.h
v3p/netlib/linalg/lsqrBase.cxx
v3p/netlib/linalg/lsqrBase.h
v3p/netlib/tests/lsmrTest2.cxx
v3p/netlib/tests/lsqrTest1.cxx
v3p/netlib/tests/lsqrTest2.cxx

Porting changes from https://github.com/tvercaut/LSQR-cpp/issues/5 to address #974

BUG: Incorrect stopping criteria in `lsmrBase::TerminationPrintOut`

---

CMakeLists.txt
core/vpgl/file_formats/vpgl_nitf_RSM_camera_extractor.cxx
core/vpgl/file_formats/vpgl_nitf_RSM_camera_extractor.h
core/vpgl/file_formats/vpgl_replacement_sensor_model_tres.cxx
core/vpgl/file_formats/vpgl_replacement_sensor_model_tres.h

Add Replacement Sensor Model RSMECB adjustable parameter TRE

---

CMakeLists.txt
contrib/brl/bbas/bpgl/acal/acal_f_utils.cxx
contrib/brl/bbas/bpgl/acal/acal_f_utils.h
core/vpgl/file_formats/vpgl_nitf_RSM_camera_extractor.cxx
core/vpgl/file_formats/vpgl_nitf_RSM_camera_extractor.h

:no_entry_sign: --> Makes changes to the contributed directory API DOES NOT require semantic versioning increase

Extend rsm metdata

---

core/vpgl/tests/CMakeLists.txt
core/vpgl/tests/test_RSM_camera.cxx
core/vpgl/tests/test_driver.cxx
core/vpgl/tests/test_include.cxx

Add unit tests for `vpgl_region_selector` & `vpgl_polycam` (part of `vpgl_RSM_camera`).
@decrispell 
- ✅  Adds tests and baseline comparison (quantitative).

ENH:  vpgl_region_selector & vpgl_polycam unit tests

---

contrib/brl/bbas/bpgl/algo/CMakeLists.txt
contrib/brl/bbas/bpgl/algo/bpgl_fast_gridding.h
contrib/brl/bbas/bpgl/algo/bpgl_heightmap_from_disparity.h
contrib/brl/bbas/bpgl/algo/bpgl_heightmap_from_disparity.hxx
contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.h
contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.hxx

Speedup heightmap
