- v3p/netlib/libf2c/f2ch.add
The s_copy function returns an integer, but the function prototype signature
specified void as the return type. When compiling with the intel compiler and
-ipo flag, undefined symbols were encountered.
> Incorrect function signature in f2ch.add

- contrib/brl/bseg/boxm2/vecf/boxm2_vecf_eye_scene.cxx
- contrib/brl/bseg/boxm2/vecf/tests/CMakeLists.txt
The TARGET_LINK_LIBRARIES was placed inside
a conditional for dependance on OPENCL.  That
seems like an incorrect dependancy because
the code builds without OPENCL and all test pass.
> COMP: Fix compilation linkage issue

- core/vnl/vnl_na.cxx
The istream interface explicitly states[1] the putback (& unget, and
all other methods that write to the stream) :
"... may either fail, be ignored, or overwrite the character at that position"
^^^^A^^^^^^^^^^^^^
In the case of the clang compiler, it was failing.
A new implementation was created that does not require writing to the
stream.  This new implementation passes all the tests.
[1] http://www.cplusplus.com/reference/istream/istream/putback/
> COMP:  putback is not reliable for istreams

- vcl/vcl_cstdio.h
snprintf is not included in Visual Studio 2012, 2013
> fix compiler error due to missing support of snprintf on VC11

- contrib/brl/b3p/minizip/ioapi.h
- contrib/brl/b3p/minizip/iowin32.h
- contrib/brl/b3p/minizip/zip.h
New versions of zlib switched macros from OF to _Z_OF. This patch checks for the definition of OF and either uses it, else uses _Z_OF if it's defined, or as a fallback, creates a default definition. The third case is probably not needed, however seems like a safer option than letting the build fail.
The *.kitware experimental dashboards include this branch and show it working
> Define OF for minizip, when it isn't already.

- config/cmake/Modules/NewCMake/FindPython.cmake
On a system with python 3.x install, the BRL python calls will fail to
complile. Set the supported version numbers in the FindPython module.
The *.kitware experimental dashboards include this branch and show it working
> Restrict python versions. BRL python calls are not 3.x compliant.

- contrib/brl/bseg/bvxm/pro/processes/bvxm_create_scene_xml_process.cxx
For the vcl_err message, we need to use scene_world.str() instead of the
stream itself.
> MSVC doesn't define << operator which takes std::basic_ostream.

- .travis.yml
- .travis/install-deps.sh
I've turned on Travis CI support for VXL, and here is an initial script to get it working.  Because VXL is so large, we may want to consider enabling `ccache` in the future to see if we can speed up builds.
> Add Travis CI

- contrib/brl/bbas/bsta/bsta_joint_histogram_3d.txx
There seems to be a lazy-computed value being used prematurely.  This fixes the "bsta_histogram_io" test failure on my machine.
> compute volume if the value is not valid

- contrib/brl/bbas/bvgl/algo/CMakeLists.txt
Fixed what seems to be a bug in the brl/bbas/bvgl/algo  CMakeLists.txt, which was preventing an auxiliary file from being copied to the library directory.  This in turn caused the "sdet_test_sel" test to crash.
The crash is fixed, but now there are some failing tests that were not previously running.
> test variable, not evaluated variable in CMakeLists.txt

- core/vgl/Templates/vgl_plane_3d+int-.cxx
This instantiation is still needed to avoid linking errors on some
platforms.  It was previously removed because integer math will give
unexpected results inside the vgl_plane_3d class. Another strategy will
be needed to avoid this.
> vgl_plane_3d instantiation for int

- core/vgl/vgl_plane_3d.txx
This patch fixes the compiler issues on Windows in, what seems like, the most maintenance-free way, but I'm certainly open to a better approach.
> Cast fabs input to double to disambiguate call for VS.

- core/vnl/vnl_sparse_lst_sqr_function.cxx
This should fix the failing test in vpgl_algo_test_ba_fixed_k_lsqr
which runs the vnl_sparse_lst_sqr_function with zero parameters in
the shared C parameter block.
> Avoid triggering an assert by returning early for zero params.

- contrib/brl/bseg/boxm/util/tests/test_boxm_plane_ransac.cxx
- core/vgl/algo/vgl_intersection.txx
- core/vgl/tests/test_infinite_line_3d.cxx
This PR contains some new tests for the vgl_infinite_line_3d class, a bugfix vgl_intersection.txx, and a bugfix in test_boxm_plane_ransac that fixes sporadic failures of that test.
The basic problem is that the unique "uv" basis vectors computed by vgl_infinite_line_3d become ill-defined as the direction of the line approaches +x.  A previous PR (now closed) only moved the singularity to a new direction.  Rather than test the 2D point x0_, which is a function of the uv basis vectors, test the 3D point closest to the origin, which is always well-defined.  x0_ should probably be removed from the public interface of vgl_infinite_line_3d in the future for this reason.
> Fix boxm plane ransac test

- contrib/brl/bbas/bkml/bkml_write.h
- contrib/brl/bbas/volm/pro/processes/volm_correct_rational_cameras_ransac_process.cxx
- contrib/brl/bbas/volm/tests/CMakeLists.txt
- contrib/brl/bbas/volm/tests/test_find_overlapping.cxx
- contrib/brl/bseg/boxm2/volm/tests/test_volm_matcher_p1.cxx
- contrib/brl/bseg/bvxm/pro/tests/test_bvxm_rpc_registration_process.cxx
This patch fixes three test case failures due to incorrect input file IO, etc., and compile warning due to reused loop index.  The pitch was verified under windows VS12 and CentOS6.6 GCC4.4.7
> repair test failures

- core/vil/io/CMakeLists.txt
- core/vnl/io/CMakeLists.txt
When CMAKE_CXX_STANDARD is set to 11, we have issues with the current template-depth values set for 2 files. Increasing the depth to 50 fixes the compiler errors.
> Increase default template-depth.

- core/vgl/tests/test_cartesian.cxx
Temporarily remove failing tests so that other refactorings can be more confidently and easily completed.
There are issues on github to record that these tests eventually need to be turned back on and fixed.  
The fixing of these tests will require recruitment of developers who actively use and hopefully know the what the code is supposed to do.
> Temp remove failing tests

- contrib/oxl/CMakeLists.txt
fix the cmake configure error due to first wave deprecation removal cleanup.
> fix cmake configure error due to folder removal

- core/vnl/tests/test_math.cxx
- core/vnl/vnl_math.h
The % operator and the library function fmod implement
the remainder operation such that the result has the same
sign as the dividend.  While this is a valid mathematical
interpretation, it is also common for the mathematical modulus
to be defined such that the result takes the sign of the divisor.
This second definition is implemented in some other languages,
such as Python.  Still others, such as Haskell, provide separate
functions for these two definitions.
This patch provides two functions, vnl_math_remainder_truncated
and vnl_math_remainder_floored, for these two definitions,
respectively.  Moreover, they are overloaded to provide a
consistent interface for integer and floating point arguments.
Unit tests have been provided.
NOTE:  The following unit tests failed on my system (Ubuntu …
> ENH: Add Floored and Truncated Modulus to VNL

- v3p/netlib/triangle.README
- v3p/netlib/triangle.c
- v3p/netlib/triangle.h
Please note that although Triangle is freely available, it is
copyrighted by the author and may not be sold or included in commercial
products without a license.
Updated from version 1.3 (circa 1996) to version 1.6 (circa 2006)
version of Triangle.
https://www.cs.cmu.edu/~quake/triangle.html
New features in Version 1.6 (released July 28, 2005). Improved handling
of domains with small angles (thanks to an algorithm of Gary Miller,
Steven Pav, and Noel Walkington). In particular, Triangle now offers a
no-large-angle guarantee even for domains that have lots of tiny input
angles (which make a no-small-angle guarantee impossible). Meshes
sometimes have fewer triangles than in previous versions, thanks to two
changes. First, Triangle now uses Paul Chew's Delaunay refinement
algorithm, which is …
> ENH: Update triangle.c code from v. 1.3 to v. 1.6

- core/vnl/tests/test_numeric_traits.cxx
- core/vnl/tests/test_pow_log.cxx
- Fixed the runtime crash of vnl_test_numeric_traits
- Fixed the runtime crash of test_pow_log on OSX 10.6
> BUG: Fixed the runtime crash of test code on OSX 10.6

- contrib/brl/bbas/bocl/bocl_device_info.cxx
- contrib/brl/bbas/bocl/bocl_device_info.h
- contrib/brl/bseg/bvxm/tests/test_voxel_world_mog_image.cxx
Previous allocated storage for OpenCL device extension query was not sufficient to support long device extensions on Mac.  This patch should be able to fix or at least remove pop-up errors in some test cases in contrib/brl/bocl/tests/
> fix bug due to OpenCL device extension query failure

- core/vnl/tests/test_matrix.cxx
- core/vnl/vnl_matrix.h
- core/vnl/vnl_matrix.txx
Two methods are added: flatten_row_major(), and flatten_column_major().  This provides functionality similar to other numeric libraries, such as numpy's [flatten()](http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.matrix.flatten.html#numpy.matrix.flatten).
Unit tests are provided.
> ENH: Add methods to flatten vnl_matrix.

- contrib/brl/bbas/bvgl/algo/tests/test_biarc.cxx
- contrib/brl/bbas/bvgl/algo/tests/test_eulerspiral.cxx
- contrib/brl/bbas/volm/desc/volm_desc_matcher.cxx
vxl/contrib/brl/bbas/bvgl/algo/tests/test_biarc.cxx:18:32: warning: comparison of address of 'biarc1' not equal to a null pointer
is always true [-Wtautological-pointer-compare]
TEST("Default Constructor", &biarc1 != 0, true);
^~~~~~    ~
vxl/contrib/brl/bbas/bvgl/algo/tests/test_eulerspiral.cxx:29:32: warning: comparison of address of 'es1' not equal to a null
pointer is always true [-Wtautological-pointer-compare]
TEST("Default Constructor", &es1 != 0, true);
^~~    ~
Prefer vnl_math::abs
vxl/contrib/brl/bbas/volm/desc/volm_desc_matcher.cxx:133:21: warning: using integer absolute value function 'abs' when argument
is of floating point type [-Wabsolute-value]
double x_dist = abs(gt_loc.x()-gt_closest.x())*sec_to_meter;
^
vxl/contrib/brl/bbas/volm/desc/volm_desc_matcher.cxx:133:21: note: …
> COMP: Remove compiler warnings

- v3p/netlib/triangle.c
- v3p/netlib/triangle.h
vxl/contrib/gel/gtrl/gtrl_triangulation.cxx:74:16: warning: conversion from string literal to 'char *' is deprecated
[-Wc++11-compat-deprecated-writable-strings]
triangulate( "-z -i -q", &in, &out, 0);
^
1 warning generated.
> COMP: Remove compiler warning about string literal

- core/vnl/tests/test_matrix.cxx
- core/vnl/tests/test_matrix_fixed.cxx
- core/vnl/vnl_matrix.txx
- core/vnl/vnl_matrix_fixed.h
- core/vnl/vnl_matrix_fixed.txx
Unit tests are provided.  The `vnl_matrix` implementation is also cleaned slightly (should have fewer cache misses).
> ENH: Add methods to flatten vnl_matrix_fixed

- core/vnl/tests/test_vector.cxx
- core/vnl/vnl_vector.h
- core/vnl/vnl_vector.txx
The following methods have been added to vnl_vector:
`roll(const int &shift)`
`roll_inplace(const int &shift)`
`flip(const unsigned int &b, const unsigned int &e)`
`roll()` and` roll_inplace()` mimick `roll` in python's numpy.
Bounded `flip(b,e)` reverses the specified portion of the vector.
This is used in the implementation of `roll_inplace`, but is also
a useful function in and of itself.
> ENH: Add three methods to vnl_vector

- CTestConfig.cmake
CDash has moved to open.cdash.org.
> Update CDash upload site location in CTestConfig.cmake.

- core/vnl/tests/CMakeLists.txt
- core/vnl/tests/test_complexify.cxx
- core/vnl/tests/test_driver.cxx
- core/vnl/vnl_complex_ops.txx
- core/vnl/vnl_complexify.h
- core/vnl/vnl_diag_matrix_fixed.h
This patch overloads `vnl_complexify` for the following containers:
-- `vnl_vector_fixed`
-- `vnl_matrix_fixed`
-- `vnl_diag_matrix`
-- `vnl_diag_matrix_fixed`
-- `vnl_sym_matrix`
A new unit test, `test_complexify`, is added.
Finally, a bug in one of the `vnl_diag_matrix_fixed` constructors is fixed.
> ENH: Overload vnl_complexify for additional containers.

- core/vxl_config.h.in
- vcl/vcl_config_compiler.h.in
@thewtex This makes ITK and VXL consistent so taht these changes persist after
the next VXL upstream merge.
> Improve cxx11 for external use

- contrib/brl/bbas/bocl/bocl_cl.h
- contrib/brl/bbas/bocl/bocl_cl_gl.h
- vcl/gcc/vcl_cmath.h
- vcl/vcl_cerrno.h
The "linux" preprocessor definition is nonconforming and is suppressed
by gcc when supplied with flags such as "-std=X" and "-pedantic".
The double underscore equivalent is supported at least as far back as
gcc v3.1.1.
see:
https://gcc.gnu.org/onlinedocs/gcc-3.1.1/cpp/System-specific-Predefined-Macros.html#System-specific%20Predefined%20Macros
http://sourceforge.net/p/predef/wiki/OperatingSystems/
> replace checks for "linux" preprocessor definition with "__linux__"

- core/vnl/Templates/vnl_sym_matrix+vcl_complex_double--.cxx
- core/vnl/Templates/vnl_sym_matrix+vcl_complex_float--.cxx
- core/vnl/tests/test_complexify.cxx
- core/vnl/vnl_complex_ops.txx
- core/vnl/vnl_complexify.h
@yanggehua brought up a linker error that he was experiencing [1], having to do with template instantiation.  I wasn't able to reproduce this error, but I was able to reproduce a similar one (see the commented out unit test, which complains about undefined reference to `operator=`).  I think this may have to do with the fact that `VNL_SYM_MATRIX_INSTANTIATE` [2] does not instantiate it, but I wasn't able to figure out the syntax for adding it.
@thewtex @hjmjohnson I'm not very familiar with vxl's system for instantiating templates--any guidance is appreciated!
[1] https://github.com/vxl/vxl/issues/107
[2] https://github.com/vxl/vxl/blob/master/core/vnl/vnl_sym_matrix.txx
> WIP: Overload vnl_complexify for additional containers.

- core/vidl/CMakeLists.txt
Used elsewhere and must be installed
> Install vidl_exports.h

- contrib/brl/bbas/bkml/bkml_parser.cxx
- contrib/brl/bbas/bkml/bkml_write.cxx
- contrib/brl/bbas/bpgl/depth_map/depth_map_region.cxx
- contrib/brl/bbas/bpgl/icam/icam_cylinder_map.cxx
- contrib/brl/bbas/brad/brad_image_metadata.h
- contrib/brl/bbas/bsta/algo/bsta_display_vrml.h
- contrib/brl/bbas/bsta/bsta_k_means.txx
- contrib/brl/bbas/bvgl/algo/bvgl_2d_geo_index.cxx
- contrib/brl/bbas/bvgl/bvgl_gen_cylinder.cxx
- contrib/brl/bbas/bvgl/bvgl_grid_index_3d.h
- contrib/brl/bbas/bvgl/bvgl_intersection.txx
- contrib/brl/bbas/volm/tests/test_find_overlapping.cxx
- contrib/brl/bpro/core/vpgl_pro/processes/vpgl_generate_xyz_from_depth_image_process.cxx
- contrib/brl/bseg/boxm2_multi/algo/boxm2_multi_pre_vis_inf.cxx
- contrib/brl/bseg/brip/brip_phase_correlation.cxx
- contrib/brl/bseg/bstm/ocl/algo/bstm_ocl_minfo_function.cxx
- contrib/brl/bseg/sdet/sdet_graph_img_seg.cxx
- contrib/brl/bseg/sdet/sdet_graph_img_seg.h
- contrib/brl/bseg/sdet/sdet_sel_base.cxx
- contrib/brl/bseg/sdet/sdet_texture_classifier.cxx
- contrib/mul/msm/msm_cubic_bezier.cxx
- core/vgl/algo/vgl_fit_sphere_3d.txx
- core/vgl/vgl_cubic_spline_2d.h
- core/vgl/vgl_cubic_spline_3d.h
- core/vnl/vnl_real_polynomial.cxx
- core/vpgl/vpgl_generic_camera.txx
Compiling on g++ using the flags `-Wall -Wextra -Wuninitialized` produced roughly 18,000 lines of compiler warnings.  This patch addresses roughly 2.8% of those warnings.  The hope is that a series of no-op patches like these will begin to reduce "error fatigue" and bring to the fore actual bugs that the warnings may be pointing out.
> COMP: Addressing some compiler warnings.

- CMakeLists.txt
Remove warning by disabling test.  The proper fix
will require careful effort.
Documentation for what would be a better solution
is given at https://github.com/vxl/vxl/issues/127
and https://github.com/vxl/vxl/pull/122
> COMP: Silence warning about deprecated use

- CMakeLists.txt
We now require cmake 2.8.9 or greater.  Code related
to 2.6 work arounds could be removed.
> STYLE: Improve cmake policy setting

- core/vgui/vgui_satellite_tableau.h
vxl/core/vgui/vgui_satellite_tableau.h:163:105: error: type-id cannot have a name
struct vgui_satellite_tableau_t_new : public vgui_tableau_sptr_t<vgui_satellite_tableau_t<object, data> vgui_tableau_sptr>
^~~~~~~~~~~~~~~~~
/Users/johnsonhj/src/vxl/core/vgui/vgui_satellite_tableau.h:167:36: error: type-id cannot have a name
typedef vgui_tableau_sptr_t<impl vgui_tableau_sptr> base;
^~~~~~~~~~~~~~~~~
vxl/core/vgui/vgui_satellite_tableau.h:175:95: error: type-id cannot have a name
struct vgui_satellite_tableau_new : public vgui_tableau_sptr_t<vgui_satellite_tableau<object> vgui_tableau_sptr>
^~~~~~~~~~~~~~~~~
vxl/core/vgui/vgui_satellite_tableau.h:179:36: error: type-id cannot have a name
typedef vgui_tableau_sptr_t<impl vgui_tableau_sptr> base;
^~~~~~~~~~~~~~~~~
> COMP: Fix syntax errors in vgui_satellite_tableu.h

- vxl_common.cmake
@hjmjohnson This is expected to fail any CI tests, as it doesn't actually contain any code, it is just a script to build dashboards. These changes make it easier to submit coverage and memory checks to the dashboard. If you think the changes are useful, it should be merged into the dashboard branch, not into master.
> Removes spaces and adds support for automatic coverage and memory checking

- core/vnl/vnl_math.cxx
When creating missing is isinf and isnormal functions
for case when isnan and isfinite are not in global or std
namespace, use the previously defined vnl_math::isnan and
vnl_math::isnormal functions.
> BUG: Windows isfinite isnan not in global namespace

- contrib/brl/bbas/bpgl/depth_map/depth_map_region.cxx
UMC
==Conditional jump or move depends on uninitialised value(s)
==   at 0xC363993: vsl_b_write(vsl_b_ostream&, bool) (vsl_binary_io.cxx:96)
==   by 0x6B8D377: depth_map_region::b_write(vsl_b_ostream&) (depth_map_region.cxx:472)
==   by 0x6B8D0B3: vsl_b_write(vsl_b_ostream&, depth_map_region const*) (depth_map_region.cxx:438)
This is related to issue #54, and many of the BRL related failing tests
> BUG: BRL uninitialized memory causes errors

- core/vil/file_formats/vil_bmp.cxx
== Mismatched free() / delete / delete []
== by 0x5123DB6: vil_bmp_image::write_header() (vil_bmp.cxx:356)
== by 0x5122FD4: vil_bmp_image::vil_bmp_image(vil_stream*, unsigned int, unsigned int, unsigned int, vil_pixel_format) (vil_bmp.cxx:113)
> BUG: Fix valgrind mismatch delete

- core/tests/make_test_config.pl
- core/tests/test_config.cxx
- core/vnl/tests/test_bignum.cxx
- core/vnl/tests/test_math.cxx
- core/vnl/vnl_math.cxx
The __alpha__ archetecture is no longer supported,
so simplify the code logic.
> STYLE: Remove support for __alpha__ architecture

- contrib/brl/bseg/boxm2/class/CMakeLists.txt
- contrib/brl/bseg/boxm2/reg/ocl/CMakeLists.txt
- contrib/brl/bseg/boxm2/util/boxm2_convert_nvm_txt.cxx
- contrib/brl/bseg/boxm2/vecf/CMakeLists.txt
- contrib/brl/bseg/boxm2/vecf/ocl/CMakeLists.txt
- contrib/brl/bseg/boxm2/volm/CMakeLists.txt
- contrib/brl/bseg/boxm2/volm/desc/CMakeLists.txt
- core/vidl/CMakeLists.txt
Since supporting whatever version of ffmpeg happens to be available seems to be a tricky issue, I added a "WITH_FFMPEG" cmake option that will not bother searching for it if turned off.  The option is on by default so default behavior shouldn't change.   @mleotta mentioned in pull request #98  that there may be support for ffmpeg version checking added in the future, so this option could probably be removed at that point.
> optionally build without ffmpeg support

- v3p/CMakeLists.txt
- v3p/zlib/CMakeLists.txt
On windows, zlib is often not installed in a path
that can be automatically found by cmake.  In those cases,
install a private version of zlib.
> COMP: Need to build zlib if not installed.

- core/vnl/vnl_matrix.h
- core/vnl/vnl_matrix_fixed.h
- core/vnl/vnl_vector.h
- vcl/vcl_compiler.h
Some variables are only used in debug mode.  Provide a macro
to hide those variables when compiling without assertions.
> COMP: Provde macro to hide unused debug variables

- core/vnl/tests/test_complex.cxx
The vnl_test_complex test for '/=' operator is
failing on gcc 4.9.3 compiler.  This patch instruments the
test to help identify the problem.
> ENH: Instrument test_complex to help identify failure

- CMakeLists.txt
This patch enable user to specify the desired location for executables and library archives.  By default, it will be ${CMAKE_CURRENT_BINARY_DIR}/bin and ${CMAKE_CURRENT_BINARY_DIR}/lib.
Some redundant replicas codes are cleaned as well
> Enable RUNTIME,ARCHIVE,LIBRARY setting during cmake configuration

- contrib/brl/bbas/bil/algo/bil_compass_edge_detector.cxx
- contrib/brl/bbas/bmsh3d/algo/bmsh3d_mesh_tri.cxx
- contrib/brl/bseg/brip/brip_vil_float_ops.cxx
- core/vgui/tests/test_image_tableau.cxx
- core/vpgl/file_formats/vpgl_nitf_rational_camera.cxx
warning: Memory allocated by 'new[]' should be deallocated by
'delete[]', not 'delete' [clang-analyzer-unix.MismatchedDeallocator]
for i in $(cat /tmp/xx ); do
clang-tidy -p ~/src/vxl-bld/ $i \
-checks=-*,clang-analyzer-unix.MismatchedDeallocator -fix;
done |tee ../warning_list.txt 2>&1
> BUG: Match new/delete signatures for memory

- contrib/mul/clsfy/CMakeLists.txt
- contrib/mul/fhs/CMakeLists.txt
- contrib/mul/ipts/CMakeLists.txt
- contrib/mul/m23d/CMakeLists.txt
- contrib/mul/mbl/CMakeLists.txt
- contrib/mul/mcal/CMakeLists.txt
- contrib/mul/mfpf/CMakeLists.txt
- contrib/mul/mipa/CMakeLists.txt
- contrib/mul/mmn/CMakeLists.txt
- contrib/mul/msdi/CMakeLists.txt
- contrib/mul/msm/CMakeLists.txt
- contrib/mul/msm/utils/CMakeLists.txt
- contrib/mul/mvl2/CMakeLists.txt
- contrib/mul/pdf1d/CMakeLists.txt
- contrib/mul/vil3d/CMakeLists.txt
- contrib/mul/vil3d/algo/CMakeLists.txt
- contrib/mul/vil3d/io/CMakeLists.txt
- contrib/mul/vimt/CMakeLists.txt
- contrib/mul/vimt/algo/CMakeLists.txt
- contrib/mul/vimt3d/CMakeLists.txt
- contrib/mul/vpdfl/CMakeLists.txt
Extends previous work for core libraries
to the contrib/mul directories.
There was much redundant code needed to setup
the installation of libraries in a way compatible
for external applications.  This redundant code
was consolidated into a macro that can be consistently
applied.
> ENH: Add vxl_add_library for contrib/mul

- contrib/brl/bseg/bapl/bapl_keypoint_extractor.cxx
- contrib/brl/bseg/boxm2/cpp/algo/boxm2_export_oriented_point_cloud.cxx
- contrib/brl/bseg/boxm2/cpp/algo/boxm2_export_oriented_point_cloud_function.cxx
- contrib/brl/bseg/boxm2/cpp/algo/boxm2_extract_point_cloud.cxx
- contrib/brl/bseg/boxm2/cpp/algo/boxm2_merge_block_function.cxx
- contrib/brl/bseg/boxm2/cpp/algo/boxm2_update_functions.cxx
- contrib/brl/bseg/boxm2/cpp/pro/processes/boxm2_cpp_batch_compute_synoptic_function_1d_process.cxx
- contrib/brl/bseg/boxm2/cpp/pro/processes/boxm2_cpp_batch_update_nonsurface_model_process.cxx
- contrib/brl/bseg/boxm2/cpp/pro/processes/boxm2_cpp_batch_update_opt2_phongs_processes.cxx
- contrib/brl/bseg/boxm2/ocl/algo/boxm2_ocl_aggregate_normal_from_filter_vector.cxx
- contrib/brl/bseg/boxm2/ocl/algo/boxm2_ocl_change_detection.cxx
- contrib/brl/bseg/boxm2/ocl/algo/boxm2_ocl_cone_update_function.cxx
- contrib/brl/bseg/boxm2/ocl/algo/boxm2_ocl_filter_scene_data.cxx
- contrib/brl/bseg/boxm2/ocl/algo/boxm2_ocl_paint_batch.cxx
- contrib/brl/bseg/boxm2/ocl/algo/boxm2_ocl_refine_scene_around_geometry.cxx
- contrib/brl/bseg/boxm2/ocl/algo/boxm2_ocl_update_auxQ.cxx
- contrib/brl/bseg/boxm2/ocl/algo/boxm2_ocl_update_sky.cxx
- contrib/brl/bseg/boxm2/reg/ocl/boxm2_ocl_reg_mutual_info.cxx
- contrib/brl/bseg/boxm2/reg/ocl/boxm2_ocl_reg_points_to_volume_mutual_info.cxx
- contrib/brl/bseg/boxm2/vecf/ocl/boxm2_vecf_ocl_transform_scene.cxx
- contrib/brl/bseg/boxm2_multi/algo/boxm2_multi_render.cxx
- contrib/brl/bseg/boxm2_multi/algo/boxm2_multi_update_cell.cxx
- contrib/brl/bseg/bstm/ocl/algo/bstm_ocl_change_detection.cxx
- contrib/brl/bseg/bvxm_bridge/bvxm_to_boxm2.cxx
- contrib/gel/gevd/gevd_edgel_regions.cxx
- contrib/gel/vmal/vmal_dense_matching.cxx
- core/vil/vil_decimate.h
- core/vul/vul_psfile.cxx
The clang static analyser produces many useful diagnostic warnings,
including "Division by zero". These warnings arise when
variables are not checked to see if they are zero before being used
as divisors. Most of these warnings would never actually result in
division by zero in real world usage.
> COMP: Removes "Division by zero" Warnings

- core/vpgl/algo/tests/test_optimize_camera.cxx
- core/vpgl/algo/vpgl_optimize_camera.cxx
- core/vpgl/algo/vpgl_optimize_camera.h
Adds a function to optimize position, orientation and focal  length to vpgl_optimize_camera, as well as some test coverage.  Previously, no tests were actually computed in test_optimize_camera.
> optimizer for position, orientation, and focal length  + better test coverage

- config/cmake/Modules/CheckPrototypeExistsCXX.cmake
- config/cmake/config/vxl_utils.cmake
- core/tests/CMakeLists.txt
The IMMEDIATE keyworrd is not used any longer in the configure_file
function, in fact it is the default behavior.
See: http://www.itk.org/Bug/view.php?id=12434
> STYLE: Outdated IMMEDIATE flag to configure_file

- .travis/install-deps.sh
This provides better testing as exposed by issue #194
When building with cmake 3.4.0 there were no build failures,
but when using the minimum cmake version of 2.8.9 the default
search paths were insufficient to find necessary configuration
files.
The continuous integration testing environment should use
the minimum cmake version to induce errors early.
> ENH: Minimum supported cmake version configured

- contrib/brl/bbas/bsta/algo/tests/test_fit_gaussian.cxx
This should fix the random failures of the bsta_fit_gaussian test.   I was able to find a random seed that consistently reproduced the failure.  Increasing the number of random samples given to the estimator fixes the problem.  The random seed is hard-coded now.
> fix sporadic failures of bsta_fit_gaussian test

- core/vnl/tests/test_matrix.cxx
- core/vnl/vnl_matrix.h
- core/vnl/vnl_matrix.txx
This patch allows the user to apply a function which takes a vector and returns a scalar rowwise or columnwise across a matrix.  This is meant to mimic the functionality of the `apply` functions present in R and in Python.
> Apply Rowwise and Columnwise

- contrib/brl/bbas/bsta/bsta_k_medoid.cxx
- core/bin/check_consistency
- core/vnl/tests/test_math.cxx
- core/vnl/vnl_math.cxx
- core/vnl/vnl_math.h
VC9 compiler does not have macros for HUGE_VAL or HUGE_VALL so
remove the need for these.
http://en.cppreference.com/w/cpp/numeric/math/HUGE_VAL
"On implementations that support floating-point infinities, these macros
always expand to the positive infinities of float, double, and long
double, respectively."
We already have vcl_numeric_limits<>::infinity() defined, so use that
instead for consistent behavior.
> COMP: VC9 Does not have HUGE_VAL or HUGE_VALL

- vcl/CMakeLists.txt
- vcl/vcl_cmath.h
- vcl/vcl_complex.h
- vcl/vcl_cstdlib.h
- vcl/vcl_valarray.h
- vcl/win32-vc9/vcl_cmath.h
- vcl/win32-vc9/vcl_complex.h
- vcl/win32-vc9/vcl_cstdlib.h
- vcl/win32-vc9/vcl_valarray.h
The code comments in the VC9 alternate files
were comments referencing VC8 and VC7 that are
no longer supported.  Once the VC8 and VC7
specific comments were removed, there was
no longer any specialization for VC9, so
the alternate files for VC9 were no longer
relevant and indicate that VC9 will work
even without these files.
> STYLE: VC9 compatibility does not seem necessary

- core/vnl/tests/test_diag_matrix.cxx
- core/vnl/tests/test_diag_matrix_fixed.cxx
- core/vnl/tests/test_matrix.cxx
- core/vnl/tests/test_matrix_fixed.cxx
- core/vnl/tests/test_sym_matrix.cxx
- core/vnl/tests/test_vector.cxx
- core/vnl/vnl_diag_matrix.h
- core/vnl/vnl_diag_matrix_fixed.h
- core/vnl/vnl_error.cxx
- core/vnl/vnl_error.h
- core/vnl/vnl_matrix.h
- core/vnl/vnl_matrix_fixed.h
- core/vnl/vnl_sym_matrix.h
- core/vnl/vnl_vector.h
- core/vnl/vnl_vector_fixed.h
Currently, the behavior when accessing elements in vnl containers
using the get() and put() functions is inconsistent.  This patch
attempts to unify the behavior somewhat, such that exceptions
are raised when an out-of-bounds index is requested from `get()` or
`put()` and  `VNL_CONFIG_CHECK_BOUNDS` is enabled.
Importantly, the behavior of the functions in `vnl_error.h` has been
modified such that exceptions are raised, rather than simply
aborting.  This makes the behavior of the functions consistent
with their current documentation.
This patch addresses an issue (https://github.com/vxl/vxl/issues/206) raised here.
> ENH: Unifying out-of-bounds behavior for vnl containers.

- config/cmake/config/vxl_utils.cmake
property not containing full path in cmake 2.8.11.
@hjmjohnson @andyneff This should fix the cmake errors...
> BUG: Fix cmake errors related to INTERFACE_INCLUDE_DIRECTORY

- core/vnl/tests/test_diag_matrix.cxx
- core/vnl/tests/test_diag_matrix_fixed.cxx
- core/vnl/tests/test_matrix.cxx
- core/vnl/tests/test_matrix_fixed.cxx
- core/vnl/tests/test_sym_matrix.cxx
- core/vnl/tests/test_vector.cxx
- core/vnl/vnl_diag_matrix.h
- core/vnl/vnl_diag_matrix_fixed.h
- core/vnl/vnl_matrix.h
- core/vnl/vnl_matrix_fixed.h
- core/vnl/vnl_sym_matrix.h
- core/vnl/vnl_vector.h
- core/vnl/vnl_vector_fixed.h
A bunch of #ifdefs were added when it should have been #ifs. This caused
building in Release to fail, because code that should not have been active, was
Bugs were introduced in 0dd5124a823be67f7779613fbc5d06a1af5d4508 and PR #207 
This bug was missed by travis-ci because it only manifested in Non-Debug modes (Release, RelWithDebInfo, etc...) It showed up [here](https://open.cdash.org/viewBuildError.php?buildid=4257489 ) because this cdash was configured for Release mode.
@DVigneault Does this patch look alright?
> BUG: Fixed VNL_CONFIG_CHECK_BOUNDS bug

- vcl/win32-vc9/vcl_cmath.h
- vcl/win32-vc9/vcl_complex.h
- vcl/win32-vc9/vcl_cstdlib.h
- vcl/win32-vc9/vcl_valarray.h
The win32-vc9 directory was tested and determined to be
unnecessary.  Previous patch (35893e482edc5feea54623b571c9041c5de57e1c)
set had removed compiling this code, but neglected to remove these
files.
> STYLE: Remove files that can no longer be accessed

- CMakeLists.txt
Project that use VXL internally, like ITK, will have these variables
overridden -- they are not usually cached.
Also, this prevents the variables from being non-advanced variables exposed
someone configuring VXL. They usually are not changed and should not be
considered advanced.
> Do not override CMake output variables.

- core/vnl/vnl_matrix_fixed.h
- core/vnl/vnl_vector.h
- core/vnl/vnl_vector_fixed.h
- core/vnl/vnl_vector_fixed_ref.h
The value type for size_type was different in
different parts of vxl.  In all cases using
an alias to size_t seems to work well.
This has the advantage of being consistent
in all parts of vxl.
> ENH: Make size_type uniform accross vxl

- v3p/CMakeLists.txt
Fix our `if(... AND EXISTS zlib)` condition to check for the source
directory via absolute path.  Otherwise it checks the current working
directory of CMake and may not think the `zlib` source directory exists.
> v3p: Fix check for local zlib directory

- core/vnl/tests/test_matrix_fixed.cxx
- core/vnl/vnl_matrix_fixed.h
- core/vnl/vnl_matrix_fixed.hxx
`apply_rowwise` and `apply_columnwise` methods were recently added to `vnl_matrix`.  This patch extends this functionality to `vnl_matrix_fixed`.
> ENH: Apply across rows and columns of matrix_fixed

- contrib/brl/b3p/expat/CMakeLists.txt
Define CM_EXPAT_STATIC early enough to be seen by the configure_file
call that uses it.
> brl: Fix static library build of expat on Windows

- contrib/brl/bbas/bgui/tests/test_histogram.cxx
- core/vgui/tests/test_range_map.cxx
- core/vnl/algo/tests/test_util.cxx
- core/vnl/algo/tests/test_util.h
- core/vnl/tests/test_bignum.cxx
- core/vnl/tests/test_math.cxx
- core/vnl/tests/test_numeric_traits.cxx
- vcl/tests/test_cmath.cxx
- vcl/vcl_compiler.h
Valgrind does not support long double (see #161 for details)
This patch supressesses long double tests when built in debug mode
(i.e. them mode used for valgrind), but does provide a mechanism for
forcing these tests, even in debug mode.
This is needed to help clean up the nightly valgrind warnings.
> COMP: Suppress valgrind long double false positives

- vcl/vcl_compiler.h
- vcl/vcl_cstdio.h
The ordering of the combined #if were causing an incorrect
overwriting of vcl_snprintf as std:;snprintf even in the
special case when _MSVER<1900.
> BUG: Error in ordering of #defines for _MSVER<1900

- vcl/tests/test_memory.cxx
- vcl/vcl_compiler.h
Tests that are only built for the dashboard were failing.
These a bit of logic that was accidently removed during
recent cleanups.  Add ability to compile with both
tr1 and C++11 features.
> COMP: Fix advanced tr1 feature use and C++11

- vcl/vcl_compiler.h
- vcl/vcl_cstdio.h
Old MSVS compilers also need cstdarg included
when overriding the snprintf functions.
> BUG: Missed moving header for old MSVS compiler

- core/vgui/tests/test_range_map.cxx
- vcl/vcl_compiler.h
On older windows compilers they need other headers
in order to define functions needed to provide
specializations of snprintf.
> BUG: Older windows were missing headers

- config/cmake/config/vxl_utils.cmake
- vcl/CMakeLists.txt
@hjmjohnson This fixes some of ITK's 'build against an install tree' issues.  For the others, we could maybe use the `snapshot_redact_cmd` of the `UpdateFromUpstream.sh` script.
> vcl header install locations

- core/vbl/vbl_array_3d.h
fixes a crash caused by calling data_block() on an empty vbl_array_3d
> avoid accessing element_ if array is empty

- config/cmake/config/vxl_utils.cmake
This addresses warnings like:
CMake Error in contrib/prip/vdtop/CMakeLists.txt:
Target "vdtop" INTERFACE_INCLUDE_DIRECTORIES property contains relative
path:
"include/vxl/contrib/prip/vdtop"
CMake Error in contrib/prip/vpyr/CMakeLists.txt:
Target "vpyr" INTERFACE_INCLUDE_DIRECTORIES property contains relative
path:
"include/vxl/contrib/prip/vpyr"
Although current target_include_directories documentation recommends using a
relative path for the install interface.  The warning is not present with
CMake 2.8.12.
@bradking please review.
CC: @hjmjohnson @blowekamp
> Do not use target_include_directories with CMake 2.8.11.

- contrib/brl/bseg/boxm2/vecf/boxm2_vecf_fit_fat_pocket.cxx
- core/vil/file_formats/vil_j2k_image.cxx
- core/vil/file_formats/vil_nitf2_image.cxx
Under Visual Studio 2012, std::less and std::greater are defined in <functional>.  Adding this header to avoid compiler error
second std type of compiler error was occurred in windows when v3p/j2k is used.  This error is fixed by avoiding the confliction between max/min in windows.h and std::max/std::min
> fix std compile error under Visual Studio 2012

- core/vul/CMakeLists.txt
The generation of the vul_export.h file was in a conditional part
of the cmake list based on platform type.  It is now pushed outside of
the platform definition section.
> BUG: Generation of export header is unconditional

- core/vnl/tests/test_matrix.cxx
- core/vnl/vnl_matrix.h
- core/vnl/vnl_matrix.hxx
This patch adds methods allowing a matrix to be composed from the rows/columns of a given matrix by supplying a vector of row/column indices.  This is conceptually analogous to what can be done in other languages/packages, e.g., in R:
m <- matrix(data = c(1, 2, 3, 4, 5, 6), nrow = 2, ncol = 3)
m.from.rows <- m[c(2,1,1,2),]
m.from.cols <- m[,c(3,2,1,1,2,3)]
One specific use case might be in sorting eigenvectors based on eigenvalues.
vnl_real_eigensystem eig(SomeMatrix);
const auto eigenvectors = vnl_real(eig.V);
const auto eigenvalues = vnl_real(eig.D.get_diagonal());
TSort sort;
vnl_vector<TReal>  sortedEigenvalues;
vnl_vector<TIndex> sortedEigenvalueIndices;
sort.vector_sort(eigenvalues, sortedEigenvalues, sortedEigenvalueIndices);
const auto sortedEigenvectors = …
> ENH: Compose new matrix by row and column indices.

- contrib/brl/bseg/boxm2/ocl/exe/boxm2_export_scene.cxx
Allow elevation increment for case where num_in()==1.
> Avoid divide by zero

- contrib/brl/bseg/boxm2/ocl/boxm2_opencl_cache.cxx
- contrib/brl/bseg/boxm2/ocl/boxm2_opencl_cache.h
On windows, unsigned long is a 4 byte integer.  For a GPU with very large VRAM (e.g. 12GB on NVIDIA Titan-X), the total global memory exceeds the maximum value a 4 byte unsigned long can represent.  Change type of "maxBytesInCache_" and "bytesInCache_" to size_t to avoid integer overflow.
> Prevent integer overflow on Windows

- contrib/brl/bbas/bvgl/bvgl_k_nearest_neighbors_3d.h
bvgl_k_nearest_neighbors_3d already has a custom destructor, so this
commit satisfies the "rule of three".  The default implementations lead
to errors due to copying of the raw search_tree_ pointer.
> implement copy constructor and assigment operator

- v3p/netlib/CMakeLists.txt
The minimum required version of CMake is 2.8.7, which is greater than 2.4.  Therefore, this code is unreachable and has been removed.
> STYLE: Remove dead CMake code.

- core/vgl/algo/CMakeLists.txt
- core/vgl/algo/Templates/compute_rigid_3d+double-.cxx
- core/vgl/algo/tests/CMakeLists.txt
- core/vgl/algo/tests/test_compute_rigid_3d.cxx
- core/vgl/algo/tests/test_compute_similarity_3d.cxx
- core/vgl/algo/tests/test_driver.cxx
- core/vgl/algo/vgl_compute_rigid_3d.h
- core/vgl/algo/vgl_compute_rigid_3d.hxx
- core/vgl/algo/vgl_compute_similarity_3d.h
- core/vgl/algo/vgl_compute_similarity_3d.hxx
This PR adds support for computing a rigid transform via the vgl_compute_similarity_3d class by fixing the scale at 1.   I thought that adding a separate "vgl_compute_rigid_3d" class (with the commonalities factored out into a third class) would be overkill but could be convinced otherwise.
> Add option to compute rigid transform via vgl_compute_similarity_3d

- CMakeLists.txt
In cmake 3.3 and greater, visibility can be used for static
libraries so that they can later be linked into shared
libraries.
> COMP: Set policy to respect VISIBILITY in static

- core/vnl/vnl_numeric_traits.cxx
- core/vnl/vnl_numeric_traits.h
vxl/core/vnl/vnl_numeric_traits.h:182:41: error: constexpr static data member ‘maxval’ must have an initializer
static VNL_EXPORT VXL_CONSTEXPR short maxval; // = 0x7fff;
> BUG: VXL_CONSTEXPR requires initialization

- core/vidl/vidl_convert.cxx
- core/vnl/algo/vnl_sparse_lm.cxx
- core/vnl/io/vnl_io_sparse_matrix.hxx
- core/vpgl/algo/tests/test_camera_compute.cxx
- core/vpgl/algo/tests/test_camera_convert.cxx
- core/vpgl/algo/tests/test_optimize_camera.cxx
- core/vpgl/algo/vpgl_affine_rectification.cxx
- core/vpgl/algo/vpgl_camera_convert.cxx
- v3p/netlib/laso/urand.c
The gcc5 compiler identified a few unused variables and
type mis-matches.
> COMP: Remove compiler warnings from gcc5

- core/vpgl/vpgl_affine_camera.h
- core/vpgl/vpgl_affine_camera.hxx
Previously, the implementations (incorrectly) fell back to those defined in `vpgl_proj_camera`.  The `backproject_ray` implementation in` vpgl_proj_camera` would sometimes give incorrect ray direction in the case of affine cameras.
> add implementations of clone and backproject_ray to affine_camera

- contrib/brl/bbas/bvgl/bvgl_scaled_shape_3d.h
- core/vsl/vsl_binary_io.cxx
There was redundant code for all integer type vsl_read/write_io functions
that was implicated in a valgrind error of an uninitialized read
operation that caused frequent dashboard failures.
> STYLE: Replace redundant code with local template function

- config/cmake/config/vxl_utils.cmake
As a follow up to vxl/vxl@d7d6314fb9846b923a5e90e8f7f65b3ab28bfc8e
target_include_directories does not work with relative paths in 2.8.11.2 also.
> Do not use target_include_directories with CMake 2.8.11.2.

- config/cmake/config/vxl_utils.cmake
- core/vnl/CMakeLists.txt
The relatively minor changes allow VTK to be integrated with other
packages (i.e. ITK) with less maintenance effort.
> STYLE: Backport of changes needed for ITK integration

- core/vpgl/algo/vpgl_camera_convert.cxx
- core/vpgl/algo/vpgl_camera_convert.h
This commit makes it possible to build vpgl without GeoTIFF enabled.  The rest of core also builds without GeoTIFF, but there are numerous issues in BRL.
> support build of vpgl without geotiff

- contrib/brl/b3p/expatpp/expatpp.cpp
- contrib/brl/bbas/bil/algo/bil_compass_edge_detector.cxx
- contrib/brl/bbas/bnabo/bnabo_index_heap.h
- contrib/brl/bseg/boxm2/vecf/ocl/boxm2_vecf_ocl_filter.cxx
- contrib/brl/bseg/boxm2/volm/boxm2_volm_matcher_p1.cxx
- contrib/tbl/vipl/vipl_add_random_noise.hxx
- contrib/tbl/vipl/vipl_dilate_disk.hxx
- contrib/tbl/vipl/vipl_erode_disk.hxx
- contrib/tbl/vipl/vipl_gradient_dir.hxx
- contrib/tbl/vipl/vipl_gradient_mag.hxx
- contrib/tbl/vipl/vipl_median.hxx
- contrib/tbl/vipl/vipl_x_gradient.hxx
- contrib/tbl/vipl/vipl_y_gradient.hxx
- core/vil/file_formats/vil_nitf2_tagged_record.cxx
- core/vsl/tests/test_arbitrary_length_int_conversion.cxx
This PR addresses two types of compiler warnings I'm getting on OSX:
-- deprecated use of the `register` keyword
-- Mismatched `new` / `delete` and `new[]` / `delete[]`
This has been verified on my system on top of this [pull request](https://github.com/vxl/vxl/pull/308), without which vxl does not build.
> COMP: Address compiler warnings on OSX

- contrib/rpl/rrel/rrel_homography2d_est.cxx
Check that matrix is_finite before allowing assert. A non-finite matrix will cause a segfault.
> Check matrix finite before assert

- vcl/vcl_compiler_detection.h
Older compilers may not be explicitly supported
in cmake for granular language support.
In these cases fall through to a default
behavior when using old compilers.
> COMP: Allow compilation for older compilers

- core/vnl/tests/CMakeLists.txt
- core/vnl/tests/test_container_interface.cxx
- core/vnl/tests/test_driver.cxx
- core/vnl/tests/test_matrix.cxx
- core/vnl/tests/test_matrix_fixed.cxx
- core/vnl/vnl_matrix.hxx
- core/vnl/vnl_matrix_fixed.h
- core/vnl/vnl_matrix_fixed.hxx
VNL containers are not related by inheritance; as such, maintaining
a common interface (where applicable) is not enforced.  Therefore,
container classes may diverge, causing methods to be absent which
the user would logically expect to have.  This patch is a very early
attempt at uncovering and implementing such missing methods through
test-driven-development.  In particular, the following four methods
have been added to `vnl_matrix_fixed`:
- `swap`
- `is_equal`
- `get_rows`
- `get_columns`
In addition to providing a (more) unified interface, this technique
may reduce the burden in writing unit tests, which currently are
written separately for each container, even when the behavior is
expected to be identical.  The `container_interface` unit test
which is added here provides runtime unit …
> ENH: Encourage unified container interface.

- core/vnl/tests/test_matrix_fixed.cxx
- core/vnl/vnl_vector_fixed.h
- core/vnl/vnl_vector_fixed.hxx
The intel compiler identifited that:
error: no suitable user-defined conversion from "vnl_vector_fixed" to "const vnl_vector" exists
Do the conversion explicitly.  This also exercised more code and
required a change to avoid a linking problem with vnl_vector_fixed.
> COMP: Intel compiler incompatibility

- core/vnl/tests/test_container_interface.cxx
The "r" variable was not being initialized due
to a copy-n-paste bug.
This was identified by valgrind as an uninitialized
memory read error.
> BUG: There was a logical error in the test

- core/vnl/vnl_matrix_fixed.hxx
Prefer to use std::copy( dp, dp + nrows * ncols, p );
over standard looping structures.
> ENH: Improve memory block copying

- core/vnl/tests/test_container_interface.cxx
This new test now excersises code that was previously
not used.  The test are failing on MSVS15, and that is
causing a roadblock to integration and other testing.
A temporary disabling of the small subset of sub-tests
that are failing in Release mode of MSVS15 (but not in Debug mode)
has been done.
> BUG: One small part of this new test is failing on MSVS15

- core/vil/algo/tests/test_algo_find_plateaus.cxx
- core/vil/algo/vil_quad_distance_function.h
- core/vnl/vnl_vector.h
- core/vnl/vnl_vector.hxx
- core/vnl/vnl_vector_fixed.h
- core/vnl/vnl_vector_fixed.hxx
- core/vpgl/algo/examples/vpgl_synth_bundle_adjust.cxx
- core/vpgl/algo/vpgl_em_compute_5_point.hxx
- core/vpgl/tests/test_poly_radial_distortion.cxx
- core/vsl/vsl_basic_xml_element.h
Variables that identify memory locations (either size, or access)
should use size_t.
http://stackoverflow.com/questions/1951519/when-should-i-use-stdsize-t
A good rule of thumb is for anything that you need to compare in the loop condition against something that is naturally a std::size_t itself.
std::size_t is the type of any sizeof expression and as is guaranteed to be able to express the maximum size of any object (including any array) in C++. By extension it is also guaranteed to be big enough for any array index so it is a natural type for a loop by index over an array.
If you are just counting up to a number then it may be more natural to use either the type of the variable that holds that number or an int or unsigned int (if large enough) as these should be a natural size for the …
> COMP: Prefer size_t for memory indicies access

- core/vnl/vnl_matrix_fixed.hxx
Moderately old versions of compilers struggled with this
new swap of multi-dimensional array.  Provide a more robust
solution.
Standard Error
/opt/gcc-4.3/lib/gcc/x86_64-unknown-linux-gnu/4.3.5/../../../../include/c++/4.3.5/bits/stl_move.h: In function 'void std::swap(_Tp&, _Tp&) [with _Tp = double [1][6]]':
/scratch/dashboards/Linux-x86_64-gcc4.3/ITK/Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_matrix_fixed.hxx:393:   instantiated from 'void vnl_matrix_fixed<T, num_rows, num_cols>::swap(vnl_matrix_fixed<T, num_rows, num_cols>&) [with T = double, unsigned int num_rows = 1u, unsigned int num_cols = 6u]'
/scratch/dashboards/Linux-x86_64-gcc4.3/ITK/Modules/ThirdParty/VNL/src/vxl/core/vnl/Templates/vnl_matrix_fixed+double.1.6-.cxx:2:   instantiated from here …
> COMP: Provide backwards compatible implementation

- CMakeLists.txt
Set CMP0063 to NEW to enable the CMake visibility properties to be
honored when building static libraries.
> COMP: Enable hidden visibility property with vxl static libraries

- core/vnl/tests/test_complex.cxx
Add tolerance for small numerical errors that cause the
inner_product and dot_product tests to sometimes fail on i386.
ITK-3453
> BUG: Relax vnl_complex floating point comparisons for i386

- core/vnl/CMakeLists.txt
Previously it was installed to vxl/vnl/vnl_config.h while it should
have been vxl/core/vnl/vnl_config.h
> Fixed the install path of vnl_config.h

- core/vnl/CMakeLists.txt
- core/vnl/algo/CMakeLists.txt
This is a follow-up to bf529035221b7 and 5840b695d958379c. ITK uses modified
VXL header locations, and these locations should be retained for backwards
compatibility. This helps ITK and VXL remain in sync.
> BUG: Maintain header installation locations compatible with ITK

- core/vil/vil_config.h.in
The vil_config.h file was configured with a define for VXL_HAS_SSE2_HARDWARE_SUPPORT
that was either 0 or 1. All uses of this symbol were of the #ifdef style.
The result is that the symbol is always defined. This change uses the
#cmakedefine feature which will define the symbol if it has a TRUE
value in cmake. Otherwise it will not be defined. This approach matches
the usage in the code.
> BUG: Convert define 0/1 paradigm to ifdef

- core/vidl/vidl_ffmpeg_istream_stub.hxx
- core/vidl/vidl_ffmpeg_ostream_stub.hxx
- core/vidl/vidl_ffmpeg_pixel_format.cxx
The ffmpeg_xstream_stub-s did not make it apparent that the reason they were failing is that there was no ffmpeg configured. This patch makes bot stubs behave the same and adds an exception if the application tries to open a stream.
Also added two symbols that were missing when an older ffmpeg was used.
> Fix ffmpeg stubs

- config/cmake/Modules/UseVXL.cmake
One of the benefits is consumers may not get the VXL warnings during their compiles.`
> Expose VXL's include_directories as SYSTEM. Its intent is API.

- core/vnl/algo/CMakeLists.txt
The vnl/algo/vnl_algo_export.h file was being installed in the wrong
directory.
> Add missing curly bracket.

- core/vnl/io/vnl_io_matrix.hxx
- core/vnl/vnl_identity_3x3.h
- core/vnl/vnl_transpose.h
This solves some undefined symbols errors seen when linking shared on VS 2015.
> Fix linking issues with shared builds on VS 2015

- core/vidl/vidl_ffmpeg_pixel_format.cxx
This was failing with Ubuntu 14.04 because major version 56 is not
specific enough.
> Fixed the version of avcodec at which PIX_FMT becomes AV_PIX_FMT

- .travis.yml
All Travis CI builds were failing due to excessive
build times.
This patch turns off the brl contributed library
in order to reduce the build & testing time to
fit into the time constraints of the Travis CI
build environment.
Build times for the contributed libraries.
============
brl
real	19m37.929s
user	35m3.023s
sys	3m57.498s
============
conversions
real	0m12.131s
user	0m19.362s
sys	0m3.080s
============
gel
real	0m58.859s
user	1m43.370s
sys	0m11.452s
============
mul
real	2m30.535s
user	4m26.628s
sys	0m31.357s
============
oul
real	0m5.226s
user	0m6.455s
sys	0m1.260s
============
oxl
real	0m6.294s
user	0m8.430s
sys	0m2.037s
============
prip
real	0m9.181s
user	0m14.919s
sys	0m1.795s
============
rpl
real	0m56.946s
user	1m40.825s
sys	0m10.785s
============
tbl
real	0m26.589s
user …
> COMP: Reduce travis build times

- CMakeLists.txt
- config/cmake/Modules/VXLStandardOptions.cmake
This commit ensures that option VXL_USE_LFS is set during the first
configuration.
> COMP: VNL: Declare VXL_USE_LFS option after VCL_HAS_LFS is set

- core/vil/CMakeLists.txt
VXL doesn't build against all versions of DCMTK which makes the 'always use' approach VXL takes, problematic.
> Let users decide if they should include DCMTK.

- contrib/brl/bseg/sdet/sdet_third_order_edge_det.cxx
We're heavily developing the edge detectors,
and noticed this bug which was causing all edge orientations to be off.
This is tested and have been in agreeement with Yuliang Guo from LEMS/Brown,
the main researcher improving edge detection. I'm the main vxl maintainer of this edge feature system and a main user of it.
> Old fix for third order missing

- core/vidl/vidl_ffmpeg_pixel_format.cxx
Some systems define them, some do not. VXL always requires them.
> Make pixel formats conditional.

- core/vidl/vidl_image_list_ostream.cxx
- core/vil/vil_file_format.cxx
- core/vil/vil_file_format.h
- core/vil/vil_load.cxx
- core/vil/vil_new.cxx
We need to add custom, runtime generated image formats to the head of the vil_file_format_storage list. The return of a matching format happens first come, first served, which makes it impossible to use custom formats which extend, built-in types.
> Add runtime-loaded formats to the front so they can replace built-in formats.

- core/vnl/algo/vnl_lbfgs.cxx
This will prevent errors caused by returning an empty vector when starting at a minimum.
> Set initial value for best_x.

- core/vil/file_formats/vil_jpeg_compressor.cxx
This was needed to compile in recent OSX and GNU/LInux
(cherry picked from commit lemsvpe@7f5c3f793d0b0ac070f2bf7975e85e28b40d7a7f)
> VXL fix: VIL jpeg compress compile error

- core/vil1/file_formats/vil1_jpeg_compressor.cxx
Needed to compile vil1 in OSX and GNU/Linux (Ubuntu)
(cherry picked from commit lemsvpe@86fbdcebed27809a35997117aaa7cde5950128d8)
> VXL fix: VIL1 jpeg compress compile error

- v3p/tiff/test/CMakeLists.txt
- v3p/tiff/test/raw_decode.c
From the tiff 4.0.8 version of the test:
JPEG decoding is inherently inexact, so we can't test for exact
pixel values.  (Well, if we knew exactly which libjpeg version
we were using, and with what settings, we could expect specific
values ... but it's not worth the trouble to keep track of.)
Hence, use ranges of expected values.  The ranges may need to be
widened over time as more versions of libjpeg appear.
The ranges specified in the new test is EXACTLY the difference
between the previous failing test and previously required
exact values.
> BUG: Bad test for optionally built tiff_raw_decode

- core/vgui/CMakeLists.txt
- core/vgui/impl/gtk2/vgui_gtk2_adaptor.cxx
- core/vgui/impl/gtk2/vgui_gtk2_statusbar.h
- core/vgui/impl/gtk2/vgui_gtk2_window.cxx
These fixes are general and are needed for recent systems. Tested on Ubuntu 16.04 and 14.04
The new checks for GTKGL do exactly what they did before (so they are no harm to
the current system), but if these checks fail, they try to use pkgconfig in a seamless manner.
Fixes #384
> vgui: better GTK2 GTKGL detection

- core/vnl/algo/vnl_amoeba.h
- core/vnl/algo/vnl_complex_eigensystem.h
- core/vnl/algo/vnl_levenberg_marquardt.h
- core/vnl/algo/vnl_lsqr.h
- core/vnl/algo/vnl_real_eigensystem.h
- core/vnl/algo/vnl_sparse_lm.h
With visibility set to hidden applications can't link vnl_algo. This branch exports the classes that were failing for my applications. It's likely that a more comprehensive branch should follow which exports more of this libraries symbols.
> With hidden visibility propagated we need to export symbols

- core/vnl/algo/vnl_fft.h
When compiling ITK, low level fft functions were identified
that need to be externally visible.
The vnl_fft_gpfa must be visible in shared library builds.
> ENH: VNL_ALGO_EXPORT for advanced fft functions

- vcl/vcl_compiler_detection.h
Remove VXL_NOEXCEPT_EXPR, invalid in c++03.
Use empty `throw()` if noexcept specifier is not available.
Originated from ITK, see gerrit: http://review.source.kitware.com/22861
> COMP: Fix VXL_NOEXCEPT macro.

- contrib/brl/bseg/sdet/sdet_curvelet.h
- contrib/brl/bseg/sdet/sdet_curvelet_map.h
- contrib/brl/bseg/sdet/sdet_edgel.h
We had defs in the wrong place and with bad names.
(cherry picked from commit lemsvpe@9fddf6caee05c3837f5a9c1976ef8940ab1d1286)
> vxl: removed curvelet defs from edgel .h

- contrib/gel/vsol/vsol_curve_2d.h
This code isn't great, as it cites external classes, but it needs this fix since
dbsol_circ_arc_2d doesn't exist anymore in any recent active repository (this was an old LEMS/Brown class). Only bsold_circ_arc_2d does, and this is from the VXD library http://github.com/rfabbri/vxd.
(cherry picked from internal commit lemsvpe@daa998a4616ec57902357898b0ba30614016538e)
> VXL: dbsol to bsold_circ_arc in vsol curve

- vcl/vcl_compiler_detection.h
Compiler detection and feature support is performed with files generated with
the CMake macro `WriteCompilerDetectionHeader`. This macro generate a specific
header file for several supported compilers, including MSVC. However, for
MSVC, it only supports feature detection if MSVC >= 1600. If MSVC < 1600,
an error message is thrown instead of defaulting to default unknown compiler
which uses `__cplusplus` variable to configure supported features. In the case
of MSVC < 1600, it will default to a configuration with no C++11 support.
> BUG: Allow compilation of VNL with MSVC<1600

- core/vnl/algo/vnl_amoeba.h
This avoids the build error
d:\jenkins\workspace\itkwinvs12ninja\itk-src\modules\thirdparty\vnl\src\vxl\core\vnl\algo\vnl_amoeba.h(106)
: error C2487: 'default_verbose' : member of dll interface class may not be
declared with dll interface
when BUILD_SHARED_LIBS=ON and CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS:BOOL=ON are
set following the addition of the export macro to the vnl_amoeba class in
vxl/vxl@f0be54544acb75fb467abc67067a09647e288d0d.
> vnl: Do not use export macro in vnl_amoeba default_verbose

- contrib/brl/b3p/expatpp/expatpp.cpp
- contrib/brl/bbas/volm/volm_utils.cxx
- contrib/brl/bseg/boxm2/boxm2_scene.cxx
- contrib/brl/bseg/boxm2/cpp/algo/boxm2_refine_block_function_with_labels.cxx
- contrib/brl/bseg/boxm2/vecf/boxm2_vecf_articulated_scene.h
- contrib/mul/msm/tools/msm_reset_shape_modes.cxx
- core/vgl/vgl_affine_coordinates.hxx
- core/vil/file_formats/vil_viffheader.cxx
- core/vnl/vnl_math.cxx
- core/vnl/vnl_sample.cxx
- core/vpl/os_unix/vpl.cxx
- core/vul/vul_temp_filename.cxx
Some headers from C library were deprecated in C++ and are no longer
welcome in C++ codebases. Some have no effect in C++. For more details
refer to the C++ 14 Standard [depr.c.headers] section.
This patch replaces C standard library headers with their C++
alternatives and removes redundant ones.
> COMP: Use C++ headers over C headers

- core/vpl/os_unix/vpl.cxx
Keeping the C++ headers in the extern C block causes build failures with duplicate definitions of various functions.
> Move the c++ headers out of the extern C block

- contrib/brl/bbas/bvgl/bvgl_point_3d_cmp.h
- contrib/brl/bseg/boxm/basic/boxm_block_vis_graph_node.h
- contrib/mul/mbl/mbl_index_sort.h
- contrib/mul/mbl/mbl_stl.h
- contrib/mul/mbl/mbl_stl_pred.h
- core/vbl/vbl_batch_compact_multimap.h
- core/vbl/vbl_batch_multimap.h
- core/vnl/vnl_sparse_matrix.h
Both std::unary_function and std::binary_function are
deprecated since C++11 and removed without any replacement
from C++17. These base classes only contained typedefs that
were used solely by std::not2 (strictly superseeded by
std::not_fn in C++17).
As std::not2 is not used anywhere in VXL, this commit does
not break backward compatibility. In fact, the whole
purpose of this commit is C++17 forward compatibility,
which is important for projects written in C++17 that use
VXL and need to pass according compiler flags for binary
compatibility.
This will not make VXL fully compatible to C++17 but it is
enough regarding the components of VXL used by ITK.
> COMP: Remove inheritance from std::<un|bin>ary_function

- core/vnl/algo/tests/test_convolve.cxx
These throw intermittent false positives depending on build configuration.
Their value is less than the distraction this causes.
CC: @hjmjohnson @dstoup
> BUG: Remove vnl convolve timing tests

- core/vnl/vnl_math.h
This addresses errors such as:
ITK/Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_math.h:159:5: error: 'auto'
not allowed in function return type
With C++11 and ITK_WRAP_PYTHON=1 on macOS.
As discussed here:
http://stackoverflow.com/questions/9864125/c11-how-to-alias-a-function
`using` is preferred when the names are the same. Do explicit perfect
forwarding for cuberoot since the name changed.
CC: @hjmjohnson
> COMP: vnl_math perfect forward return type

- .travis.yml
Add an infrastructure to easily download and
use different versions of cmake.
> ENH: Update travis for flexible cmake versioning.

- core/vpdl/CMakeLists.txt
This branch fixes configure errors in projects which use the vpdl target. It isn't defined anymore after recent merges.
I am also curious why the vpdl library is a part of the experimental set. Not critical but since core_probability seems a viable and used library it makes sense to expose it better. I can push such a change if it's deemed acceptable.
> Set library properties for vpdl so target is defined

- core/vgl/vgl_point_2d.hxx
The stream started caring about < > but it wasn't testing the end for the end of stream before peeking again which was returning an invalid stream. I added treatment of < > the same as ( ).
I also reformatted the function so it was readable. Before, it was incredibly difficult to follow the flow.
> Fix a bug introduced in reading vgl_point_2d

- core/vpgl/algo/vpgl_optimize_camera.cxx
This fixes a bug in which vpgl_optimize_camera::opt_orient_pos_f() would occasionally return a camera with a negative focal length.
There was already a similar check within the cost function used by vpgl_optimize_camera::opt_orient_pos_cal, but not in the position and focal length only variant.
> add large penalty for negative focal length in camera optimization

- .gitignore
- CMakeLists.txt
- core/vgl/tests/test_pointset.cxx
- core/vgl/vgl_oriented_box_2d.hxx
- core/vgl/vgl_pointset_3d.h
- core/vil/io/Templates/vil_io_smart_ptr+vil_image_view_base-.cxx
- core/vil/tests/test_image_view_maths.cxx
vxl/core/vgl/algo/vgl_homg_operators_1d.hxx:100:59: warning: instantiation of variable 'vgl_homg<double>::infinity' required here, but no definition is available [-Wundefined-var-template]
vxl/core/vgl/algo/vgl_homg_operators_1d.hxx:100:59: warning: instantiation of variable 'vgl_homg<float>::infinity' required here, but no definition is available [-Wundefined-var-template]
vxl/core/vgl/algo/vgl_homg_operators_2d.hxx:138:25: warning: instantiation of variable 'vgl_homg<double>::infinity' required here, but no definition is available [-Wundefined-var-template]
vxl/core/vgl/algo/vgl_homg_operators_2d.hxx:138:25: warning: instantiation of variable 'vgl_homg<float>::infinity' required here, but no definition is available [-Wundefined-var-template]
vxl/core/vgl/tests/test_pointset.cxx:81:16: …
> COMP: Fix numerous compiler warnings

- core/vnl/tests/test_rational.cxx
- core/vnl/vnl_rational.cxx
- core/vnl/vnl_rational.h
Explicitly specify conversion types for all supported
integer types to resolve implicit ambigities.
vnl_fixed_matrix exposed ambiguities when the
the vnl_fixed_matrix element indexing is
changed to size_t.
> ENH: Provide vnl_rational support for size_t (aka unsigned long)

- contrib/brl/bseg/bstm_multi/basic/CMakeLists.txt
- contrib/brl/bseg/bstm_multi/basic/array_4d.cxx
- contrib/brl/bseg/bstm_multi/cpp/algo/tests/test_bstm_to_multi_bstm_block_function.cxx
- contrib/brl/bseg/bstm_multi/io/CMakeLists.txt
- contrib/brl/bseg/bstm_multi/io/not_empty.cxx
A newly added library had no source code
and resulted while trying to generate an
empy archive.  A stub file with
a trivial dummy function was created
to work around the build failure.
> BUG: New brl libraries had no source

- core/vnl/vnl_numeric_traits.cxx
vxl/core/vnl/vnl_numeric_traits.cxx:60:104:
warning: implicit conversion from 'int' to 'const char' changes value from 255 to -1 [-Wconstant-conversion]
> COMP: Silence int->char conversion warning

- core/vnl/vnl_math.h
Wrap std::isinf with perfect fowarding of arguments, but with a bool
return type.
The following test was failing on certain systems:
Test 185: isinf(ninf_d)
Due to a returned value of -1 and type int.
This has been seen with the following compilers:
g++ (GCC) 7.2.1 20170829 (Red Hat 7.2.1-1)
g++ (GCC) 6.3.1 20170216 (Red Hat 6.3.1-3)
> Ensure vnl_math::isinf returns a bool type

- CMakeLists.txt
- contrib/brl/bbas/bocl/tests/CMakeLists.txt
- contrib/brl/bbas/bsta/algo/tests/CMakeLists.txt
- contrib/brl/bbas/imesh/algo/tests/CMakeLists.txt
- contrib/brl/bseg/boct/tests/CMakeLists.txt
- contrib/brl/bseg/boxm/algo/sp/tests/CMakeLists.txt
- contrib/brl/bseg/boxm/tests/CMakeLists.txt
- contrib/brl/bseg/boxm2/cpp/algo/tests/CMakeLists.txt
- contrib/brl/bseg/boxm2/ocl/tests/CMakeLists.txt
- contrib/brl/bseg/boxm2/tests/CMakeLists.txt
- contrib/brl/bseg/bstm_multi/cpp/algo/tests/CMakeLists.txt
- contrib/brl/bseg/bvpl/tests/CMakeLists.txt
- contrib/cul/bundler/tests/CMakeLists.txt
A vxl option is added to controlling if longtime failing tests are run.
These failing tests make it difficult to identify new failures during
routine code maintenance.
> COMP: Disable long time failing tests

- core/vnl/CMakeLists.txt
Turning this flag on causes many instability problems on many platforms.
Test begin failing and segmentation faults occur in the core of ITK.
> ENH: Disabling VNL_CONFIG_ENABLE_SSE2 as a valid option

- core/vnl/vnl_c_na_vector.hxx
- core/vnl/vnl_c_vector.hxx
- core/vnl/vnl_sparse_matrix_linear_system.cxx
- core/vnl/vnl_vector_fixed_ref.hxx
vxl/core/vnl/vnl_c_na_vector.hxx:156:27: warning: type attributes ignored after type is already defined [-Wattributes]
vxl/core/vnl/vnl_c_vector.hxx:444:27: warning: type attributes ignored after type is already defined [-Wattributes]
vxl/core/vnl/vnl_c_vector.hxx:453:27: warning: type attributes ignored after type is already defined [-Wattributes]
vxl/core/vnl/vnl_sparse_matrix_linear_system.cxx:80:27: warning: type attributes ignored after type is already defined [-Wattributes]
vxl/core/vnl/vnl_sparse_matrix_linear_system.cxx:81:27: warning: type attributes ignored after type is already defined [-Wattributes]
vxl/core/vnl/vnl_vector_fixed_ref.hxx:127:27: warning: type attributes ignored after type is already defined [-Wattributes]
> COMP: Remove attribute ignored warning

- contrib/gel/vdgl/vdgl_digital_region.cxx
- contrib/gel/vdgl/vdgl_digital_region.h
- core/vbl/vbl_disjoint_sets.h
- core/vgl/vgl_fit_oriented_box_2d.h
- core/vgl/vgl_fit_oriented_box_2d.hxx
- core/vidl/vidl_ffmpeg_istream_v56.hxx
- core/vpgl/algo/vpgl_backproject_dem.cxx
Twiddle with the order of member initializers in a bunch of classes so that the order of initializers matches the order in which the compiler actually executes them. This avoids tripping `-Wreorder` warnings. (This isn't all of them, but it covers ones that I was tripping.)
> Fix initialization order

- core/vidl/Templates/vil_smart_ptr+vidl_frame-.cxx
- core/vidl/Templates/vil_smart_ptr+vidl_istream-.cxx
- core/vidl/Templates/vil_smart_ptr+vidl_ostream-.cxx
- core/vidl/vidl_convert.h
- core/vidl/vidl_ffmpeg_istream.h
- core/vidl/vidl_ffmpeg_ostream.h
- core/vidl/vidl_ffmpeg_ostream_params.h
- core/vidl/vidl_frame.h
- core/vidl/vidl_image_list_istream.h
- core/vidl/vidl_image_list_ostream.h
- core/vil/vil_smart_ptr.hxx
Add missing export decoration so that vidl is usable when hidden visibility is enabled.
As part of this, fiddle with `VIL_SMART_PTR_INSTANTIATE` so that the instantiations can be export-decorated... on not-Windows. Exporting template instantiations on Windows is an ugly mess for which we have no machinery whatsoever at present. (At least things should be no more broken than already...)
> Fix vidl visibility

- contrib/mul/clsfy/Templates/mbl_cloneables_factory+clsfy_builder_1d-.cxx
- contrib/mul/clsfy/Templates/mbl_cloneables_factory+clsfy_builder_base-.cxx
- contrib/mul/mbl/CMakeLists.txt
- contrib/mul/mbl/mbl_cloneables_factory.h
- contrib/mul/mbl/mbl_cloneables_factory_def.h
- contrib/mul/mbl/tests/test_cloneables_factory.cxx
- contrib/mul/mcal/Templates/mbl_cloneables_factory+mcal_component_analyzer-.cxx
- contrib/mul/mcal/Templates/mbl_cloneables_factory+mcal_single_basis_cost-.cxx
- contrib/mul/mfpf/Templates/mbl_cloneables_factory+mfpf_point_finder-.cxx
- contrib/mul/mfpf/Templates/mbl_cloneables_factory+mfpf_point_finder_builder-.cxx
- contrib/mul/mfpf/Templates/mbl_cloneables_factory+mfpf_region_definer-.cxx
- contrib/mul/mfpf/Templates/mbl_cloneables_factory+mfpf_vec_cost_builder-.cxx
- contrib/mul/mipa/Templates/mbl_cloneables_factory+mipa_vector_normaliser-.cxx
- contrib/mul/mmn/Templates/mbl_cloneables_factory+mmn_solver-.cxx
- contrib/mul/msm/Templates/mbl_cloneables_factory+msm_aligner-.cxx
- contrib/mul/msm/Templates/mbl_cloneables_factory+msm_param_limiter-.cxx
- contrib/mul/vpdfl/Templates/mbl_cloneables_factory+vpdfl_builder_base-.cxx
The use of the MBL_CLONEABLES_FACTORY_INSTANTIATE() macro after the
implementation of mbl_cloneables_factory was causing the compilation error
"error: explicit specialization of 'objects' after instantiation". Breaking
the definition and implementation into two files fixes this issue.
> mbl_cloneables_factory: split into def and implementaiton

- config/cmake/Modules/FindClipper.cmake
- core/vgl/vgl_clip.hxx
As per commits 90d6285 and 206f426, clipper.h was renamed to clipper.hxx.  Change remaining clipper.h references to clipper.hxx.
> Update remaining references to clipper.h

- core/vil/file_formats/vil_tiff.cxx
- core/vil/file_formats/vil_tiff_header.cxx
Add read-only planar TIFF format (option 2 as per [here](https://www.awaresystems.be/imaging/tiff/tifftags/planarconfiguration.html)) to vil_tiff.  
Authored by @mundyj.
> Planar format to vil_tiff

- CMakeLists.txt
Excerpt from configure log with CMake 3.12.0:
Looking for srand48
Looking for srand48 - found
Check if the system is big endian
Searching 16 bit integer
Looking for sys/types.h
CMake Warning (dev) at /usr/local/share/cmake-3.12/Modules/CheckIncludeFile.cmake:70 (message):
Policy CMP0075 is not set: Include file check macros honor
CMAKE_REQUIRED_LIBRARIES.  Run "cmake --help-policy CMP0075" for policy
details.  Use the cmake_policy command to set the policy and suppress this
warning.
CMAKE_REQUIRED_LIBRARIES is set to:
;m
For compatibility with CMake 3.11 and below this check is ignoring it.
Call Stack (most recent call first):
/usr/local/share/cmake-3.12/Modules/CheckTypeSize.cmake:225 (check_include_file)
/usr/local/share/cmake-3.12/Modules/TestBigEndian.cmake:32 (CHECK_TYPE_SIZE) …
> COMP: fixing warning CMAKE_REQUIRED_LIBRARIES is set to: ;m

- config/cmake/config/VXLIntrospectionConfig.cmake
Complete error message as it appears in ITK upon
first configuration in a clean build directory:
CMake Warning (dev) at /Applications/CMake.app/Contents/share/cmake-3.12/Modules/CheckIncludeFile.cmake:70 (message):
Policy CMP0075 is not set: Include file check macros honor
CMAKE_REQUIRED_LIBRARIES.  Run "cmake --help-policy CMP0075" for policy
details.  Use the cmake_policy command to set the policy and suppress this
warning.
CMAKE_REQUIRED_LIBRARIES is set to:
;m
For compatibility with CMake 3.11 and below this check is ignoring it.
Call Stack (most recent call first):
/Applications/CMake.app/Contents/share/cmake-3.12/Modules/CheckTypeSize.cmake:225 (check_include_file)
/Applications/CMake.app/Contents/share/cmake-3.12/Modules/TestBigEndian.cmake:32 (CHECK_TYPE_SIZE) …
> COMP: proper fix of warning regarding CMP0075

- CMakeLists.txt
- contrib/mul/mbl/CMakeLists.txt
- contrib/mul/mcal/CMakeLists.txt
- contrib/mul/msm/CMakeLists.txt
- contrib/mul/vimt/CMakeLists.txt
- contrib/mul/vimt/algo/CMakeLists.txt
- core/examples/CMakeLists.txt
- core/examples/merge_libs/CMakeLists.txt
- core/examples/merge_libs/merging_libraries.txt
- core/examples/merge_libs/test_link_all_vxl.cxx
- core/vbl/CMakeLists.txt
- core/vbl/io/CMakeLists.txt
- core/vgl/CMakeLists.txt
- core/vgl/algo/CMakeLists.txt
- core/vgl/io/CMakeLists.txt
- core/vgl/xio/CMakeLists.txt
- core/vil/CMakeLists.txt
- core/vil/algo/CMakeLists.txt
- core/vil/io/CMakeLists.txt
- core/vnl/CMakeLists.txt
- core/vnl/algo/CMakeLists.txt
- core/vnl/io/CMakeLists.txt
- core/vnl/xio/CMakeLists.txt
- core/vpl/CMakeLists.txt
- core/vsl/CMakeLists.txt
- core/vul/CMakeLists.txt
- core/vul/io/CMakeLists.txt
- v3p/netlib/CMakeLists.txt
- vcl/CMakeLists.txt
A number of people have asked whether it is possible to create a single library file containing VXL, rather than the multiple individual libraries that are the default.
CMake does provide a mechanism for this, using OBJECT libraries.
See: https://gitlab.kitware.com/cmake/community/wikis/doc/tutorials/Object-Library
To use this, one has to add a bit of extra code to each library CMakeLists.txt. 
So for vbl, one adds:
if (VXL_BUILD_OBJECT_LIBRARIES)
add_library(vbl-obj OBJECT ${vbl_sources})
endif ()
The VXL_BUILD_OBJECT_LIBRARIES is a new flag (default value OFF), added to the root CMakeLists.txt
One can then create a single library from multiple library sources using a CMake command like this:
add_library(all_vxl_libs $<TARGET_OBJECTS:vcl-obj>
$<TARGET_OBJECTS:vsl-obj> …
> Options to help create a single VXL library file.

- v3p/netlib/v3p_f2c.h
`register` is an optional hint to the compiler to put a variable in a
register.
This addresses the warning:
/home/matt/src/vxl/v3p/netlib/v3p_f2c.h:29:14: warning: 'register'
storage class specifier is deprecated and incompatible with C++17
[-Wdeprecated-register]
> COMP: Remove `register` keyword from v3p_f2c.h

- CMakeLists.txt
To address in the ITKExamples Superbuild:
CMake Warning (dev) at Modules/ThirdParty/VNL/src/vxl/config/cmake/Modules/FindZLIB.cmake:20 (find_package):
Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
CMake variable ZLIB_ROOT is set to:
/.../ITKEx-bld/zlib-install
For compatibility, CMake is ignoring the variable.
Call Stack (most recent call first):
> COMP: Set CMP0074 to NEW

- contrib/brl/bbas/bmsh3d/CMakeLists.txt
- contrib/prip/vdtop/CMakeLists.txt
A few tests were still being setup with `BUILD_TESTING` off
> Fix missing gates for BUILD_TESTING

- config/cmake/config/vxl_platform_tests.cxx
This issue found with permissive- by msvc on windows.
The default value of "foo" is not allowed to change.
resolves #480 issue
> BUG: Function signature must match default value

- contrib/brl/bbas/brad/CMakeLists.txt
- contrib/brl/bseg/betr/CMakeLists.txt
- contrib/brl/bseg/brip/CMakeLists.txt
- contrib/brl/bseg/bsgm/CMakeLists.txt
- contrib/brl/bseg/bstm/pro/CMakeLists.txt
- contrib/brl/bseg/bstm_multi/CMakeLists.txt
There were two unrelated problems that caused
shared library building with BRL libraries.
1) Two submodules that were not used external to the unit test for
those submodules had untested function references (OK for static libs,
but caused linkage failure for shared libs).
contrib/brl/bseg/bstm_multi/pro unused/incomplete lib not compiled
contrib/brl/bseg/bstm_multi/cpp unused/incomplete lib not compiled
2) A circular dependancy where the bbrad and brip libraries depended on each other
unnecessarily.  By forcing brip to depend on brad only (i.e. removing the dependancy
from brad to brip) and adding a few missing library dependancies, the
shared library builds of BRL are working agian.
Resolves #508
> COMP: BRL shared lib inconsistency

- core/vbl/vbl_bounding_box.h
These false postives are due to the fact that the functions are only
called for the appropriate dimension type.
> COMP: Silence warnings about array bound overrun

- config/cmake/config/vxl_utils.cmake
- core/vnl/Templates/vnl_complex_ops+double-.cxx
- core/vnl/algo/vnl_fft_base.h
- core/vnl/algo/vnl_svd.h
- core/vnl/vnl_trace.h
- v3p/netlib/triangle.c
If VXL is modified, the incremental build becomes sequential during
compilation of VXL.  This enables object-level compile parallelism
in VXL libraries.
> ENH: compile VXL in parallel on Visual Studio

- core/vnl/vnl_matrix.h
- core/vnl/vnl_matrix.hxx
Supporting WINDOWS_EXPORT_ALL_SYMBOLS needed the definition
in one place to avoid a duplicate symbol build failure.
Also remove extra space between comments and code that
artificially separated the desription from the code.
> ENH: Move definition of vnl_matrix to .hxx

- contrib/brl/bseg/boxm2/vecf/view/boxm2_ocl_articulated_render_tableau.cxx
- contrib/brl/bseg/boxm2/view/boxm2_ocl_change_tableau.cxx
- contrib/brl/bseg/boxm2/view/boxm2_ocl_render_tableau.cxx
- contrib/brl/bseg/boxm2/view/boxm2_ocl_render_trajectory_tableau.cxx
- contrib/brl/bseg/brec/pro/tests/test_brec_create_mog_image_process.cxx
- contrib/brl/bseg/bstm/view/bstm_ocl_multi_render_tableau.cxx
- contrib/brl/bseg/bstm/view/bstm_ocl_render_tableau.cxx
- contrib/brl/bseg/bvxm/pro/tests/test_bvxm_rpc_registration_process.cxx
- contrib/brl/bseg/bvxm/pro/tests/test_bvxm_update_lidar_process.cxx
2nd arguments to brdb_database_manager->select operations must be wrapped in std::move, as a unique_ptr cannot be copied.
> unique_ptr for brdb_database_manager

- contrib/brl/bbas/bgui3d/bgui3d_tableau.cxx
- contrib/brl/bbas/bgui3d/bgui3d_viewer_tableau.cxx
Remaining case of changing null pointer constants (eg. NULL, 0) to use the new C++11 nullptr keyword.
(cherry picked from commit lemsvpe@287ab89282f57af6636cb4158dc46a21e69d8f0b)
> COMP to VXL: nullptr instead of 0 or NULL @ bgui3d

- .circleci/config.yml
Update circleci configuration with C+11 requirement.  Also submit circleci build results to open.cdash.org only for master branch (not experimental/development branches).
> circleci update (c++11, cdash on master only)

- contrib/brl/bbas/imesh/algo/imesh_imls_surface.cxx
(cherry picked from commit lemsvpe@44421a58010410cf6ec4dd514f109d51fbd26df9)
This solved some duplicate symbol errors in some compilers (tested with GCC 5.5.0 under Mac OS)
> TO VXL: COMP: duplicate instantiation removed

- core/vil/file_formats/vil_geotiff_header.cxx
For compatibility with WGS84 geotiff created by GDAL, check "linear units" parameter on a geotiff only when present.
> GDAL geotiff compatibility

- contrib/brl/bbas/volm/pro/processes/volm_combine_height_map_process.cxx
- contrib/brl/bpro/core/bbas_pro/CMakeLists.txt
- contrib/brl/bpro/core/bbas_pro/bbas_processes.h
- contrib/brl/bpro/core/bbas_pro/bbas_register.cxx
- contrib/brl/bpro/core/bbas_pro/processes/bpgl_heightmap_from_disparity_process.cxx
- contrib/brl/bpro/core/pyscripts/bbas_adaptor.py
- contrib/brl/bpro/core/pyscripts/bsgm_adaptor.py
- contrib/brl/bpro/core/pyscripts/vpgl_adaptor.py
- contrib/brl/bpro/core/vpgl_pro/processes/vpgl_rectify_images_process.cxx
- contrib/brl/bseg/bsgm/pro/processes/bsgm_matching_stereo_process.cxx
* bpgl_heightmap_from_disparity python adaptor
* volm_combine_height_map_process.cxx: direct threshold for median filter, return "-9999.0" as invalid value
* bsgm_matching_stereo_process.cxx: optional text file output
* vpgl_rectify_images_process accepts dispairty image directly
> heightmap_from_disparity adaptor

- core/vpgl/algo/tests/CMakeLists.txt
- core/vpgl/algo/tests/test_camera_homographies.cxx
- core/vpgl/algo/tests/test_driver.cxx
- core/vpgl/algo/vpgl_camera_homographies.cxx
- core/vpgl/tests/test_proj_camera.cxx
- core/vpgl/vpgl_proj_camera.h
- core/vpgl/vpgl_proj_camera.hxx
**vpgl_camera_homographies:**
new unit test revealed necessary fix for vpgl_camera_homographies calculation
**vpgl_proj_camera**
- is_canonical: is the projective camera matrix of the form [I | 0]
- unit test for is_canonical
- update vpgl_PROJ_CAMERA_INSTANTIATE
- additional updates (e.g., const args, spacing change)
> vpgl_camera_homographies & vpgl_proj_camera

- core/vpgl/CMakeLists.txt
- core/vpgl/Templates/vpgl_affine_tri_focal_tensor+double-.cxx
- core/vpgl/Templates/vpgl_affine_tri_focal_tensor+float-.cxx
- core/vpgl/Templates/vpgl_tri_focal_tensor+double-.cxx
- core/vpgl/Templates/vpgl_tri_focal_tensor+float-.cxx
- core/vpgl/algo/tests/CMakeLists.txt
- core/vpgl/algo/tests/test_affine_tensor_transfer.cxx
- core/vpgl/algo/tests/test_driver.cxx
- core/vpgl/algo/vpgl_camera_convert.cxx
- core/vpgl/tests/CMakeLists.txt
- core/vpgl/tests/test_affine_tri_focal_tensor.cxx
- core/vpgl/tests/test_driver.cxx
- core/vpgl/tests/test_tri_focal_tensor.cxx
- core/vpgl/vpgl_affine_camera.h
- core/vpgl/vpgl_affine_camera.hxx
- core/vpgl/vpgl_affine_tri_focal_tensor.h
- core/vpgl/vpgl_affine_tri_focal_tensor.hxx
- core/vpgl/vpgl_tri_focal_tensor.h
- core/vpgl/vpgl_tri_focal_tensor.hxx
New code for vpgl trifocal tensor
- trifocal tensor is a generalization of the fundamental matrix in three views.
- New code offers both projective and affine trifocal tensors.
- Unit tests included
- other changes to support trifocal tensors
> Trifocal tensor

- core/vpgl/algo/tests/test_ray.cxx
- core/vpgl/algo/vpgl_ray.cxx
- core/vpgl/algo/vpgl_ray.h
- core/vpgl/file_formats/vpgl_geo_camera.cxx
- core/vpgl/vpgl_lvcs.h
vpgl updates:
- retrieve geotiff header only once during vpgl_geo_camera
- add vpgl_ray method for the affine camera
- default vpgl_lvcs destructor
> vpgl: geo cam, affine cam, lvcs

- contrib/brl/bbas/brad/brad_image_metadata.cxx
- contrib/brl/bbas/brdb/brdb_query.h
- contrib/brl/bbas/bwm/bwm_observer_img.cxx
- contrib/brl/bbas/bwm/bwm_observer_img.h
- contrib/brl/bbas/bwm/bwm_observer_vgui.cxx
- contrib/brl/bbas/bwm/bwm_popup_menu.cxx
- contrib/brl/bbas/bwm/bwm_tableau_img.cxx
- contrib/brl/bbas/bwm/bwm_tableau_img.h
- contrib/brl/bbas/imesh/CMakeLists.txt
- contrib/brl/bpro/core/brad_pro/brad_processes.h
- contrib/brl/bpro/core/brad_pro/brad_register.cxx
- contrib/brl/bpro/core/brad_pro/processes/brad_get_image_footprint_process.cxx
- contrib/brl/bpro/core/bvgl_pro/bvgl_processes.h
- contrib/brl/bpro/core/bvgl_pro/bvgl_register.cxx
- contrib/brl/bpro/core/bvgl_pro/processes/bvgl_geo_index_extent_process.cxx
- contrib/brl/bpro/core/bvgl_pro/processes/bvgl_geo_index_region_distance_process.cxx
- contrib/brl/bpro/core/bvgl_pro/processes/bvgl_geo_index_region_overlap_process.cxx
- contrib/brl/bpro/core/pyscripts/brad_adaptor.py
- contrib/brl/bpro/core/pyscripts/bvgl_adaptor.py
- contrib/brl/bpro/core/pyscripts/vpgl_adaptor.py
- contrib/brl/bpro/core/vpgl_pro/processes/vpgl_geo_camera_processes.cxx
- contrib/brl/bpro/core/vpgl_pro/processes/vpgl_print_rational_camera_process.cxx
- contrib/brl/bpro/core/vpgl_pro/vpgl_processes.h
- contrib/brl/bpro/core/vpgl_pro/vpgl_register.cxx
- contrib/brl/bseg/bvxm/pro/processes/bvxm_create_scene_xml_process.cxx
- contrib/brl/bseg/bvxm/pro/processes/bvxm_create_scene_xml_process.h
- contrib/brl/bseg/bvxm/pyscripts/bvxm_adaptor.py
Various updates to BRL contrib libraries and adaptors:
- brdb_query fix compile error on VS2017
- bwm update for new line options
- remove dependency on brdb by imesh lib
- vpgl_adaptor: add vpglGetGeoTransform, exception checks
- brl, vpgl_geo_camera_processes - appropriate half-pixel offset in TFW file
- brl vpgl_adaptor - print out rational camera
- brad_adaptor - add process to get image footprint from metadata
- bvxm_adaptor - create_scene_xml_large_scale_process, enlarge the scene region based on given expansion size in meter
- new bvgl python processes for geo_index manipulation
- brl adaptor bugfix - clean database outputs in bvgl_adaptor and bvxm_adaptor
- brad_image_metadata - lat/lon from TXT metadata file only when present in TXT file
- brad_image_metadata - fix bug when …
> BRL contrib updates

- core/vil/file_formats/vil_nitf2_field_definition.cxx
Bugfix for vil_nitf2_field_definition - disambiguate arguments from class members
Constructor input argument names and class member names are identical, and it is ambiguous which `tag` (argument or class member) is testing during `assert(!tag.empty()...`
On windows, input argument is tested, but input argument is always empty after the `std::move` introduced by 5922e9d and 68e52b1.
To fix, disambiguate argument names from class member names.  `assert` statement s now explicitly testing class member.
> bugfix vil_nitf2_field_definition - disambiguate arguments from class members

- core/vpgl/algo/CMakeLists.txt
- core/vpgl/algo/tests/CMakeLists.txt
- core/vpgl/algo/tests/test_camera_compute.cxx
- core/vpgl/algo/tests/test_driver.cxx
- core/vpgl/algo/tests/test_fit_rational_cubic.cxx
- core/vpgl/algo/vpgl_camera_compute.cxx
- core/vpgl/algo/vpgl_camera_compute.h
- core/vpgl/algo/vpgl_fit_rational_cubic.cxx
- core/vpgl/algo/vpgl_fit_rational_cubic.h
`vpgl_rational_camera_compute::compute` - new vpgl/algo capability to compute a rational camera model from world-to-image correspondences.  Supporting code and unit tests also included.
> vpgl_rational_camera_compute

- contrib/brl/bbas/bil/algo/tests/test_bil_detect_ridges.cxx
- contrib/brl/bbas/bpgl/bpgl_comp_rational_camera.hxx
- contrib/brl/bbas/brad/brad_image_metadata.cxx
- contrib/brl/bbas/brad/brad_image_metadata.h
- contrib/brl/bpro/core/vpgl_pro/processes/vpgl_compute_affine_from_rational_process.cxx
- contrib/brl/bpro/core/vpgl_pro/processes/vpgl_rectify_images_process.cxx
- `vpgl_compute_affine_from_rational_process` - use `vpgl_affine_camera_convert::convert`
- `vpgl_construct_height_map_process`
- z search space at half voxel_size only for voxel_size above 1 meter
- OpemMP parallelized
- `test_bil_detect_ridges` - directly ensure test data presence
- `bpgl_comp_rational_camera` - clean up stdout (remove error statement)
- `brad_image_metadata` - add gain/offset/solar_irrad parsing directly from IMD file
> More BRL contrib updates

- v3p/tiff/tif_win32.c
Fix malloc problem in v3p tiff for Windows - required explicit inclusion of stdlib and additional __inline.
> v3p tiff for Windows 

- contrib/brl/bbas/bpgl/algo/bpgl_fm_compute_affine_ransac.cxx
- contrib/brl/bbas/bpgl/algo/bpgl_fm_compute_affine_ransac.h
- contrib/brl/bbas/bpgl/algo/tests/test_fm_compute.cxx
- core/vpgl/tests/CMakeLists.txt
- core/vpgl/tests/test_affine_fundamental_matrix.cxx
- core/vpgl/tests/test_driver.cxx
- core/vpgl/vpgl_affine_fundamental_matrix.h
- core/vpgl/vpgl_affine_fundamental_matrix.hxx
- core/vpgl/vpgl_affine_tri_focal_tensor.h
- core/vpgl/vpgl_affine_tri_focal_tensor.hxx
vpgl_affine_fundamental_matrix update:
- add constructor from 2 affine cameras
- adopt Hartly and Zisserman convention for internal a-e representation
- additional function overloads
- new tests
Additional updates to ignore internal vpgl_affine_fundamental_matrix representation 
- vpgl_affine_tri_focal_tensor 
- BRL bpgl_fm_compute_affine_ransac (and related test update)
> vpgl_affine_fundamental_matrix

- contrib/brl/bbas/bpgl/algo/tests/test_camera_from_box.cxx
- core/vpgl/tests/test_affine_camera.cxx
- core/vpgl/vpgl_affine_camera.h
- core/vpgl/vpgl_affine_camera.hxx
Improvements to vpgl_affine_camera
- improve backprojection via direct ray construction
- ray_dir accessor
- postmultiply by translation
- new related tests
- related change to BRL bpgl test_camera_from_box - backproject via ray instead of line_3d_2p
> vpgl_affine_camera

- vcl/tests/test_preprocessor.cxx
vcl/tests/test_preprocessor.cxx:37:11: error:
'VXL_COMPILER_IS_MIPSpro' was not declared in this scope
cmake commit beb991110d84e9c0a6b1339e22fa98284b08bac9
Author: Brad King <brad.king@kitware.com>
Date:   Fri Jan 11 13:50:46 2019 -0500
Remove now-unused code once used on IRIX
We dropped support for IRIX as a host platform long ago.
Remove some leftover code.
> COMP: Remove test for MIPSPro support by cmake

- config/cmake/Modules/NewCMake/FindECW.cmake
- core/vil/CMakeLists.txt
- v3p/j2k/CMakeLists.txt
VXL_USE_ECW option to control check/inclusion of ECW J2K libraries (native or V3P if available)
- VXL_USE_ECW option in vil CMakeLists.txt
- VXL_USE_ECW is false by default, as the library is not typically available
- additional tab indent of FindECW.cmake
> VXL_USE_ECW option

- config/cmake/Modules/FindGEOTIFF.cmake
- core/vil/CMakeLists.txt
Remove redundant find_path statement from FindGEOTIFF (path was already checked for existence, find_path is unnecessary).  Also correct "VXL_USE_GEOTFIF" test and add message to vil cmake that geotiff was discovered.
> remove redundant find_path from FindGEOTIFF

- core/vpgl/CMakeLists.txt
- core/vpgl/file_formats/vpgl_nitf_rational_camera.cxx
- core/vpgl/file_formats/vpgl_nitf_rational_camera.h
- core/vpgl/tests/test_local_rational_camera.cxx
- core/vpgl/tests/test_rational_camera.cxx
- core/vpgl/vpgl_local_rational_camera.h
- core/vpgl/vpgl_local_rational_camera.hxx
- core/vpgl/vpgl_rational_camera.cxx
- core/vpgl/vpgl_rational_camera.h
- core/vpgl/vpgl_rational_camera.hxx
`vpgl_rational_camera` refactoring
- input/output coefficient order schema that differs from VXL internal order now encapsulated in one place - see new `vpgl_rational_order` scoped enumeration
- new `read*` methods for easier overloading with additional file validation
- general refactoring (review, cleanup, & update)
- refactor derived classes (`vpgl_local_rational_camera` and `vpgl_nitf_rational_camera`) for compatibility with base class
- additional `project` tests
> vpgl_rational_camera refactoring

- core/vnl/tests/test_drand48.cpp
- core/vnl/tests/test_matrix_exp.cxx
The path to headers for the tests should be
consistently relative to the core directory.
> COMP: Improve header search robustness

- core/vpgl/algo/CMakeLists.txt
- core/vpgl/algo/tests/CMakeLists.txt
- core/vpgl/algo/tests/test_camera_compute.cxx
- core/vpgl/algo/tests/test_driver.cxx
- core/vpgl/algo/tests/test_equi_rectification.cxx
- core/vpgl/algo/vpgl_affine_rectification.cxx
- core/vpgl/algo/vpgl_affine_rectification.h
- core/vpgl/algo/vpgl_camera_compute.cxx
- core/vpgl/algo/vpgl_equi_rectification.cxx
- core/vpgl/algo/vpgl_equi_rectification.h
`vpgl_equi_rectification` - Rectify a pair of images by applying equal and opposite warp transforms to each image, thus reducing scale distortion during rectification.  Includes bugfix for `vpgl_affine_rectification` (vector should be of length 3).
`vpgl_affine_camera_compute` compute viewing distance, additional test
> vpgl_equi_rectification

- contrib/brl/bbas/bpgl/algo/CMakeLists.txt
- contrib/brl/bbas/bpgl/algo/bpgl_rectify_affine_image_pair.cxx
- contrib/brl/bbas/bpgl/algo/bpgl_rectify_affine_image_pair.h
- contrib/brl/bbas/bpgl/algo/tests/CMakeLists.txt
- contrib/brl/bbas/bpgl/algo/tests/test_driver.cxx
- contrib/brl/bbas/bpgl/algo/tests/test_rectify_affine_image_pair.cxx
- contrib/brl/bpro/core/bbas_pro/bbas_processes.h
- contrib/brl/bpro/core/bbas_pro/bbas_register.cxx
- contrib/brl/bpro/core/bbas_pro/processes/bpgl_rectify_affine_image_pair_process.cxx
- contrib/brl/bpro/core/pyscripts/bbas_adaptor.py
- contrib/brl/bseg/bsgm/CMakeLists.txt
- contrib/brl/bseg/bsgm/Templates/bsgm_align_pointsets_3d+double-.cxx
- contrib/brl/bseg/bsgm/Templates/bsgm_align_pointsets_3d+float-.cxx
- contrib/brl/bseg/bsgm/Templates/bsgm_prob_align_pointsets_3d+double-.cxx
- contrib/brl/bseg/bsgm/Templates/bsgm_prob_align_pointsets_3d+float-.cxx
- contrib/brl/bseg/bsgm/bsgm_align_pointsets_3d.h
- contrib/brl/bseg/bsgm/bsgm_align_pointsets_3d.hxx
- contrib/brl/bseg/bsgm/bsgm_pairwise_dsm.cxx
- contrib/brl/bseg/bsgm/bsgm_pairwise_dsm.h
- contrib/brl/bseg/bsgm/bsgm_prob_align_pointsets_3d.h
- contrib/brl/bseg/bsgm/bsgm_prob_align_pointsets_3d.hxx
- contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.cxx
- contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.h
BRL new features & bugfixes:
- brl/bsgm: align 3D pointsets (directly & using probability scalar)
- bugfix - correct test references for brl/bpgl/algo
- brl/bpgl/algo: rectify affine image pair using vpgl_equi_rectification
- bpgl_rectify_affine_image_pair python adaptor
- brl/bsgm: pairwise digital surface model from rectified images
> Contrib BRL - align, rectify, surfaces

- CMakeLists.txt
- core/vil/CMakeLists.txt
Without VXL_USE_GEOTIFF set to true, the v3p geotiff library will not be built.
However, core/vil/CMakeLists.txt is processed after v3p by cmake, so it's too late to set VXL_USE_GEOTIFF there.
Prior to this change, vxl would fail to build on my mac without manually setting VXL_USE_GEOTIFF on the cmake command line.
> Move VXL_USE_GEOTIFF option up to top level

- core/vpgl/algo/vpgl_camera_convert.cxx
fixes a bug in vpgl_affine_camera_convert::convert() (depth and height swapped) that could potentially lead to subpar cameras due to poorly sampled points.
> bugfix: depth and height were swapped.

- core/vpgl/algo/tests/test_affine_tensor_transfer.cxx
- core/vpgl/vpgl_affine_tri_focal_tensor.hxx
The test_affine_tensor_transfer test in vpgl/algo was spuriously failing ~1% of the time due to some non-determinism inside vpgl_affine_camera_convert.  The failing tests were due to some very strict tolerances that are relaxed slightly by this changeset.
> Fix vpgl algo test failures

- vcl/CMakeLists.txt
The vcl_msvc_warnings.h file was missing from the install
process.  This only affects MSVC installed builds.
> COMP: Missing file for install of vxl

- contrib/brl/bpro/bprb/bprb_batch_process_manager.h
- contrib/brl/bpro/bpro_batch/bpro_batch.cxx
- contrib/brl/bpro/bpro_batch/bpro_defs.h
- contrib/brl/bpro/core/vpgl_pro/processes/vpgl_crop_img_using_3d_box_process.cxx
- contrib/brl/bseg/brip/brip_roi.cxx
- core/vpgl/vpgl_rational_camera.hxx
CORE VPGL:
- minor change to vpgl_rational_camera print function, increasing precision of output
CONTRIB BRL:
- brip_roi - favor unsigned->int casting (likely safer, as the int values could be negative while the unsigned values are likely to be relatively small)
- adaptor process bugfix - allow rational_cam to have non-integer offset values during crop operation 
- adaptor process - get adaptor verbosity
> rational cam print & contrib update

- core/vgl/tests/test_closest_point.cxx
- core/vgl/vgl_infinite_line_3d.hxx
Fixing a constructor that did not copy all fields and caused issues with line direction. Added a test case that would fail without the fix.
> vgl_infinite_line_3d constructor fix

- core/vpgl/vpgl_lvcs.cxx
- core/vpgl/vpgl_lvcs.h
vpgl_lvcs is derived from vbl_ref_count, thus the destructor is implicitly virtual. As the destructor is the only virtual function in vpgl_lvcs, DO NOT define inline; the destructor must be the "key function" (first non-inline, non-pure, virtual function).
Defining in cxx protects against "undefined reference to vtable" linking errors.
https://gcc.gnu.org/wiki/VerboseDiagnostics#missing_vtable
> Move vpgl_lvcs destructor to cxx file

- contrib/brl/bpro/core/pyscripts/vpgl_adaptor.py
- contrib/brl/bpro/core/vpgl_pro/processes/vpgl_isfm_rational_camera_seed_process.cxx
- contrib/brl/bpro/core/vpgl_pro/processes/vpgl_isfm_rational_camera_with_initial_process.cxx
update BRL python isfm adaptor processes
- make isfm adaptor process accept 3D region directly
- eliminate requirement for ASTER DEM ingestion
- general code cleanup (e.g., removing #if statements)
> CONTRIB BRL: update isfm python adaptors

- contrib/brl/bpro/core/bbas_pro/processes/bbas_camera_angles_process.cxx
- contrib/brl/bpro/core/vpgl_pro/processes/vpgl_get_backproject_ray_process.cxx
- contrib/brl/bpro/core/vpgl_pro/processes/vpgl_rational_camera_process.cxx
- contrib/brl/bseg/bvxm/pro/processes/bvxm_detect_scale_process.cxx
- contrib/brl/bseg/bvxm/pro/processes/bvxm_rpc_registration_process.cxx
- core/vpgl/algo/tests/test_camera_homographies.cxx
- core/vpgl/algo/vpgl_backproject.cxx
- core/vpgl/algo/vpgl_backproject.h
- core/vpgl/algo/vpgl_camera_convert.cxx
- core/vpgl/algo/vpgl_invmap_cost_function.cxx
- core/vpgl/algo/vpgl_invmap_cost_function.h
- core/vpgl/algo/vpgl_ray.cxx
Unify vpgl_backproject::bproj_plane() interface to accept references.
- Previously, the generic_camera version accepted the camera as a reference, and the basic version accepted the camera as a pointer.  With the new unified interface, overloading can be used to choose the correct implementation.
- The vgl wrapper interface is converted to a function template so that it doesn't need to be re-written for every camera type overload.
- Only one implementation of vpgl_backproject::direction_to_camera() is needed, as overloading will now be used to call the correct bproj_plane().
- Add a new bproj_plane() overload for projective cameras.
> Unify bproj plane interface

- contrib/brl/bpro/core/vpgl_pro/processes/vpgl_get_backproject_ray_process.cxx
- core/vpgl/algo/vpgl_backproject.h
external (or uncompiled internal) code could be broken by #635 .  This PR adds two simple wrapper functions with the previous APIs.
> add wrapper function to keep backwards compatibility with previous bproj_plane() API

- CMakeLists.txt
- core/vpgl/vpgl_local_rational_camera.hxx
- core/vpgl/vpgl_lvcs.cxx
- core/vpgl/vpgl_lvcs.h
🚫 Makes breaking changes to vxl/core API that requires semantic versioning increase
✅ Makes design changes to existing vxl/core API that requires semantic versioning increase
🚫 Makes changes to the contributed directory API DOES NOT require semantic versioning increase
🚫 Adds tests and baseline comparison (quantitative)
🚫 Adds Documentation
- Update `vpgl_lvcs` functions for const correctness (ensure all functions which do not change the state of the object instance are const)
- Update `vpgl_lvcs` protected member functions (change name from `set_*_conversions` to `get_*_conversions` and use protected member variables directly)
- Eliminate (now) unnecessary `const_cast` from `vpgl_local_rational_camera`
- tweak version number - now v2.0.2.1
> ENH: vpgl_lvcs const correctness

- .circleci/config.yml
:no_entry_sign: Makes design changes to existing vxl/core\* API that requires semantic versioning increase
:no_entry_sign: Adds tests and baseline comparison (quantitative).
Update circleci scripts (not used by vxl/vxl, but enabled in some forks)
- Users with "enable pipelines" set to ON in advanced settings are currently unable to clear the circleci cache (clearing the cache forces a rebuild of all VXL).  Users may now change their `CACHE_VERSION` build environment variable to generate a new cache.
- ninja build using all available processors …
> ENH: CircleCI caching and build jobs

- core/vpgl/algo/tests/test_camera_compute.cxx
1,0e-6 is the value 1 and the value 0e-6.  1.0e-6 was intended.
> BUG: Test syntax had incorrect values

- contrib/brl/bbas/bpgl/algo/bpgl_rectify_affine_image_pair.cxx
- contrib/brl/bbas/bpgl/algo/bpgl_rectify_affine_image_pair.h
- contrib/brl/bseg/bsgm/bsgm_disparity_estimator.cxx
- contrib/brl/bseg/bsgm/bsgm_disparity_estimator.h
:no_entry_sign: Makes design changes to existing vxl/core/\* API that requires semantic versioning increase
:no_entry_sign: Adds tests and baseline comparison (quantitative).
Contrib changes as follows:
- BSGM: 2x reduction in `bsgm_disparity_estimator` memory consumption  (eliminating separate census and x-gradient matrices, favoring only a single fused matrix) + additional census cost refactoring 
- BGPL: allow user to define invalid pixel fill value for `bpgl_rectify_affine_image_pair`
> PERF/ENH: BSGM memory, BPGL rectification

- contrib/brl/b3p/shapelib/dbfopen.c
- v3p/geotiff/bin/csv2html.c
:no_entry_sign: Makes design changes to existing vxl/core\* API that requires semantic versioning 
:no_entry_sign: Makes changes to the contributed directory API DOES NOT require semantic versioning 
:no_entry_sign: Adds tests and baseline comparison (quantitative)
PR #653 converted atoi -> std::stoi and atof -> std::stod.  This change breaks c-style libraries which are unable to access c++ std library features.   Revert c-style libraries to atoi and atof.  
Note this issue was not caught as VXL tests do not build contrib.
> BUG: revert std::stod/stoi for c-style code

- core/vbl/vbl_local_minima.hxx
- core/vnl/vnl_diag_matrix.h
- core/vnl/vnl_diag_matrix_fixed.h
- core/vnl/vnl_fastops.cxx
- core/vnl/vnl_na.cxx
- v3p/geotiff/geotiff_proj4.c
Compiling vxl with gcc 9.1 identifies new sources of potential weak coding.
Update to address the new warnings.
> Gcc 9 compiler warnings

- CMakeLists.txt
- core/vnl/examples/vnl_polynomial_factoring.cxx
See https://docs.microsoft.com/en-us/cpp/build/reference/fs-force-synchronous-pdb-writes?view=vs-2019
and discussions:
https://discourse.itk.org/t/has-anyone-tried-to-build-visual-studio-c-2019/1561
> COMP: Improve default building of VXL with MSVC 1920-2929 version

- contrib/brl/bbas/bpgl/acal/acal_f_utils.cxx
- contrib/brl/bbas/bpgl/algo/bpgl_rectify_affine_image_pair.cxx
- BPGL rectification was incorrectly checking the bounds of points projected into the images. The bounds are now checked correctly.
- Acal was silently erroring when the affine camera text format it expected was violated. It will now properly return false if the format is invalid.
> BUG: bpgl & acal fixes

- core/vnl/tests/test_rational.cxx
- core/vnl/vnl_rational.cxx
- core/vnl/vnl_rational.h
Fixed issue #664, "vnl_rational should have same size on all platforms":
Added `vnl_rational::int_type`, the integer type of both the numerator
and the denominator, and defined this type as `std::int64_t` to ensure
64-bit integers on all supported platforms. Note that `boost::rational`
also has an `int_type`: www.boost.org/doc/libs/1_71_0/boost/rational.hpp
Extensively used C++ SFINAE (Substitution Failure Is Not An Error) to
avoid redundant code.
Added missing `const` keyword to converting operator for signed
integral types.
Added `test_converting_constructors()` to test_rational.
> ENH: Fix issue #664: vnl_rational numerator, denominator both int64_t

- .travis.yml
Add ctest `--output-on-failure` flag to `.travis.yml` to print test output for any failing test.  Without such information, developers may have difficulty fixing a test failure for travis-specific build environments.
:no_entry_sign: Makes design changes to existing vxl/core\* API that requires semantic versioning increase
:no_entry_sign: Adds tests and baseline comparison (quantitative).
> ENH: travis ctest --output-on-failure

- contrib/brl/bbas/bocl/bocl_device.cxx
- contrib/brl/bbas/bocl/bocl_device_info.cxx
COMP: fixed compiler warnings C4311: 'type cast': pointer truncation in brl/bbas/bocl
> fixed warnings type cast pointer truncation in brl

- contrib/brl/bseg/sdet/algo/sdet_classify.cxx
Fixed a bug in SDET classify, where the valid image bounds could be negative, causing an invalid allocation
> BUG: sdet_classify

- contrib/brl/bbas/bvgl/algo/bvgl_register_ptsets_3d_rigid.h
- contrib/brl/bbas/bvgl/algo/bvgl_register_ptsets_3d_rigid.hxx
- contrib/brl/bseg/betr/tests/CMakeLists.txt
BRL fixes - missing header file and disable failing tests.
:no_entry_sign: Makes design changes to existing vxl/core\* API that requires semantic versioning  
:no_entry_sign: Adds tests and baseline comparison (quantitative).
> COMP: BRL fixes

- CMakeLists.txt
- core/vpgl/tests/test_rational_camera.cxx
- core/vpgl/vpgl_rational_camera.cxx
- core/vpgl/vpgl_rational_camera.h
small enhancement adding a `std::initializer_list` for the `vpgl_rational_order` enumeration allowing easy iteration through all choices (i.e., `for (auto item:  vpgl_rational_order_func::initializer_list) {...}`)
🚫 Makes breaking changes to the `vxl/core/` API that requires semantic versioning increase
✅ Makes design changes to existing `vxl/core/` API that requires semantic versioning increase
🚫 Makes changes to the contributed directory API DOES NOT require semantic versioning increase
> ENH: vpgl_rational_order initializer list

- .travis.yml
Add build caching to travis - on my fork this change reduced CI time for a manually triggered rebuild from 20 min (setup, full core rebuild, test) to 2 min (setup, incremental core rebuild, test).  
Changes include:
- cache entire build directory
- resolve timestamps between git clone and build cache (see below for more info)
- switch from `make` to `ninja`
To elaborate on the timestamp resolution - cloned code timestamps are newer than the build cache, which would typically result in a complete rebuild.  Timestamps are resolved so that a complete rebuild is unnecessary based on CircleCI code from @andyneff.  A good discussion of the issue is found here:
https://blog.esciencecenter.nl/travis-caching-and-incremental-builds-6518b89ee889
Note that admins can always clear the cache should …
> CI: faster travis with build cache

- core/vnl/tests/test_vector.cxx
- core/vnl/vnl_vector.h
- core/vnl/vnl_vector.hxx
Added fast (O(1)), `noexcept` move-constructor and move-assignment
operator to `vnl_vector`.
Added `noexcept` specifier to `vnl_vector::swap`, in order to use it
for the move-assignment implementation.
Added `vnl_vector_test_move_construct()` and `vnl_vector_test_move_assign()`.
> PERF: Add C++11 move-constructor and move-assignment to vnl_vector

- contrib/brl/bbas/bvgl/algo/bvgl_register_ptsets_3d_rigid.h
- contrib/brl/bbas/bvgl/algo/bvgl_register_ptsets_3d_rigid.hxx
- contrib/brl/bbas/bvgl/algo/tests/test_register.cxx
Adding RANSAC registration methods to bvgl_register_ptsets_3d_rigid in bvgl/algo.
> ENH: RANSAC methods in bvgl_register_ptsets_3d_rigid

- core/vnl/io/vnl_io_rational.cxx
> Fix ambiguos function matching with clang9

- core/vpgl/vpgl_rational_camera.cxx
- core/vpgl/vpgl_rational_camera.h
Avoid compiler warning for gcc 5.3.1 by using std::array instead of std::initializer_list.
> COMP: Use lighter weight std::array<> with rigid size of 2

- .travis.yml
- core/vnl/tests/test_vector.cxx
- core/vnl/vnl_vector.h
- core/vnl/vnl_vector.hxx
- core/vpgl/vpgl_radial_tangential_distortion.h
Force function overrides using the override
keyword from C++11.
cd run-clang-tidy.py -extra-arg=-D__clang__ -checks=-*,modernize-use-override  -header-filter=.* -fix
> STYLE: Use override statements for C++11

- .travis.yml
- core/vul/vul_string.cxx
Travis CI update including:
- Fix incremental build issue 
- cached build directory `$PROJ_BUILD_DIR` was @ `/home/travis/build`
- travis stores the source repository in `$TRAVIS_BUILD_DIR`, which turns out to be @ `/home/travis/build/<USER>/<REPO>`
- source repo was thus a subdir of cache build directory, and cache would overwrite source repo on restore
- move build cache `$PROJ_BUILD_DIR` to non-conflicting location `/home/travis/proj/build`
- Ignore cache on pull request or cron job (i.e., always perform a full rebuild before accepting a PR or for a regularly scheduled build)
- Expand travis coverage to test other gcc versions (4, 6, 7) based on
https://docs.travis-ci.com/user/languages/c/#gcc-on-linux
Note that expanded gcc coverage revealed a missing header file in vul_string.h …
> ENH: travis CI update (coverage & cache)

- core/vil/CMakeLists.txt
Adding a TIFF CMake message to VIL, to parallel the GeoTiff message. Useful for determining if VIL will be using your system's libtiff, or v3p's libtiff.
> DOC: TIFF CMake message

- core/vnl/vnl_matrix.hxx
- core/vnl/vnl_vector.hxx
PR #694 recently added a `m_LetArrayManageMemory` member variable to `vnl_matrix` and `vnl_vector`.  Add this new member variable to respective `swap` functions.
🚫 Makes design changes to existing vxl/core/\* API that requires semantic versioning increase
🚫 Makes changes to the contributed directory API DOES NOT require semantic versioning increase
> BUG: vnl_matrix & vnl_vector swap

- core/vnl/tests/test_container_interface.cxx
- core/vnl/tests/test_vector.cxx
- core/vnl/vnl_matrix.hxx
- core/vnl/vnl_vector.hxx
In the move-assignment `operator=` for `vnl_matrix` (see PR #694) when both left-hand side and right-hand side objects manage their own memory, the right-hand side object should finally be invalidated with null data, zero size, and  `m_LetArrayManageMemory` set to a default value of true (not false).  The system segfaults should a user attempt to `std::swap` two matrices.
Set `m_LetArrayManageMemory` to true in move-assignment `operator=` for both `vnl_matrix` and `vnl_vector`.  Add more swap tests, including native swap and `std::swap` for both `vnl_matrix` and `vnl_vector`.
During move-assignment, `vnl_matrix` wrongly reset `m_LetArrayManageMemory` to false.  This is an issue should a user attempt to `std:swap` two matrices (while users should prefer the native `vnl_matrix::swap` …
> BUG: vnl_matrix move-assignment segfault

- contrib/brl/bbas/bvgl/algo/bvgl_register_ptsets_3d_rigid.h
- contrib/brl/bbas/bvgl/algo/bvgl_register_ptsets_3d_rigid.hxx
- contrib/brl/bbas/bvgl/bvgl_k_nearest_neighbors_3d.h
Minor update for `contrib/brl/bbas/bvgl`:
- BUG: let compiler choose appropriate swap method for `bvgl_k_nearest_neighbors_3d` (e.g., prefer `vnl_matrix::swap` over explict `std::swap`)
- STYLE: improve member variable initialization for constructors in `bvgl_k_nearest_neighbors_3d` and `bvgl_register_ptsets_3d_rigid`
- STYLE: code cleanup for `bvgl_k_nearest_neighbors_3d` and `bvgl_register_ptsets_3d_rigid`
🚫 Makes design changes to existing vxl/core/\* API that requires semantic versioning increase
✔️ Makes changes to the contributed directory API DOES NOT require semantic versioning increase
> BUG/STYLE: contrib bvgl update

- contrib/gel/gevd/gevd_edgel_regions.cxx
- contrib/mul/msm/msm_subset_aligner.cxx
- contrib/mul/msm/tools/msm_compare_markup_curves.cxx
- contrib/mul/msm/tools/msm_compare_markups.cxx
- contrib/mul/msm/tools/msm_estimate_residuals.cxx
- contrib/mul/msm/tools/msm_get_shape_params.cxx
- contrib/mul/msm/tools/msm_points_to_matrix.cxx
- contrib/mul/msm/tools/msm_robust_mean.cxx
* COMP: Many compiler errors like this:
error C2039: 'back_inserter': is not a member of 'std'
Solution:
Add the <iterator> header to solve.
> Fix failing build

- contrib/brl/bbas/bpgl/algo/bpgl_rectify_affine_image_pair.cxx
- contrib/brl/bbas/bpgl/algo/bpgl_rectify_affine_image_pair.h
Allow rectification even if points in the zero disparity plane project outside of the scene bounding box. Add a check to ensure the overlap is above a certain percentage.
> ENH: bpgl_rectify_affine_image_pair sliver check

- core/vnl/vnl_matrix.h
- core/vnl/vnl_vector.h
- core/vnl/vnl_vector_ref.h
The derived class of vnl_vector_ref has a specialized destructor that
must be called in order to avoid incorrect memory deallocation.  The
polymorphic behaviors that are depended upon require virtual destructors.
Non-virtual destructors were rationalized as a potential performance gain,
but experimentation in the tests showed no measurable performance difference
after these changes (i.e. the tests took the same amount of time to run
before and after the changes).
> BUG: The vnl_vector & vnl_matrix destructor should be virtual

- contrib/brl/bbas/bpgl/algo/bpgl_rectify_affine_image_pair.cxx
- contrib/brl/bbas/bpgl/algo/bpgl_rectify_affine_image_pair.h
- contrib/brl/bpro/core/bbas_pro/processes/bpgl_rectify_affine_image_pair_process.cxx
- contrib/brl/bpro/core/pyscripts/bbas_adaptor.py
Two minor contrib/brl enhancements
- bpgl rectification parameter operator<<
- 'rectify_z' input argument to rectify_affine_image_pair in bbas python adaptor
🚫 Makes design changes to existing vxl/core\* API that requires semantic versioning increase
✔️ Makes changes to the contributed directory API DOES NOT require semantic versioning increase
> ENH (contrib/brl): operator & input argument

- contrib/brl/bbas/bpgl/algo/bpgl_gridding.h
- contrib/brl/bbas/bpgl/algo/tests/test_gridding.cxx
This commit fixes interpolation instability problems in bpgl_gridding.
This commit includes new test cases that fail without this change.
-  :no_entry_sign:  Makes design changes to existing vxl/core\* API that requires semantic versioning increase
- :no_entry_sign:  Makes changes to the contributed directory API DOES NOT require semantic versioning increase
-  [X] Adds tests and baseline comparison (quantitative).
-  :no_entry_sign: Adds Documentation.
> BUG: regularize solution to improve stability of linear interpolation

- contrib/brl/bbas/bpgl/algo/bpgl_3d_from_disparity.hxx
- contrib/brl/bbas/bpgl/algo/bpgl_gridding.h
- contrib/brl/bbas/bvgl/bvgl_k_nearest_neighbors_2d.h
- contrib/brl/bbas/bvgl/tests/test_k_nearest_neighbors.cxx
Refactor `bvgl_k_nearest_neighbors_2d` to include `max_dist` parameter (in the bnano library, referred to as `max_radius`).  
- If `max_dist` is infinite, functionality is unchanged.
- If `max_dist` is specified as a finite number, the knn function will return at most k nearest neighbors within the specified distance of the interpolation point.
Also includes update where this function is `bvgl_k_nearest_neighbors_2d`, specifically the associated test and `bpgl_gridding`.
avoid depreciation warning regarding implicit cast conversion in `vnl_matrix_inverse`
```
/vxl/contrib/brl/bbas/bpgl/algo/bpgl_3d_from_disparity.hxx: In instantiation of 'vil_image_view<T> bpgl_3d_from_disparity(const vpgl_affine_camera<double>&, const vpgl_affine_camera<double>&, const vil_image_view<T>&) [with T = …
```
> ENH/COMP (contrib): bvgl_k_nearest_neighbors_2d/bpgl_3d_from_disparity

- contrib/brl/bbas/bpgl/algo/bpgl_gridding.h
- contrib/brl/bbas/bpgl/algo/bpgl_heightmap_from_disparity.h
- contrib/brl/bbas/bpgl/algo/bpgl_heightmap_from_disparity.hxx
- contrib/brl/bbas/bpgl/algo/tests/test_gridding.cxx
- contrib/brl/bbas/bpgl/algo/tests/test_heightmap_from_disparity.cxx
- contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.cxx
- contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.h
Refactor `bpgl_gridding` functionality for improved flexibility & test coverage.  This includes
- expected neighbor range (between min/max number of neighbors)
- max neighbor distance as gridding input (not as member of interp. class)
- linear_interp with double internals
- improve linear_interp against new test cases
Update `bpgl_heightmap_from_disparity` and `bsgm_prob_pairwise_dsm` accordingly
🚫 Makes design changes to existing vxl/core\* API that requires semantic versioning increase
✔️ Makes changes to the contributed directory API DOES NOT require semantic versioning increase
> ENH (contrib): bpgl_gridding

- contrib/brl/bbas/bpgl/algo/bpgl_heightmap_from_disparity.hxx
Fixed a bug with extracting the scalar values during bpgl_heightmap_from_disparity::_heightmap_from_pointset.
> BUG: bpgl_heightmap

- core/vpgl/algo/tests/test_fit_rational_cubic.cxx
vpgl/algo fix failing `test_fit_rational_cubic` - use a fixed seed for deterministic random numbers and repeatable results.  
This should stop failures like travisci linked below due to randomness in the test.
https://travis-ci.org/vxl/vxl/jobs/607604654#L1060
🚫 Makes design changes to existing vxl/core\* API that requires semantic versioning increase
🚫 Makes changes to the contributed directory API DOES NOT require semantic versioning increase
✔️ Adds tests and baseline comparison (quantitative).
> BUG: fix failing vpgl/algo test

- core/vnl/vnl_diag_matrix.h
> Address unused parameter method warning.

- core/vnl/algo/vnl_matrix_inverse.h
The as_vector method does not exist.
> DOC: Recommend explicitly using vnl_matrix_inverse.as_matrix()

- core/vnl/vnl_matrix_ref.h
- core/vnl/vnl_vector.hxx
> COMP: address unused parameter warning in default constructor

- contrib/brl/bbas/bpgl/acal/acal_intertile_graph_solver.cxx
We were re-using the same vnl_levenberg_marquardt object in the second pass of the solver. If cameras were filtered out from the first pass, this led to a different number of unknowns, and the solver would fail, leaving the translations to default to (0,0). Fixed this by properly constructing the new vnl_levenberg_marquardt object in the second pass.
> BUG: Acal Intertile Solver

- v3p/bzlib/LICENSE
- v3p/bzlib/README
- v3p/bzlib/blocksort.c
- v3p/bzlib/bzlib.c
- v3p/bzlib/bzlib.h
- v3p/bzlib/bzlib_private.h
- v3p/bzlib/compress.c
- v3p/bzlib/crctable.c
- v3p/bzlib/decompress.c
- v3p/bzlib/huffman.c
- v3p/bzlib/randtable.c
Update the bzlib2 library to the latest version
as found at https://www.sourceware.org/bzip2/downloads.html
> ENH: Update bzlib2 library to latest version

- core/vnl/vnl_drand48.cpp
UBSan found a signed integer overflow. Arithmetic with 6 unsigned shorts gets promoted to signed int, which can then overflow with big numbers. Cast to unsigned long, as in lines preceding, to force unsigned arithmetic, where overflow is well-defined.
> BUG: fixed signed integer overflow by casting to unsigned long

- v3p/geotiff/cpl_serv.h
This reverts commit 901b41bb412ec18e12a7801a331a19e877b55ba3.
This resolves issue #734 of compilation failure, but
re-introduces a compiler warning about implicitly defined
function on some compilers.
> Revert "COMP: Some compilers need both string.h & strings.h"

- contrib/brl/bbas/bpgl/CMakeLists.txt
- contrib/brl/bbas/bpgl/Templates/bpgl_lon_lat_camera+double-.cxx
- contrib/brl/bbas/bpgl/Templates/bpgl_lon_lat_camera+float-.cxx
- contrib/brl/bbas/bpgl/bpgl_geotif_camera.h
- contrib/brl/bbas/bpgl/bpgl_geotif_camera.hxx
- contrib/brl/bbas/bpgl/bpgl_lon_lat_camera.h
- contrib/brl/bbas/bpgl/bpgl_lon_lat_camera.hxx
- contrib/brl/bbas/bpgl/tests/CMakeLists.txt
- contrib/brl/bbas/bpgl/tests/test_driver.cxx
- contrib/brl/bbas/bpgl/tests/test_lon_lat_camera.cxx
- :no_entry_sign:  Makes breaking changes to the vxl/core/\* API that requires semantic versioning increase
-  :no_entry_sign: Makes design changes to existing vxl/core\* API that requires semantic versioning increase
-  :no_entry_sign:  Adds Documentation.
A new class bpgl_lon_lat_camera provides a projection from longitude and latitude arrays to image pixel locations.
> ENH: Lon lat camera rebase

- core/vnl/algo/tests/test_symmetric_eigensystem.cxx
Segmentation fault caused by array being too large.
Making the array smaller avoids exception or
invalid instruction error on windows.
> BUG: Windows fails with too large array size

- core/vpgl/vpgl_rational_camera.h
Fix the comment description of vpgl_rational_camera::set_offset.
> STYLE: vpgl_rational_camera

- contrib/brl/bseg/bsgm/CMakeLists.txt
- contrib/brl/bseg/bsgm/bsgm_error_checking.cxx
- contrib/brl/bseg/bsgm/tests/CMakeLists.txt
- contrib/brl/bseg/bsgm/tests/test_driver.cxx
- contrib/brl/bseg/bsgm/tests/test_error_checking.cxx
- contrib/brl/bseg/bsgm/tests/test_include.cxx
- contrib/brl/bseg/bsgm/tests/test_template_include.cxx
Fixed two bounds errors in bsgm_error_checking::bsgm_compute_invalid_map. Added bsgm tests to confirm fix.
> BUG: bsgm_compute_invalid_map

- contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.cxx
- contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.h
Even though bsgm_prob_pairwise_dsm has downscale_exponent as a parameter, it wasn't passing that parameter to the bsgm_multiscale_disparity_estimator constructor.
> BUG: bsgm_prob_pairwise_dsm downscale_exponent

- contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.h
- contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.hxx
Add a min_overlap_fraction_ parameter to the sgm_param struct used by bsgm_prob_pairwise_dsm, and pass it along to the bpgl rectification. This allows a caller to specify a min_overlap_fraction of 0, to indicate that they don't want a bounds check. This is helpful when purposefully using a scene box much larger than the scene you expect your cameras to cover.
> ENH: bsgm min_overlap_fraction

- contrib/brl/bseg/bsgm/bsgm_disparity_estimator.cxx
- contrib/brl/bseg/bsgm/bsgm_disparity_estimator.h
bsgm_disparity_estimator stores the SGM cost volume as a flattened 1-D vector. The size of this vector is width * height * num_disparities. With moderate image sizes and disparity ranges, this product surpasses the size of a 32 bit signed int, overflowing to a negative value. When this is passed to std::vector::resize(size_t), a much-too-large vector allocation is requested, and the program crashes.
This PR changes the type of the width, height, and num_disparities …
> BUG: bsgm_disparity_estimator overflow

- contrib/brl/bbas/bpgl/algo/bpgl_rectify_image_pair.h
- contrib/brl/bseg/bsgm/CMakeLists.txt
- contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.h
Minor update for contrib/bsgm and contrib/bpgl:
- `bsgm/CMakeLists.txt`: additional cmake link libraries, 
- `bsgm_prob_pairwise_dsm`: add constructors & setup functions, const correctness for accessors, default internal values, spacing
- `bpgl_rectify_image_pair`: spacing
- 🚫 Makes breaking changes to the vxl/core/\* API that requires semantic versioning increase
- 🚫 Makes design changes to existing vxl/core/\* API that requires semantic versioning increase
- 🚫  Adds tests and baseline comparison (quantitative).
- 🚫 Adds Documentation.
> ENH: contrib bsgm & bpgl

- contrib/brl/bbas/bpgl/acal/acal_match_graph.cxx
- contrib/brl/bbas/bpgl/acal/acal_match_graph.h
- Adds getter and setter methods
- Properly assigns an ID to each match_edge object in the graph
> ENH: acal_match_graph adding getters / setters

- contrib/brl/bbas/bpgl/acal/CMakeLists.txt
- contrib/brl/bbas/bpgl/acal/acal_match_graph.h
- contrib/brl/bbas/bpgl/acal/acal_match_utils.h
- contrib/brl/bbas/bpgl/acal/io/CMakeLists.txt
- contrib/brl/bbas/bpgl/acal/io/acal_io_match_graph.cxx
- contrib/brl/bbas/bpgl/acal/io/acal_io_match_graph.h
- contrib/brl/bbas/bpgl/acal/io/acal_io_match_utils.cxx
- contrib/brl/bbas/bpgl/acal/io/acal_io_match_utils.h
- contrib/brl/bbas/bpgl/acal/io/tests/CMakeLists.txt
- contrib/brl/bbas/bpgl/acal/io/tests/test_driver.cxx
- contrib/brl/bbas/bpgl/acal/io/tests/test_generic_io.h
- contrib/brl/bbas/bpgl/acal/io/tests/test_include.cxx
- contrib/brl/bbas/bpgl/acal/io/tests/test_match_graph_io.cxx
- contrib/brl/bbas/bpgl/acal/io/tests/test_match_utils_io.cxx
- contrib/brl/bbas/bpgl/acal/tests/CMakeLists.txt
- contrib/brl/bbas/bpgl/acal/tests/test_driver.cxx
- contrib/brl/bbas/bpgl/acal/tests/test_include.cxx
- contrib/brl/bbas/bpgl/acal/tests/test_match_graph.cxx
- contrib/brl/bbas/bpgl/acal/tests/test_match_utils.cxx
Add contrib/brl acal I/O operations via `vsl_b_write` and `vsl_b_read`.  New unit tests for IO operations.  Other supporting changes.
> ENH: contrib/brl - acal_io

- contrib/brl/bbas/bpgl/acal/acal_f_utils.h
- contrib/brl/bbas/bpgl/acal/acal_match_graph.cxx
- contrib/brl/bbas/bpgl/acal/acal_match_graph.h
- contrib/brl/bbas/bpgl/acal/acal_match_utils.h
- contrib/brl/bbas/bpgl/acal/io/CMakeLists.txt
- contrib/brl/bbas/bpgl/acal/io/acal_io_f_utils.cxx
- contrib/brl/bbas/bpgl/acal/io/acal_io_f_utils.h
- contrib/brl/bbas/bpgl/acal/io/tests/CMakeLists.txt
- contrib/brl/bbas/bpgl/acal/io/tests/test_driver.cxx
- contrib/brl/bbas/bpgl/acal/io/tests/test_f_utils_io.cxx
- contrib/brl/bbas/bpgl/acal/io/tests/test_include.cxx
- contrib/brl/bbas/bpgl/acal/tests/test_match_graph.cxx
- Additional acal_io functionality for `f_params` structure (including serialization & equality operator for serialization unit test)
- `acal_match_graph` unit test.  Includes minor addition to class interface for unit test of incidence matrix load as well as some additional output operators.
- ✔️Adds tests and baseline comparison (quantitative).
- ❌Adds Documentation.
> ENH: contrib/brl - acal io & tests

- contrib/brl/bbas/bpgl/acal/acal_match_graph.cxx
- contrib/brl/bbas/bpgl/acal/acal_match_tree.cxx
- contrib/brl/bbas/bpgl/acal/acal_match_tree.h
- contrib/brl/bbas/bpgl/acal/tests/test_match_tree.cxx
-  :no_entry_sign: Makes changes to the contributed directory API DOES NOT require semantic versioning increase
Adds a guard to the acal_match_tree destructor to prevent segfaults when root_ hasn't been initialized.
> BUG: acal match_tree destructor

- contrib/brl/bbas/bpgl/acal/acal_match_graph.cxx
- contrib/brl/bbas/bpgl/acal/acal_match_tree.cxx
- contrib/brl/bbas/bpgl/acal/acal_match_tree.h
- contrib/brl/bbas/bpgl/acal/tests/test_match_tree.cxx
Update in contrib/brl for `acal_match_tree`:
- nodes now use `std::weak_ptr` to point to parent node, simplifying parent retrieval and eliminating need for custom destructor
- `operator==` & `operator<<` for node & tree
- related updates & unit tests
> ENH: contrib/brl - acal_match_tree update

- contrib/brl/bbas/bpgl/acal/CMakeLists.txt
- contrib/brl/bbas/bpgl/acal/acal_match_graph.cxx
- contrib/brl/bbas/bpgl/acal/acal_match_graph.h
- contrib/brl/bbas/bpgl/acal/tests/test_match_graph.cxx
contrib/brl - `acal_match_graph`updates
- operators for equality & output stream
- unit test for equality
- remove default constructors that allowed invalid vertex & edge
- link acal with parent bpgl
- ❌Makes design changes to existing vxl/core\* API that requires semantic versioning increase
> ENH: contrib/brl acal graph operators

- CMakeLists.txt
- core/vsl/CMakeLists.txt
- core/vsl/tests/CMakeLists.txt
- core/vsl/tests/test_array_io.cxx
- core/vsl/tests/test_driver.cxx
- core/vsl/tests/test_include.cxx
- core/vsl/tests/test_tuple_io.cxx
- core/vsl/vsl_array_io.h
- core/vsl/vsl_array_io.hxx
- core/vsl/vsl_tuple_io.h
- core/vsl/vsl_tuple_io.hxx
- core/vsl/vsl_utils.hxx
- Add std::tuple and std::array serialization capabilities to VSL
- Update VXL minor version from 2.1.2.2 to 2.2.0.0
> ENH: VSL tuple & array

- config/cmake/config/vxl_utils.cmake
Modern cmake features of:
install( ...
COMPONENT Development
COMPONENT Libraries
)
Provides this functionality and used throughout the toolkit and is more
consistent.
NOTE:  This similar change was done in ITK in 2014:
commit eab5021bc8b2730515a62998ae1a96650e845add
Author: Matt McCormick <matt.mccormick@kitware.com>
Date:   2014-06-19 12:26:58 -0500
> BUG: Remove VXL_INSTALL_NO_LIBRARIES and VXL_INSTALL_NO_DEVELOPMENT.

- core/vsl/vsl_map_io.hxx
- core/vsl/vsl_vector_io.hxx
This PR fixes some of the Visual Studio link errors in vnl_io. These are unresolved external symbol errors that come from missing VSL_EXPORT decorations in the relative vsl class. There are still similar errors coming from vnl_io_real_polynomial and vnl_io_real_npolynomial but I'm not yet sure how to fix those.
> BUG: Add missing VSL_EXPORT for io functions to fix VS build errors

- config/cmake/config/VXLIntrospectionConfig.cmake
- core/vnl/CMakeLists.txt
If sse2 build options are requested, require that they
be requested additions of compiler flags.
> COMP: Remove implicit addition of -msse2 flag

- core/vgl/vgl_pointset_3d.h
Adding a warning message to appending pointsets with and without normals. There is not really a good solution to what to do in this case, but it should not silently fail to append.
- :no_entry_sign:Makes breaking changes to the vxl/core/\* API that requires semantic versioning increase
- :no_entry_sign:  Makes changes to the contributed directory API DOES NOT require semantic versioning increase
> ENH: append pointsets

- config/cmake/config/vxl_utils.cmake
- core/vgl/algo/vgl_compute_cremona_2d.h
- core/vgl/tests/test_quadric.cxx
- core/vil/CMakeLists.txt
- core/vnl/CMakeLists.txt
- core/vpgl/algo/tests/test_lens_warp_mapper.cxx
- core/vpgl/algo/vpgl_backproject_dem.h
- core/vpgl/algo/vpgl_equi_rectification.cxx
Refactor `vxl_add_library` as function (local scope eliminates need for `unset` commands) and replace custom parsing code with `cmake_parse_arguments`. 
Add `HEADER_BUILD_DIR` argument to `vxl_add_library`. This lets us conveniently attach the build directory (e.g., `$CMAKE_CURRENT_BUILD_DIR`) to a target's `BUILD_INTERFACE` for build-generated header files (e.g., files derived from *.h.in generated via the `vxl_configure_file` macro).
Add `HEADER_BUILD_DIR` to vnl & vil targets.
Additionally update several core/algo #include directives to standard form
- ❌ Makes changes to the contributed directory API …
> ENH: vxl_add_library refactor

- .circleci/config.yml
- .travis.yml
- config/cmake/config/vxl_utils.cmake
Fix bug introduced in PR #797 - `INSTALL_NOBASE_HEADER_FILES` expects library source files, not library name.  Also add CI install tests to spot check core header files (both standard & build-generated headers) for existence.
Fixes issue #801.
> BUG: install header files

- core/vgl/io/CMakeLists.txt
- core/vgl/io/Templates/vgl_io_pointset_3d+double-.cxx
- core/vgl/io/Templates/vgl_io_pointset_3d+float-.cxx
- core/vgl/io/Templates/vsl_vector_io+vgl_point_3d+float--.cxx
- core/vgl/io/Templates/vsl_vector_io+vgl_vector_3d+float--.cxx
- core/vgl/io/tests/CMakeLists.txt
- core/vgl/io/tests/test_driver.cxx
- core/vgl/io/tests/test_include.cxx
- core/vgl/io/tests/test_pointset_3d_io.cxx
- core/vgl/io/vgl_io_pointset_3d.h
- core/vgl/io/vgl_io_pointset_3d.hxx
Adds VSL support for vgl_pointset_3d\<double\> and vgl_pointset_3d\<float\>.
> ENH: vgl_io_pointset_3d

- core/vnl/tests/test_vector.cxx
- core/vnl/tests/test_vector_fixed_ref.cxx
- core/vnl/vnl_vector.h
- core/vnl/vnl_vector_fixed.h
Replace `vnl_vector[vnl_vector.size() - 1]` by vnl_vector.back().
Also add vnl_vector::front()"
Co-authored-by: Niels Dekker <N.Dekker@lumc.nl>
> ENH: Add front() and back() members to vnl_vector and vnl_vector_fixed

- core/vnl/vnl_c_vector.hxx
The local typedefs "abs_t" and "real_t" both shadow
typedefs declared in the classe's header file.  This
patch removes one redundant typedef, and renames another
so as not to conflict with the same-named typedef
in the parent class.  These warnings were observed on
Arch Linux using g++ version 10.2.0.
> COMP: Address Wshadow Compiler Warnings

- contrib/brl/bbas/bpgl/algo/bpgl_rectify_image_pair.h
- contrib/brl/bbas/bpgl/algo/bpgl_rectify_image_pair.hxx
- contrib/brl/bbas/bpgl/algo/rectify_params.h
- contrib/brl/bbas/bpgl/algo/tests/test_rectify_image_pair.cxx
- contrib/brl/bseg/bsgm/bsgm_census.h
- contrib/brl/bseg/bsgm/bsgm_disparity_estimator.cxx
- contrib/brl/bseg/bsgm/bsgm_disparity_estimator.h
- contrib/brl/bseg/bsgm/bsgm_error_checking.h
- contrib/brl/bseg/bsgm/bsgm_error_checking.hxx
- contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.h
- contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.hxx
- Modify bsgm_prob_pairwise_dsm, bsgm_disparity_estimator, and others to accept a vgl_box_2d<int> target window. SGM processing will then occur within those image bounds. The minimum box values are inclusive, while the maximum values are treated as exclusive.
- Re-design bpgl_rectify_image_pair to separate homography computation from warping, and also support a target window.
> ENH: Windowed BSGM processing

- v3p/openjpeg2/opj_includes.h
Fixes OpenJPEG build error with Visual Studio 16.9
> SRC\vxl\v3p\openjpeg2\opj_includes.h(104,35): error C2169: 'lrintf': intrinsic function, cannot be defined (compiling source file SRC\vxl\v3p\openjpeg2\tcd.c) [BUILD\vxl-build\v3p\openjpeg2\openjpeg2.vcxproj]
Solution copied from ITK
https://github.com/InsightSoftwareConsortium/ITK/pull/2388
https://github.com/InsightSoftwareConsortium/ITK/issues/1967
- ❌  Makes changes to the contributed directory API DOES NOT require semantic versioning increase
> COMP: Fix OpenJPEG build error with Visual Studio 16.9

- contrib/brl/bseg/bsgm/bsgm_disparity_estimator.h
- contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.h
minor contrib/brl updates to eliminate MSVC warnings
- ❌Makes design changes to existing vxl/core\* API that requires semantic versioning increase
- ❌dds tests and baseline comparison (quantitative).
> COMP: contrib/brl bsgm MSVC warnings

- CMakeLists.txt
- core/vil/tests/CMakeLists.txt
- core/vil/tests/test_driver.cxx
- core/vil/tests/test_flatten.cxx
- core/vil/tests/test_math_value_range.cxx
- core/vil/vil_flatten.h
- core/vil/vil_math.h
ENH: add `vil_flatten` to copy `vil_image_view` data into a 1D `std::vector`.  Provides both row-major and column-major implementations.  Add tests.
ENH: add `ignore_nan` argument to `vil_math_value_range_percentiles`, allowing users to process floating point images containing nans.  Add/expand tests.
- ✔️ Makes design changes to existing vxl/core\* API that requires semantic versioning increase
> ENH: vil_flatten & vil_math_value_range_percentiles(ignore_nan)

- core/vnl/tests/test_matrix.cxx
- core/vnl/tests/test_matrix_fixed.cxx
- core/vnl/vnl_matrix.hxx
- core/vnl/vnl_matrix_fixed.hxx
- Replaced a hand-written `for` loop from `vnl_matrix_fixed`.
- Replaced a `for` loop from  from `vnl_matrix` that had a branch inside
the loop.
- Made the two `set_identity()` implementations more similar to each
other.
- Removed brute-force `T(x)` casts from `0` and `1`, as `T` should
support implicit conversion from `0` and `1`.
Added `test_identity()` unit tests.
> STYLE: Small improvements of matrix `set_identity()` member functions

- CMakeLists.txt
- core/vil/file_formats/vil_geotiff_header.h
- core/vpgl/file_formats/CMakeLists.txt
- core/vpgl/file_formats/tests/CMakeLists.txt
- core/vpgl/file_formats/tests/test_driver.cxx
- core/vpgl/file_formats/tests/test_geo_camera.cxx
- core/vpgl/file_formats/tests/test_include.cxx
- core/vpgl/file_formats/vpgl_geo_camera.cxx
- core/vpgl/file_formats/vpgl_geo_camera.h
- core/vpgl/vpgl_lvcs.h
Refactor `vpgl_geo_camera` to permit more flexible construction. Changes are designed to be backward compatible.  
Changes include:
- additional `vpgl_geo_camera` load functions to creste camera on the stack & heap
- make `vpgl_geo_camera` always available, with extra functionality enabled via `HAS_GEOTIFF` directive (e.g., loading from geotiff)
- improve `vpgl_geo_camera` const correctness
- `vpgl_geo_camera` unit tests
- add `vpgl_lvcs::clone` method
- make several existing `vil_geotiff_header` functions public
@decrispell 
- ✔️  Makes design changes to existing vxl/core/\* API that requires semantic versioning increase
- ❌ Makes changes to the contributed directory API DOES NOT require …
> vpgl_geo_camera

- core/vpgl/file_formats/vpgl_geo_camera.cxx
Bug fix - `vpgl_geo_camera::init_geo_camera` return value
> BUG: vpgl_geo_camera::init_geo_camera return value

- contrib/brl/bseg/bsgm/bsgm_disparity_estimator.h
- contrib/brl/bseg/bsgm/bsgm_error_checking.h
- contrib/brl/bseg/bsgm/bsgm_error_checking.hxx
For bsgm_disparity_estimator, always check for shadows if shadow_thresh > 0 via new function bsgm_check_shadows
@decrispell
PR Checklist
❌ Makes breaking changes to the vxl/core/* API that requires semantic versioning increase
❌ Makes design changes to existing vxl/core* API that requires semantic versioning increase
✔️ Makes changes to the contributed directory API DOES NOT require semantic versioning increase
❌ Adds tests and baseline comparison (quantitative).
❌ Adds Documentation.
> ENH: contrib/brl bsgm_check_shadows

- core/vpgl/algo/vpgl_equi_rectification.cxx
> map focal plane rectification homograpies to common image space

- CMakeLists.txt
- vcl/CMakeLists.txt
- vcl/compilers/VXL_COMPILER_INFO_AppleClang_CXX.h
- vcl/compilers/VXL_COMPILER_INFO_Clang_CXX.h
- vcl/compilers/VXL_COMPILER_INFO_GNU_CXX.h
- vcl/compilers/VXL_COMPILER_INFO_Intel_CXX.h
- vcl/compilers/VXL_COMPILER_INFO_MSVC_CXX.h
- vcl/compilers/VXL_COMPILER_INFO_SunPro_CXX.h
- vcl/vcl_compiler.h.in
- vcl/vcl_compiler_detection.h
This is a follow-up to #833. We should be able to revert https://github.com/InsightSoftwareConsortium/ITK/pull/2464 once this is merged.
> Fix CMP0120: The WriteCompilerDetectionHeader module is removed.

- contrib/brl/bbas/bpgl/acal/acal_match_graph.cxx
- contrib/brl/bbas/bpgl/acal/acal_match_tree.cxx
- contrib/brl/bbas/bpgl/acal/acal_match_tree.h
BUG: fix `acal_match_graph::validate_match_trees_and_set_metric` for trees with only a single node (parent discovery for a single-node tree resulted in a segfault)
STYLE: general formatting in `acal_match_graph` and `acal_match_tree`
> BUG/STYLE: contrib/brl acal single node tree

- core/vnl/algo/vnl_svd_fixed.h
- core/vnl/vnl_matrix.h
- core/vnl/vnl_vector.h
Removed template parameters from protected constructors in VNL class definitions to allow successful compilation to avoid the following error with gcc-11 C++20:
error: expected unqualified-id before ')' token
> COMP: Removed constructor template parameters from the VNL library

- core/vnl/vnl_matrix.hxx
This would happen in ITK, in
Modules\Numerics\Statistics\include\itkGaussianMixtureModelComponent.hxx
at line m_Covariance.SetIdentity();
and in a few other places too. See:
https://open.cdash.org/viewTest.php?onlyfailed&buildid=7341011
List of tests that Completed (SEGFAULT) copy-pasted here in case of link rot:
itkExpectationMaximizationMixtureModelEstimatorTest
itkGaussianMixtureModelComponentTest
itkImageClassifierFilterTest
itkSampleClassifierFilterTest7
The bug was introduced by c6c899aaf9cbf7ccabfca1ba35b2248fb611ffbc.
> BUG: fix a crash due to null pointer dereference

- CMakeLists.txt
- core/vil/vil_math.h
`vil_math::isisinf`, `vil_math::isnan`, `vil_math::isfinite`, `vil_math::isnormal` copied from vnl_math, handling a variety of corner cases (e.g., MSVC does not properly implement C++11 conformance for integral types).
Fixes issue #843, @dzenanz, @hjmjohnson 
- ✔️  Makes design changes to existing vxl/core\* API that requires semantic versioning increase
- ❌  Makes changes to the contributed directory API DOES NOT require semantic versioning increase
- ❌  Adds tests and baseline comparison (quantitative).
- ❌  Adds Documentation.
> BUG: vil_math::isnan

- core/vgui/internals/vgui_accelerate_x11.cxx
- core/vil/file_formats/vil_tiff_header.cxx
- core/vnl/algo/vnl_svd.hxx
- core/vpgl/algo/vpgl_equi_rectification.cxx
> TSan issues

- core/vnl/algo/vnl_levenberg_marquardt.cxx
> BUG: fixed buffer overrun in logging code found by ASan

- contrib/brl/bbas/bpgl/algo/bpgl_surface_type.cxx
- contrib/brl/bbas/bpgl/algo/bpgl_surface_type.h
bpgl_surface_type refactor
- formatting, whitespace
- const correctness
- min/max input for color display
- do not write 'no_surface_type' image during `write`
@decrispell 
> STYLE/ENH: contrib bpgl_surface_type

- core/vpgl/file_formats/vpgl_geo_camera.cxx
- core/vpgl/file_formats/vpgl_geo_camera.h
> copy constructor didn't update pixel spacing

- contrib/brl/bbas/bpgl/algo/bpgl_surface_type.cxx
- contrib/brl/bbas/bpgl/algo/bpgl_surface_type.h
- contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.h
- contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.hxx
contrib/brl minor refactoring of `bpgl_surface_type` and `bsgm_prob_pairwise_dsm`
- add missing `throw` statements to some runtime_errors
- parameter/method naming consistency
- new accessors
- save functions throw errors
@decrispell 
- ✔️  Makes changes to the contributed directory API DOES NOT require semantic versioning increase
> ENH: contrib/brl - surface_type

- .circleci/config.yml
Increase circleci resource class to medium+ (3 cores, 6GB RAM).
https://circleci.com/docs/2.0/configuration-reference/#resourceclass
Also increase ninja & ctest job concurrency to `nproc`
Clean build (without build cache) including contrib ran in ~45 min, below the 1 hour cutoff now enforced by CircleCI for free builds.  Builds using a cache and/or builds without contrib will run much faster.
@decrispell 
> circleci resource_class

- contrib/brl/bbas/bvgl/algo/tests/CMakeLists.txt
I wasn't able to configure on cmake 3.22.1 without this change
> COMP Add extensions to that newer cmake is happy

- core/vnl/vnl_math.h
The std::abs in C++11 provides api for int, long, long long,
float, double, and long double.  Prefer to use the native
std::abs variants rather than custom coded versions.
> STYLE: Prefer std::abs over custom code

- core/vnl/algo/vnl_levenberg_marquardt.cxx
In debug builds, the historical test case would
always fail due to '*n==2' and '*p==2' that did
not pass the 'assert(*n >= *p)' strict condition
added in commit 334e913af16bc9356135da32a45c9980f164cab1.
> BUG: Recent assert in debug was too strict

- CMakeLists.txt
VXL minor revision updated to 3.5 in order to allow identification
when vnl_math::abs learned how to consistently process complex numbers,
and the standard types supported by std::abs were preferred over
custom implementations.
[X] Makes breaking changes to the vxl/core/\* API that requires semantic versioning increase
[X] Makes design changes to existing vxl/core\* API that requires semantic versioning increase
> DOC: Change version minor number

- CMakeLists.txt
- core/vpgl/tests/CMakeLists.txt
- core/vpgl/tests/test_driver.cxx
- core/vpgl/tests/test_lvcs.cxx
- core/vpgl/tests/test_utm.cxx
- core/vpgl/vpgl_utm.cxx
- core/vpgl/vpgl_utm.h
New function in `vpgl_utm` allowing users to calculate a WGS84->UTM conversion in a specific UTM zone.  This is useful when points are near a UTM zone boundary - conversion to a user specified zone ensures all UTM coordinates are relative to the same coordinate system.
Update related unit tests
- move UTM tests from `test_lvcs` to new `test_utm`
- add UTM tests for new forcing capabilities
- add basic LVCS tests in WGS84 and UTM coordinate systems
- ✔️ Makes design changes to existing vxl/core\* API that requires semantic versioning increase
- ❌ …
> ENH: vpgl_utm force_utm_zone

- CMakeLists.txt
- core/vpgl/tests/test_utm.cxx
- core/vpgl/vpgl_utm.cxx
- core/vpgl/vpgl_utm.h
Convert between UTM systems.  Useful for converting from one UTM coordiante system (utm_zone_in and south_flag_in) to an 
adjacent UTM coordinate system (utm_zone_out and south_flag_out). Conversion is performed by passing the point through WGS84 coordinates.  Includes tests.
- ✔️ Makes design changes to existing vxl/core\* API that requires semantic versioning increase
- ❌  Makes changes to the contributed directory API DOES NOT require semantic versioning increase
- ✔️  Adds tests and baseline comparison (quantitative).
- ❌> Adds Documentation.
> ENH: vpgl_utm utm2utm conversion

- core/vnl/algo/tests/test_convolve.cxx
- core/vul/vul_timer.cxx
Fixes -Wdivision-by-zero warnings on OpenBSD where CLOCKS_PER_SEC is 100.
> Fixed incorrect assumption that CLOCKS_PER_SEC > 1000

- core/vnl/tests/test_rational.cxx
On OpenBSD 7 on PowerPC:
warning: implicit conversion from 'long long' to 'long' changes value from 1234321234321 to 1665620369 [-Wconstant-conversion]
From the surrounding code and comments, it seems to me this code is only supposed to be used when long is 64 bit.  It's 32 bit on OpenBSD PowerPC.
> Limit a test to occur only when long is 64 bit

- core/vnl/tests/test_na.cxx
- core/vnl/tests/test_rational.cxx
Clang 13 has fewer implied header includes.
The tests must explicitly include <limits> for the
numeric_limits definitions to avoid pre-processor errors like:
error: no member named 'numeric_limits' in namespace 'std'
> COMP: Missing header for std::numeric_limits<>

- v3p/netlib/sparse/spConfig.h
- v3p/netlib/sparse/spDefs.h
- v3p/netlib/sparse/spFactor.c
Clang 13 identifies a value change during an implicit conversion, so
we must set the upperbound carefully.
vxl/v3p/netlib/sparse/spFactor.c:2147:13: warning:
implicit conversion from 'long' to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Wimplicit-const-int-float-conversion]
> COMP: Avoid implicit conversion value change warning

- core/vnl/tests/test_hungarian_algorithm.cxx
The initialization values for the the arrays
are hard-coded in the test at compiletime, so
make them constexpr to assist with exposing
memory errors.
> STYLE: Prefer constexpr for compiletime constants

- contrib/brl/bseg/baml/tests/CMakeLists.txt
- contrib/brl/bseg/sdet/sdet_nms.h
- core/vgl/algo/tests/test_h_matrix_2d.cxx
- core/vgl/algo/vgl_h_matrix_1d.hxx
- core/vgl/algo/vgl_h_matrix_2d.hxx
- core/vgl/algo/vgl_h_matrix_3d.hxx
- core/vgl/vgl_homg.cxx
- core/vgl/vgl_vector_3d.hxx
- core/vnl/io/tests/CMakeLists.txt
- core/vnl/io/tests/test_driver.cxx
- core/vnl/io/vnl_io_matrix.hxx
- core/vnl/io/vnl_io_matrix_fixed.hxx
- core/vnl/io/vnl_io_sym_matrix.hxx
- core/vnl/io/vnl_io_vector.hxx
- core/vnl/io/vnl_io_vector_fixed.hxx
- core/vpgl/algo/vpgl_invmap_cost_function.cxx
- core/vsl/vsl_b_read_block_old.h
- core/vsl/vsl_vector_io.hxx
- vcl/vcl_deprecated.h
There were two deprecation methods defined within VXL.
Prefer to use the compiler supported methods rather than
the circa 2003 manually developed macros.
> ENH: Use modern deprecation methods for VXL.     

- config/cmake/config/vxl_utils.cmake
- v3p/geotiff/CMakeLists.txt
- v3p/netlib/CMakeLists.txt
- v3p/tiff/CMakeLists.txt
- vcl/vcl_deprecated.h
- Disable /MP for several additional v3p libraries, eliminating warnings on MSVC compilers as per #832 
- Implement suggestion to disable /MP for clang-cl compilers from #863 
- `#warning` -> `#pragma message` for MSVC, bug introduced in #899 
@hjmjohnson 
> BUG: /MP and #warning

- core/vpgl/vpgl_affine_tri_focal_tensor.h
- core/vpgl/vpgl_affine_tri_focal_tensor.hxx
- core/vpgl/vpgl_tri_focal_tensor.h
- core/vpgl/vpgl_tri_focal_tensor.hxx
formatting for `vpgl_tri_focal_tensor` and `vpgl_affine_tri_focal_tensor`.  Ran clang-format with vxl configuration file, plus some additional manual formatting.
> STYLE: tri_focal_tensor cleanup

- config/cmake/config/vxl_utils.cmake
PR #901 introduced a new error for some Windows environments where `/MP` broke the build.
Fixed in `vxl_utils.cmake` by adding `/MP` only for CXX files, using a cmake generator function.
> COMP: apply /MP only to CXX

- CMakeLists.txt
- core/vpgl/algo/tests/test_affine_tensor_transfer.cxx
- core/vpgl/tests/test_affine_tri_focal_tensor.cxx
- core/vpgl/vpgl_affine_fundamental_matrix.h
- core/vpgl/vpgl_affine_tri_focal_tensor.h
- core/vpgl/vpgl_affine_tri_focal_tensor.hxx
- core/vpgl/vpgl_fundamental_matrix.h
- core/vpgl/vpgl_tri_focal_tensor.h
- core/vpgl/vpgl_tri_focal_tensor.hxx
Refactor `vpgl_trifocal_tensor` and `vpgl_affine_trifocal_tensor`. Changes include const correctness, virtual/override correctness, improved error reporting, formatting, moving function bodies out of header files, and a bug fix for a previously silent test fail. 
Bump major version as this changes the API for these classes, let me know if that's not appropriate.
@decrispell 
- ✅   Makes breaking changes to the vxl/core/\* API that requires semantic versioning increase
- ✅  Makes design changes to existing vxl/core\* API that requires semantic versioning increase
- ⛔  Makes changes to the contributed directory API DOES NOT require semantic versioning increase
- ✅ Adds tests and baseline comparison (quantitative).
- ⛔ Adds Documentation.
> ENH: vpgl_trifocal_tensor

- contrib/brl/bseg/bsgm/bsgm_error_checking.hxx
- contrib/brl/bseg/bsgm/bsgm_multiscale_disparity_estimator.cxx
- contrib/brl/bseg/bsgm/bsgm_multiscale_disparity_estimator.h
- contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.h
- contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.hxx
> Large disparity

- vcl/tests/test_include.cxx
- vcl/vcl_deprecated.cxx
Raised in ITK nightly dashboard, e.g.:
https://open.cdash.org/viewBuildError.php?type=1&buildid=8350827
> COMP: Fix VNL compile warning about VXL_WARN_DEPRECATED

- config/cmake/config/VXLIntrospectionConfig.cmake
VXL contaminates the CMAKE_REQUIRED_FLAGS that may be used by other packages.  This is only relavant for compilations on i386 machines. As stated in the gcc docs the SSE instruction set is enabled by default when using an x86-64 compiler.
Long-standing problem identified in https://github.com/InsightSoftwareConsortium/ITK/pull/3852
> COMP: Do not contaminate CMAKE_REQUIRED_FLAGS

- core/CMakeLists.txt
- core/vgl/examples/CMakeLists.txt
Turning VXL_BUILD_GUI on, configure, then off caused a build failure due to dependancy not being properly and completely enforced.
> ENH: Missing dependency on build options caused build failure

- core/vnl/tests/test_matrix.cxx
- core/vnl/tests/test_matrix_fixed.cxx
- core/vnl/tests/test_vector.cxx
- core/vnl/vnl_bignum_traits.h
- core/vnl/vnl_decnum_traits.h
- core/vnl/vnl_matrix.h
- core/vnl/vnl_matrix.hxx
- core/vnl/vnl_matrix_fixed.h
- core/vnl/vnl_matrix_fixed.hxx
- core/vnl/vnl_numeric_traits.h
- core/vnl/vnl_polynomial.h
- core/vnl/vnl_polynomial.hxx
- core/vnl/vnl_rational_traits.h
- core/vnl/vnl_sparse_matrix.h
- core/vnl/vnl_sparse_matrix.hxx
- core/vnl/vnl_vector.h
- core/vnl/vnl_vector.hxx
- core/vnl/vnl_vector_fixed.h
- core/vnl/vnl_vector_fixed_ref.h
Resolves #881
The vnl_vector unary minus operator applied to
unsigned type and having a result of unsigned type (it should be signed).
vnl_vector<unsigned short> a(3) { 1, 1, 1 } ;
vnl_vector<short> b = -a;
vnl_vector<short> known= {-1, -1, 1 };
add test to demonstrate incorrect behavior of operator- When operator-() is used on an unsigned vector type, the results are wrong.
> COMP: unary minus result mismatch warning

- core/vpgl/tests/test_lvcs.cxx
- core/vpgl/vpgl_lvcs.cxx
- core/vpgl/vpgl_lvcs.h
`vpgl_lvcs::set_utm` for UTM based LVCS, to force the utm_zone and/or south_flag to a different value.  This is useful when the LVCS is near a UTM zone border and/or the equator, when it is often appropriate to force the LVCS to be defined relative to the neighboring UTM or opposite hemisphere.  Additional functionality to support this feature, and additional tests. 
@decrispell 
- ✅ Adds tests and baseline comparison (quantitative).
- ❌Adds Documentation.
> ENH: vpgl_lvcs::set_utm

- core/vnl/vnl_sparse_matrix.hxx
Made access to the back of a row _O(1)_ (constant-time), rather than _O(n)_. Simplified the loop to find column `c` (in case it is not in the back).
Adding 1000+ columns to the end appears to become more than 5 times as fast. Retrieving existing values from any column appears to become slightly faster than before. Observed using Visual Studio 2022, Release.
> PERF: Speed up `vnl_sparse_matrix::operator()`

- contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.hxx
:no_entry_sign:  Makes changes to the contributed directory API DOES NOT require semantic versioning increase
> fix unsigned char 2

- core/vnl/vnl_sparse_matrix.hxx
Very similar to pull request https://github.com/vxl/vxl/pull/926 commit 653919faf49eaa257d2357e570f7cfa8fb738f0b "PERF: Speed up `vnl_sparse_matrix::operator()`"
Also slightly improved some comment in the implementation of `operator()`
> PERF: Speed up `vnl_sparse_matrix::put(r, c, v)`

- core/vnl/vnl_sparse_matrix.hxx
Speed up `vnl_sparse_matrix::get(r, c)`, similar to 
- pull request https://github.com/vxl/vxl/pull/926
- pull request https://github.com/vxl/vxl/pull/928
Let the "const" `vnl_sparse_matrix::operator()` overload call `vnl_sparse_matrix::get(r, c)`.
> Speed up `vnl_sparse_matrix::get(r, c)`, let "const" `operator()` overload call `get(r, c)`

- core/vpgl/file_formats/vpgl_nitf_RSM_camera.cxx
Read additional fields in NITF RSM metadata.
:no_entry_sign: --> Makes changes to the contributed directory API DOES NOT require semantic versioning increase
> Add tagged record IXSHDL in replacement sensor model

- contrib/brl/bbas/bvgl/algo/bvgl_register_ptsets_3d_rigid.h
- contrib/brl/bbas/bvgl/algo/bvgl_register_ptsets_3d_rigid.hxx
- added error variance calculation to contrib/brl/bbas/bvgl/algo/bvgl_register_ptsets_3d_rigid
- updated class to store linear coefficients after fitting quadric patch during minimize_analytic
- change minimize_mean_z_error so it can now be run using a specified initial_t vector
@decrispell 
> add variance calc to bvgl_register_ptsets_3d_rigid

- core/vpgl/tests/test_utm.cxx
- core/vpgl/vpgl_utm.cxx
`vpgl_utm::transform` calculate utm_zone from longitude values that exceed the typical range of [-180, 180). This permits excursions past the antimeridian which may result in longitude values outside the typical range (e.g., -180.1 or 180.1 degrees).  Includes unit tests to confirm expected operation.
@decrispell 
> ENH: utm_zone

- core/vpgl/tests/test_lvcs.cxx
- core/vpgl/vpgl_lvcs.cxx
Handle `vpgl_lvcs` corner cases around the antimeridian, where longitude changes from 180° to -180°.
- `vpgl_lvcs::local_to_global` for UTM LVCS, unwrap longitude relative to the origin.
- `vpgl_lvcs::global_to_local` limit the longitude difference relative to the LVCS origin to the range [-180, 180).  
Includes unit tests for expected operation.
@decrispell 
- ❌  Adds Documentation.
> ENH: lvcs antimeridian

- core/vnl/vnl_matrix_fixed.hxx
The check that the corresponding number of rows and columns are equal appears redundant, for `vnl_matrix_fixed`.
> STYLE: `vnl_matrix_fixed::is_equal` assume equal number of rows, columns

- core/vnl/tests/test_matrix_fixed.cxx
- core/vnl/tests/test_vector.cxx
- core/vnl/vnl_matrix.hxx
- core/vnl/vnl_matrix_fixed.hxx
- core/vnl/vnl_vector.hxx
It appears that `is_equal` would sometimes return `true` when a vnl_vector or
matrix would contain the floating point value NaN. Fixed by adjusting the
condition for doing a `return false` out of the `for` loop, in `is_equal`.
Added unit tests that compare a vnl_vector or matrix that contains NaN and one
that just contains the value zero.
So with this commit, `{ NaN, ..., NaN } is_equal { 0, ..., 0 }` will return _false_, as it should.
> BUG: Fix `is_equal` support when vnl_vector or matrix contains NaN

- CMakeLists.txt
- core/vpgl/file_formats/vpgl_nitf_rational_camera.cxx
- core/vpgl/file_formats/vpgl_nitf_rational_camera.h
`vpgl_nitf_rational_camera::read` public function.  Allows uses to construct an empty `vpgl_nitf_rational_camera` then populate from a NITF and confirm success.
- ✅  Makes design changes to existing vxl/core\* API that requires semantic versioning increase
- ❌Adds tests and baseline comparison (quantitative).
@decrispell
> ENH: vpgl_nitf_rational_camera::read

- contrib/brl/bseg/bsgm/CMakeLists.txt
> BUG: Link bsgm to acal

- contrib/brl/bbas/bpgl/algo/bpgl_surface_type.cxx
- contrib/brl/bbas/bpgl/algo/bpgl_surface_type.h
Minro changes to `bpgl_surface_type `
- `domain_to_string` and `domain_from_string` as static functions. 
- Additional getters, e.g., `type_image` returned as `vil_image_view<float>`
@decrispell 
- ✅  Makes changes to the contributed directory API DOES NOT require semantic versioning increase
> ENH: contrib bpgl_surface_type

- CMakeLists.txt
- core/vnl/tests/test_vector.cxx
- core/vnl/vnl_vector_fixed.h
- core/vnl/vnl_vector_fixed.hxx
Allows calling `is_equal(rhs, tol)` directly on a `vnl_vector_fixed`.
> ENH: Add `vnl_vector_fixed::is_equal`, just like `vnl_vector::is_equal`

- contrib/brl/bbas/bpgl/acal/acal_single_track_solver.cxx
- contrib/brl/bbas/bpgl/acal/acal_single_track_solver.h
When the number of satellite images is large the pose covariance matrix must be conditioned"
> condition large track solution

- core/vnl/vnl_alloc.h
- core/vnl/vnl_matrix_fixed.h
- core/vnl/vnl_vector.h
- core/vpdl/vpdl_distribution.h
- core/vpdl/vpdl_gaussian.h
- core/vpdl/vpdl_gaussian_indep.h
- core/vpdl/vpdl_gaussian_sphere.h
Remove semicolons at the end of function definitions.
> COMP: Fix -Wextra-semi warnings

- core/vil1/vil1_stream_url.cxx
Replaced the sprintf with std::string. We didn't use snprint since it's not clear 4096 is even big enough to perform the operations. We have to check the return values of snprint which becomes more complex.
At the read from socket into memory, we decided to use the char buffer[4096] lower than where it was initially since std::string where we look at its size won't perform the same result as if char buffer[4096] is used.
>  COMP: Replacement of sprinf by using std::string

- contrib/brl/bbas/bpgl/acal/acal_single_track_solver.cxx
Fixes a bug in acal_single_track_solver.cxx that caused track_3d_point_ to be uninitialized in the case that there is a large track size but the problem is not ill conditioned.
@decrispell 
- :white_check_mark: Makes changes to the contributed directory API DOES NOT require semantic versioning increase
> BUG: contrib acal_single_track_solver

- contrib/brl/bbas/bpgl/acal/acal_match_graph.cxx
- contrib/brl/bbas/bpgl/acal/acal_match_graph.h
- no_entry_sign: --> Adds tests and baseline comparison (quantitative).
> access_match_graph_correspondences

- CMakeLists.txt
- core/vil/Templates/vil_pyramid_image_view+ubyte-.cxx
- core/vil/Templates/vil_pyramid_image_view+ushort-.cxx
- core/vil/vil_pyramid_image_view.hxx
- core/vpgl/vpgl_utm.h
ENH Update image pyramid to work with color images, byte and short images
@decrispell 
> Pyramid image byte changes

- core/vnl/vnl_matlab_print_scalar.cxx
- core/vnl/vnl_matlab_print_scalar.h
Replacement of sprintf to snprintf.
Here only one fix is proposed since it involves doing more involved changes.
Here the snprintf requires the size of buf. Unfortunately, buf, without it’s length, is passed to the function.
We can also see that each function in the file has the same name and a argument list very similar for each of them.
I propose to create at the top a function that has the same name as the others, but with the length of buf added and snprintf used. Then, use that function for the other functions accordingly.
Can I proceed like this for the rest of the functions in the file? Also, should we add a deprecated comment?
>  COMP: Replace sprintf to snprintf

- CMakeLists.txt
Add "...policy_max", sets the maximum policy, and avoid CMake deprecation warnings when the min version is too old.
> Use cmake_minimum_required to set policy.

- core/vnl/tests/test_matrix_fixed.cxx
- core/vnl/tests/test_vector.cxx
- core/vnl/vnl_matlab_print_scalar.cxx
gcc13 imposes more strict conformance to where functions are to be defined.
Need to add missing includes to find the functions.
> Add gcc13 missing headers

- core/vnl/vnl_matlab_print.hxx
Months ago a coleague and I added a safer variant of vnl_matlab_print_scalar() that takes the size of the buffer. Solution was just to use this new variant.
> Fixed a buffer overrun found by ASan

- contrib/brl/bseg/bsgm/bsgm_remove_spikes.cxx
With some versions of GCC, `bsgm_remove_spikes.cxx` throws `error: ‘numeric_limits’ is not a member of ‘std’` when compiling. Including `<limits>` fixes this.
@decrispell 
> COMP: Fix bsgm ‘numeric_limits’ error

- contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.h
- contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.hxx
Contrib `bsgm_prob_pairwise_dsm` - optional overlay of the sun direction line on rectified imagery.
@decrispell 
- ✅  Makes changes to the contributed directory API DOES NOT require semantic versioning increase
> contrib bsgm_prob_pairwise_dsm::overlay_sun_dir

- contrib/brl/bseg/bsgm/bsgm_prob_pairwise_dsm.h
`bsgm_prob_pairwise_dsm::process_with_windows` add missing `compute_invalid_masks`
@decrispell 
- ✅ Makes changes to the contributed directory API DOES NOT require semantic versioning increase
> CONTRIB: bsgm_prob_pairwise_dsm window invalid masks

- contrib/brl/bseg/bsgm/bsgm_disparity_estimator.cxx
This change throws an error instead of accessing an array out of bounds in `bsgm_disparity_estimator.run_multi_dp()` when the width or height is 1. This sometimes happens when a small window is passed to `bsgm_prob_pairwise_dsm` and rectified.
It also trims trailing whitespace in the changed file.
@decrispell 
> BUG: Fix bsgm disparity segmentation fault
